### ISSUE TITLE
Client IP

### ISSUE THREAD

**Issue by Vikaton** [sinatra/sinatra#1003]
Do you guys request the visitors IP from the HTTP headers the client sends or somewhere else?

**Comment by kgrz** [comment]
If I understand this correctly, this can be done by accessing the `HTTP_REFERER` from the `request` object inside any route block. 

http://www.sinatrarb.com/intro.html#Accessing%20the%20Request%20Object

--

Kashyap

**Comment by kytrinyx** [comment]
Yes, this is the recommended approach. Thanks @kgrz
