### ISSUE TITLE
error Mongoid::Errors::DocumentNotFound does not pass

### ISSUE THREAD

**Issue by adrianotadao** [sinatra/sinatra#1005]
Hi all,

I'm trying to handle error with sinatra but does not works to me.

Look at this:

**Works**
```ruby
get '/' do
  begin
    Namespace.find(params[:id])
  rescue Mongoid::Errors::DocumentNotFound
    #Here works
  end
end
```

**Does not works**
```ruby
error Mongoid::Errors::DocumentNotFound do
  #Does not pass here
end
```

I'm using:

```
gem 'sinatra', '1.4.6'
gem 'mongoid', '4.0.2'
```

Any idea?

**Comment by kytrinyx** [comment]
Do you have the same issue if you create your own error type? e.g.

```
class FancyError < StandardError
end

error FancyError do
  # does this work?
end
```

**Comment by adrianotadao** [comment]
Hi @kytrinyx,

That way, works. But it would be much better if it works as:

```
error Mongoid::Errors::DocumentNotFound do
end
```

**Comment by kytrinyx** [comment]
Yes, I wasn't suggesting that you should wrap the mongoid error, I'm trying to figure out how to reproduce this with the smallest amount of code.

Would you be able to write a small one-file app that shows the problem, and link to it as a gist?

**Comment by adrianotadao** [comment]
@kytrinyx thank you for your time ...

I made an [example](https://dl.dropboxusercontent.com/u/2987816/sinatra_error.zip) with sinatra and mongoid. Could you take a look?

Thanks a lot.

**Comment by adrianotadao** [comment]
@kytrinyx Hello... If you think that is a bug, I can try to fix this. :+1:

**Comment by kytrinyx** [comment]
Hi, sorry -- I've got this on my list to look at, but I just moved house so the past 2 weeks have been really chaotic. I'm planning on catching up with everything this weekend.

**Comment by kgrz** [comment]
@adrianotadao Hello, I've tried to get a sample script working: https://gist.github.com/kgrz/a6f8a6e9b18cac459592


Can you confirm that the setting `set :show_exceptions, :after_handler` is present in your code you're trying out? I haven't used the mongoid gem, so if this doesn't help, I will try it with that.

**Comment by adrianotadao** [comment]
Hello @kgrz,

It almost worked like I want, when I've set:

```ruby
set :show_exceptions, :after_handler, 
```

The exception went to:

```ruby
error Mongoid::Errors::DocumentNotFound do
  halt 404
end
```

Until here, is perfect! But the problem starts over here. First, I need to change my mongoid.yml setting to:

```ruby
development:
  options:
    raise_not_found_error: true
```

So, when the application throws a NotFound exception, their logs contain this:

```bash
127.0.0.1 - - [12/Jun/2015:14:37:13 -0300] "GET /notifications/foo/ HTTP/1.0" 404 - 0.0085
2015-06-12 14:37:26 - Mongoid::Errors::DocumentNotFound - 
Problem:
  Document(s) not found for class Site with id(s) 1111.
Summary:
  When calling Site.find with an id or array of ids, each parameter must match a document in the database or this error will be raised. The search was for the id(s): 1111 ... (1 total) and the following ids were not found: 1111.
Resolution:
  Search for an id that is in the database or set the Mongoid.raise_not_found_error configuration option to false, which will cause a nil to be returned instead of raising this error when searching for a single id, or only the matched documents when searching for multiples.:
```

The ideal is the application just halt 404, like below, without the Mongoid Exception:

```bash
127.0.0.1 - - [12/Jun/2015:14:37:10 -0300] "GET /notifications/foo/ HTTP/1.0" 404 - 0.0495
```

Do you understand? If you don't understand, I can explain with another way ... and sorry, I'm not a native English. =D

Thanks a lot!

**Comment by zzak** [comment]
@adrianotadao Is the 404 page still rendered for this exception?

My concern is the exception is handled properly, but still raised in the log -- in this case it might be affected by the `show_exceptions` logic.

**Comment by codeworm96** [comment]
I investigated the behavior using the sample script: https://gist.github.com/kgrz/a6f8a6e9b18cac459592.
I found this behavior is affected by the [handle_exception!](https://github.com/sinatra/sinatra/blob/master/lib/sinatra/base.rb#L1097) method's logic. According to the documentation and the code, the option `show_exceptions` decides whether
to show a stack trace in the browser when an exception happens while `dump_errors` decides whether to display errors in the log. In this case the `show_exception` option works well. But `dump_errors` is enabled. So before the exception is handled by the error handler, the `dump_errors!` method will be called (L1114), which will print the log of the exception.

**Comment by adrianotadao** [comment]
Hi @zzak ... sorry for the delay ...

I'm still receiving an unexpected exception. With ActiveRecord, this works well, but, with Mongoid::Document does not

Look at my gif.. I was running my example... 

![](http://g.recordit.co/X0Xguqvefa.gif)

**Comment by zzak** [comment]
Actually, I think you are seeing this because it's expected behavior. Let me explain.

When running under development, by default `show_exceptions` is enabled, this means that unless you `set :show_exceptions, :after_handler` you won't see the result of `error { }` blocks except for production (where `show_exceptions` is disabled).

It's actually documented here: https://github.com/sinatra/sinatra/blob/master/README.md#available-settings see `show_exceptions` section.

For a full example:

```ruby
require 'mongoid'
require 'sinatra'

Mongoid.configure.connect_to("zomgoid")

class MyDocument
  include Mongoid::Document
  field :title
end

error Mongoid::Errors::DocumentNotFound do
  "Couldn't find that one, sorry!"
end

# You MUST set this in order to see the result of error {} in development
set :show_exceptions, :after_handler

get '/:id' do
  doc = MyDocument.find(params[:id])
  doc.title
end
```

**Comment by adrianotadao** [comment]
@zzak I tested here but, thank you. This is closed for me too. By the way, I don't work in this project anymore... I'm working in another company now.

Thanks for your time.
