### ISSUE TITLE
Two gets when sending attachment and session is lost in the second get

### ISSUE THREAD

**Issue by J-F-Liu** [sinatra/sinatra#1008]
The code is:
~~~~~~~~~~~~~~~
enable :sessions
get '/open/:url' do
  p session
  content_type 'application/internet-shortcut'
  headers "Content-Disposition" => 'inline; filename="folder.url"'
  "[InternetShortcut]\r\n"+"URL=file:///#{params[:url]}"
end
~~~~~~~~~~~~~~~

Access http://127.0.0.1:4567/open/%5C%5C172.16.100.14%5Clibm%5C005%5CZY2206%5C3 
The screen log is:
~~~~~~~~~~~~
{"session_id"=>"6080cb0c03e2ae4a62283594961ad19bce8d8d85e50b16241fe82258e6a31436", "csrf"=>"35f53c900ee3349498b7b24b557bdb87", "tracking"=>{"HTTP_USER_AGENT"=>"
a3dbdacb9716b38bdd2474612eba2412460e94d6", "HTTP_ACCEPT_LANGUAGE"=>"ca4aee0e81214addc5fb12877cf9e5c8b8beb7d6"}}
127.0.0.1 - - [28/May/2015:10:15:29 +0800] "GET /open/%5C%5C172.16.100.14%5Clibm%5C005%5CZY2206%5C3 HTTP/1.1" 200 65 0.0130
{}
127.0.0.1 - - [28/May/2015:10:15:29 +0800] "GET /open/%5C%5C172.16.100.14%5Clibm%5C005%5CZY2206%5C3 HTTP/1.1" 200 65 0.0100
~~~~~~~~~~~~

Session should not lost, otherwise user needs to login again.

**Comment by zzak** [comment]
Are you using [rack-protection](https://github.com/sinatra/rack-protection)?

**Comment by J-F-Liu** [comment]
@zzak I'm using padrino.
I also found that this issue is browser related. [Sogou](http://ie.sogou.com/) sends two gets to download file beforehand.

**Comment by zzak** [comment]
It seems like padrino uses [rack-protection](https://github.com/padrino/padrino-framework/blob/f05e39d2aed4e33f7b26ea0370ee54b0144b8de7/padrino-core/padrino-core.gemspec#L35) in core.

Can you verify your protection settings? It looks like the defaults are set here:
https://github.com/padrino/padrino-framework/blob/f05e39d2aed4e33f7b26ea0370ee54b0144b8de7/padrino-core/lib/padrino-core/application/application_setup.rb#L68

**Comment by J-F-Liu** [comment]
The settings are
```
  class App < Padrino::Application
    ...
    register Padrino::Admin::AccessControl
    enable :sessions
    enable :authentication
```

**Comment by zzak** [comment]
I wonder what `set :protection`, and `set :protection_from_csrf` do in padrino

**Comment by zzak** [comment]
So based on the default behavior of `Rack::Protection::SessionHijacking`, if any of those keys from the session change, the session will be dropped: https://github.com/sinatra/rack-protection/blob/f8d8ee2eb72f707d17b07c48bc55a8906978ea5d/lib/rack/protection/session_hijacking.rb#L15

My guess is a new session is created by the third-party, and rack-protection is actually doing the right thing.

**Comment by J-F-Liu** [comment]
@zzak Yes, so this is caused by browser's bug.

**Comment by zzak** [comment]
Let's close this ticket then, thank you for confirming! <3
