### ISSUE TITLE
How to serve static content under a folder without filename specified like an index.html or default.html?

### ISSUE THREAD

**Issue by daluu** [sinatra/sinatra#1015]
I was looking at the readme for Sinatra, 

http://www.sinatrarb.com/intro.html

there's a section for static files. I don't see any other documentation regarding static files on the sinatrarb site.

I used a custom directory and got that working. But what's not clear is that a typical web server setup of

http://site.com/path

would serve the corresponding root file: index.htm, index.html, default.htm, default.html, etc. if any such file exists. And that may be customizable for what the name and extension of the file might be though usually is index or default and end with ".htm" or ".html".

It seems Sinatra does not simulate that behavior, and one must specifically request the filename after the resource path.

Is there a way to map serving a specific file when no filename specified after path? Or must I write a handler method that instead reads a default file (as text string) and return that as a workaround? I had hope for the easy static files route.

Please add such support if missing or add/update docs if feature exists.

**Comment by daluu** [comment]
Guess this has been asked before: http://stackoverflow.com/questions/2437390/serving-static-files-with-sinatra

**Comment by daluu** [comment]
Found previous, related issue: https://github.com/sinatra/sinatra/issues/30, but it's not clear regarding the status of that, doesn't seem to be part of core Sinatra.

**Comment by kgrz** [comment]
```ruby
require 'sinatra'

set :public_folder, File.dirname(__FILE__)
```

This would work if you want the behaviour of a normal webserver (the index page would be accessible at `<host>/index.html` and not `<host>/`, though. You probably figured this out).


To keep the routing logic simple, Sinatra doesn't check for the presence of a default index file in the folder you've requested. You'd need to explicitly specify a handler and use `send_file`.  Sinatra doesn't try to guess the folder structure based on the URL fragment you provide. For example, in the case of the following, Sinatra doesn't try to look at `<app file location>/some/hierarchy` automatically. It relies on the user to set the template that should be rendered.

```ruby
get '/some/hierarchy' do
  # do something here
end
```

Note that using Sinatra for serving a static website is overkill. It's useful if you have a component that requires compilation/interpolation like ERB templates. You might want to use WEBrick or any other rack handlers to achieve the functionality you're looking for, and get rid of the routing overhead that Sinatra carries.

For example:

```ruby
require 'webrick'

server = WEBrick::HTTPServer.new Port: 1234
server.mount '/', WEBrick::HTTPServlet::FileHandler, 'path/to/static/files'
trap("INT") { server.stop }
server.start

# example taken from: http://tobyho.com/2009/09/16/http-server-in-5-lines-with/
```

Would run a small servlet that would serve the static files. Similar examples will exist for other Rack-based servers like Puma etc.

**Comment by starrychloe** [comment]
Yeah, there should be an set option for a default index file, like Apache.

https://httpd.apache.org/docs/2.2/mod/mod_dir.html#directoryindex

    set :public_dir, File.dirname(__FILE__) + '/www', {:directory_index => 'index.html'}

**Comment by daluu** [comment]
@starrychloe is that a suggestion for implementation that you are providing or a tip (that that functionality currently exists)? For the latter, I gave it a try and it does not work, still have to specify the explicit file.

**Comment by daluu** [comment]
@kgrz sinatra for static site is indeed overkill, what do you recommend in the case of mixed use where we define REST APIs that do stuff (non-static) as well as want to serve static files as well from the same "server" instance? Should one stick with Sinatra then, or implement things in a specific way?

**Comment by zzak** [comment]
I'd recommend [Jekyll](https://github.com/jekyll/jekyll) for static sites, or service static assets from the web server so you don't hit the Sinatra stack.

Ofcourse, you can use Sinatra to serve static files, but I don't think this is a main use-case so I'm hesitant to approve more features for this use.

**Comment by erhard** [comment]
Is it possible to reopen this issue. If you have the feature of loading a default index.html than it is possible to mix static site generators like Hugo which serves the static parts with the dynamic of a ruby data server. So it is a feature request.

**Comment by mwpastore** [comment]
@erhard This is outside the scope of Ruby/Sinatra. Your web server should serve static files and proxy requests for dynamic content to your application server. This is trivial to do in any modern web server such as Nginx, Caddy, etc.

**Comment by erhard** [comment]
Yes you are totally right, but why then serving even an index page or the sendfile method ?. Sinatra is so easy building up an infrastructure for a lot of things with one thing namely Sinatra. Sinatra is a swiss knife in my eyes and should have this feature too. But anyway from the strikt point of view you are right. From the pragmatic point of view…. 
I use the sinatraserver as a test and development server for json requests goining in a content system. If sinatra would be able to server all the contents too it would be much easier for me.

**Comment by mwpastore** [comment]
```ruby
require 'sinatra'

configure :development do
  set :public_folder, '/path/to/hugo'
end

if development?
  get '/' do
    redirect to('/index.html')
  end

  get '/index.html' do
    send_file File.expand_path('index.html', settings.public_folder)
  end
end
```

Is that insufficient for some reason? What else do you want/need?

**Comment by Merovex** [comment]
I know this is closed, but for anyone who might follow, I found an approach that works by avoiding Sinatra:

#Gemfile 
`gem 'rack-contrib'`

#config.ru 
```
require 'rack'
require 'rack/contrib/try_static'

# enable compression
use Rack::Deflater

# Avoid Sinatra
use Rack::TryStatic,
    :root => "_site",  # static files root dir
    :urls => %w[/],     # match all requests
    :try => ['.html', 'index.html', '/index.html'] # try these postfixes sequentially
# otherwise 404 NotFound
run lambda { [404, {'Content-Type' => 'text/html'}, ['whoops! Not Found']]}

require File.expand_path('sinatra/my_app.rb', File.dirname(__FILE__))
run MyApp
```
