### ISSUE TITLE
Route — Get Matching Route from Request?

### ISSUE THREAD

**Issue by abhillman** [sinatra/sinatra#1032]
Thank you kindly for a great project!

Suppose I define a route like:

```
get '/api/names/:first_name/:last_name' do |first_name, last_name|
    "Hello, #{first_name}!"
end
```

Supposing I make a request to this route — I can inspect `request.path_info` and will get something like `/api/names/john/smith`. Is there some way to inspect the request and read off the route as it was defined — i.e. get back `/api/names/:first_name/:last_name`. Are these information lost by the time a controller is called?

Thank you!

**Comment by kgrz** [comment]
You could get some information out of `request.env["sinatra.route"]` or
`@env["sinatra.route"]`.

Another way perhaps would be to define the path regex as a constant, and
reuse that instead. For example:

```ruby

require 'sinatra'

NAME_ROUTE = "/api/:firstname/:lastname"

get NAME_ROUTE do |firstname, lastname|
  puts "hello #{firstname}"
  puts "I'm inside #{NAME_ROUTE}"
end
```

--
Kashyap Kondamudi

**Comment by kgrz** [comment]
You could get some information out of `request.env["sinatra.route"]` or
`@env["sinatra.route"]`.

Another way perhaps would be to define the path regex as a constant, and
reuse that instead. For example:

```ruby

require 'sinatra'

NAME_ROUTE = "/api/:firstname/:lastname"

get NAME_ROUTE do |firstname, lastname|
  puts "hello #{firstname}"
  puts "I'm inside #{NAME_ROUTE}"
end
```

**Comment by zzak** [comment]
I wonder if this would be easier with Mustermann.. but there seems to a workaround (just use Ruby:tm:) so I'm giving this a close.
