### ISSUE TITLE
No documentation for Radius

### ISSUE THREAD

**Issue by 101arg101** [sinatra/sinatra#1040]
After looking all over Google to find any documentation for creating Radius tags for Sinatra (or even any kind of Radius usage with Sinatra) it looks like there isn't any. Could somebody write some documentation?

**Comment by grahamlyons** [comment]
That somebody could be you! Why not have a go and open a pull request?

**Comment by kennym** [comment]
@101arg101 I wonder if you have seen the README section about Radius templates: https://github.com/sinatra/sinatra#radius-templates

**Comment by zzak** [comment]
I'm not familiar with Radius, maybe it means the [jlong/radius](https://github.com/jlong/radius) project?

I would expect the documentation for the markup to be found on the upstream project, we're only maintaining the render interface.

Maybe we can close this issue as is, I'm not sure we want to maintain markup documentation for every supported template language.
