### ISSUE TITLE
change CHANGES to CHANGELOG.md

### ISSUE THREAD

**Issue by ashleygwilliams** [sinatra/sinatra#1042]
move the file and update the `CONTRIBUTING.md` doc.

**Comment by ashleygwilliams** [comment]
anything else that would need to happen for this @TrevorBramble ?

**Comment by TrevorBramble** [comment]
@ashleygwilliams The release task references the file directly. https://github.com/sinatra/sinatra/blob/52b9a798a71ac3594be44c99f3fa786bbe6c8824/Rakefile#L185

**Comment by ashleygwilliams** [comment]
cool @TrevorBramble !! anyone who address this issue should also be sure to change in that file! let us know if you need help!

**Comment by kimroen** [comment]
This issue seems to be fixed by #1043, so it can probably be closed. (Thanks, @Zemmiph0bia!)

**Comment by kytrinyx** [comment]
good call, thanks.
