### ISSUE TITLE
Removing fork label

### ISSUE THREAD

**Issue by raventid** [sinatra/sinatra#1046]
Hello! 
Is it possible to remove fork label from this repository? (I'm really don't wanna seem impolite, I respect bmizerany repo!) New github users have a hard time trying to find sinatra source code because it does not appear in search results. I know that there is a reference at the top of the bmizerany page - (offically at github.com/sinatra/sinatra), but it is not the same as see the link in search results.

It might seem inconsiderable, but the devil is in the detail :)

**Comment by zzak** [comment]
That's not our call.
