### ISSUE TITLE
Access to figaro configuration

### ISSUE THREAD

**Issue by Javix** [sinatra/sinatra#1047]
I can't figure out why my Figaro keys are not recognized in a Sinatra app:

```
#main.rb

require 'sinatra'
require 'sinatra/reloader' if development?
require 'figaro'

get '/:logger' do
  logger = params[:logger]
  message = Figaro.env.message?
  "Using logger: #{logger} said #{message}"
end
```

Here the application.yml:
```
jar: org.apache.log4J
pattern: ddMMyyyy
level: INFO
message: Hey LOG4J
```
When I run `ruby main.rb`and access to http://localhost:4567/log4j, I always get:
```
Using logger: log4j said false
```
my config.ru file:
```
require 'sinatra'
require 'figaro'
require './main'

run Sinatra::Application
```
Any idea on what is wrong here ? Thank you.

**Comment by Fnux** [comment]
I can't check right now about Figaro but this code should work (without figaro) 
```
require 'yaml'
CONFIG =  YAML.load_file('application.yml')
message = CONFIG['message']
```
Also, you're calling `Figaro.env` which is : 

> a convenience that acts as a proxy to ENV

But where is `ENV` defined ? And where are you telling Figaro to load the application.yml file ?

**Comment by Javix** [comment]
Sure, it is a standard way to read a YAML file. As for `?`after `message`, I know, it is just a way to check if the specified key exists in the application.ml file (see https://github.com/laserlemon/figaro for more examples). I was wondering why the way Figaro is used in a Rails app does not work in Sinatra app.

**Comment by Fnux** [comment]
Ow. Rails do a lot of things itself and Figaro seems to be build especially for rails. You will have to hack/tweak few things if you want to use with sinatra...

* [Intersting stuff about Figaro and Sinatra](https://github.com/laserlemon/figaro/issues/60)
* [Something call figaro-sinatra](https://github.com/chytreg/sinatra-figaro)

**Comment by Javix** [comment]
Ah, thank you for sharing, I'll take a look at that.

**Comment by kgrz** [comment]
@Javix Is your problem solved? Do you think this is a good case to add to sinatra-recipes or somewhere?

**Comment by Javix** [comment]
@kgrz Nope, unfortunately I had no time to look more deeper that links.

**Comment by zzak** [comment]
I have no idea about figaro, is this third-party integration issue?
