### ISSUE TITLE
sinatrarb.com has expired (pending renewel)

### ISSUE THREAD

**Issue by Alexendoo** [sinatra/sinatra#1048]
http://www.sinatrarb.com/

Uh oh ^^

**Comment by kgrz** [comment]
@Alexendoo Thanks for noticing this. I've pushed a mirror here: http://sinatra.kgrz.io until this gets renewed. Sorry about the trouble.

**Comment by bmizerany** [comment]
My bad. I've renewed it. It should be back any minute. Thank you for reporting!

**Comment by bmizerany** [comment]
@kgrz Thank you for the mirror. Much appreciated.
