### ISSUE TITLE
Redirect loop www.sinatrarb.com

### ISSUE THREAD

**Issue by lvonk** [sinatra/sinatra#1049]
I get this error when trying to access www.sinatrarb.com. This webpage has a redirect loop ERR_TOO_MANY_REDIRECTS.

![screen shot 2015-11-16 at 14 54 52](https://cloud.githubusercontent.com/assets/104943/11183448/075ad862-8c72-11e5-9edc-f0e516859fbc.png)

**Comment by kytrinyx** [comment]
I'm also getting redirects. http://www.sinatrarb.com redirects to https://sinatra.github.com, which if I reload it redirects back to www.sinatrarb.com and so on. It seems like http://sinatrarb.com (without the `www`) redirects to www.sinatrarb.com, but I kind of lost track.

**Comment by mattwildig** [comment]
There seem to be two `A` records for `sinatrarb.com`:

```
$ dig sinatrarb.com
<snip>
;; ANSWER SECTION:
sinatrarb.com.		99	IN	A	50.63.202.9
sinatrarb.com.		99	IN	A	192.30.252.154
```

The 50.63.202.9 address is Godaddy (according to `whois`), which is sending the redirect:

```
$ curl -v sinatrarb.com
<snip>
*   Trying 50.63.202.9...
* Connected to sinatrarb.com (50.63.202.9) port 80 (#0)
<snip>
< HTTP/1.1 302 Found
< Location: https://sinatra.github.io
```

`sinatra.github.io` then redirects back to `sinatrarb.com`. 

The `192.30.252.154` address is the Github pages address, i.e. the “real” address.

It looks like this `50.63.202.9` entry has been added in the recent renewal (or possibly it was there before but the order has changed). I think there should only be the one, pointing to `192.30.252.154`.

**Comment by TrevorBramble** [comment]
@bmizerany Hey, Blake. Looks like we need some nameserver love again.

**Comment by bmizerany** [comment]
Fixed. I think. Please test.

**Comment by bmizerany** [comment]
Thank you @TrevorBramble for relentlessly hunting me down!

**Comment by TrevorBramble** [comment]
@bmizerany :smile: Working here. Should be good, modulo DNS propagation latency. Thank you!

**Comment by Temikus** [comment]
Seems like this is reoccurring @bmizerany 
Probably due to the CNAME

```
λ dig www.sinatrarb.com                                                                                                                                                                                                 ...
;; ANSWER SECTION:
www.sinatrarb.com.	3599	IN	CNAME	sinatrarb.com.
sinatrarb.com.		599	IN	A	184.168.221.28
```
