### ISSUE TITLE
Incorrect rack requirement for showexceptions file

### ISSUE THREAD

**Issue by djsegal** [sinatra/sinatra#1055]
-----------------

I was getting this error when booting up my rails app:

```
activesupport/lib/active_support/dependencies.rb:302:in `require': 
    cannot load such file -- rack/showexceptions (LoadError)
```

------------------

+ The error was addressed in the issue: 
  - https://github.com/rack/rack/issues/978#issuecomment-165690896

+ And can be fixed by requiring the correct (new) show_exception file inside sinatra. 
  - there was a rename from `showexception` to `show_exception`

------------------

**Comment by djsegal** [comment]
This actually opens up several rack issues covered in PR #1056

**Comment by djsegal** [comment]
This was a problem with an out of date rack version.

Resolved by: https://github.com/sinatra/sinatra/pull/1033

**Comment by sgringwe** [comment]
@djsegal what is the planned merge and release for #1033? Is there an immediate solution for this error?

**Comment by jaredbeck** [comment]
Are there any plans to backport this fix to 1.4?  Potentially an easy backport, and would allow 1.4 users to run on rack 2.

**Comment by kytrinyx** [comment]
I'd be happy to backport this. @zzak @TrevorBramble @ashleygwilliams @kgrz -- any objections?

**Comment by kgrz** [comment]
I'm worried about the changed `Rack::File` API/usage in Rack 2.x. It might break Sinatra 1.4.x's use of Rack::File. #1045 uses the newer API, but including that for 1.4.x would be a breaking change.

**Comment by kytrinyx** [comment]
Ah, yes, you're right. If we do back-port this, we'd also need to back-port the changes you made in #1045. It doesn't look like the 1045 PR changes the public API of Sinatra itself, so at first blush that seems like it could work. Am I missing anything else here?

**Comment by TrevorBramble** [comment]
Given the known details I think backporting is the right thing.

**Comment by kytrinyx** [comment]
OK, cool. I'll assign this one to myself.

**Comment by kytrinyx** [comment]
I've taken another look at this. The idea would be to only support rack 2.0, right?

**Comment by zzak** [comment]
I think supporting Rack 2.0 only is the easiest way to move forward

**Comment by kytrinyx** [comment]
Yeah, I think so to. I'm going to un-assign this. At first blush there's a little bit more work that needs to go into this than just cherry-picking the commits in question.

**Comment by zzak** [comment]
This should be fixed.

**Comment by jaredbeck** [comment]
> This should be fixed.

It is fixed by https://github.com/sinatra/sinatra/commit/5993492eccfda74c3cc60760073a4b037662f5d3 in `1.4.7`, right? Thanks!

**Comment by MichaelCPell** [comment]
Confirming that I solved this by adding `gem 'sinatra', '2.0.0.beta2'` to gemfile.

**Comment by rushingfitness** [comment]
If you're using grape, there's a conflict using 2.0.0.beta2 as it depends on `'mustermann', '1.0.0.beta2'` which `grape 0.19.2` (highest current version) depends on `mustermann (~> 1.0.0)`:

    Bundler could not find compatible versions for gem "mustermann":
      In Gemfile:
        mustermann (= 1.0.0.beta2)
    
        grape was resolved to 0.19.2, which depends on
          mustermann-grape (~> 1.0.0) was resolved to 1.0.0, which depends on
            mustermann (~> 1.0.0)

**Comment by mwpastore** [comment]
@rushingfitness Try `2.0.0.rc2` instead.

**Comment by rushingfitness** [comment]
@mwpastore I could kiss ya! Thanks man, don't know how I missed the rc's :)
