### ISSUE TITLE
Puma / Sinatra / Duplicate logs

### ISSUE THREAD

**Issue by Edwardzyc** [sinatra/sinatra#1057]
Puma with sinatra creates duplicate logs

http://stackoverflow.com/questions/31206060/sinatra-with-puma-gives-twice-the-output-in-the-terminal

Is this something that sinatra should be concerned with?

**Comment by zzak** [comment]
I believe this is an issue with puma, that has been reported elsewhere.

But I'm not sure where I remember reading about it. /cc @evan

**Comment by zzak** [comment]
Oops wrong @evanphx

**Comment by burningTyger** [comment]
yes, this can be solved in puma. Add the `-q` param to puma to quiet its logging.
