### ISSUE TITLE
Name collision with Capistrano

### ISSUE THREAD

**Issue by synth** [sinatra/sinatra#1063]
I encountered a weird error during a capistrano deployment after installing a new gem: slackistrano.

Ultimately, I discovered that slackistrano was failing because it executed

    before 'deploy:updating',           'slack:deploy:updating'

which is Capistrano dsl. However, it ended up calling Sinatra code:

````shell
NoMethodError: undefined method `each_pair' for "slack:deploy:updating":String
/home/web/sites/site.com/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1602:in `compile!'
/home/web/sites/site.com/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1344:in `add_filter'
/home/web/sites/site.com/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1331:in `before'
/home/web/sites/site.com/shared/bundle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1989:in `block (2 levels) in delegate'
/home/web/sites/site.com/shared/bundle/ruby/2.2.0/gems/slackistrano-1.0.0/lib/slackistrano/tasks/slack.rake:121:in `<top (required)>'
````

Now, my app doesn't use Sinatra directly, but does use gems that use it in development(mailcatcher, for one). For me, the fix involved making sure those gems weren't in the production section of my Gemfile. However, this seems like a bigger issue to me. 

I've more thoroughly documented the issue here: http://stackoverflow.com/questions/34644649/sshkit-error-during-capistrano-deployment-of-rails-app/34644650#34644650

**Comment by zzak** [comment]
This seems like it's a third-party issue, as commented on the StackOverflow ticket.
