### ISSUE TITLE
alternative HTTP verbs

### ISSUE THREAD

**Issue by zotherstupidguy** [sinatra/sinatra#1064]
Some firewalls and proxies may block any type of requests except GET and POST, and some web browser forms (HTML4) only use GET and POST.

For convenience, should Sinatra be able to catch alternative HTTP requests and route them similarly?

Example:  
[post, patch] '/resource' do
 #code here to handle post or patch
end

**Comment by rdalverny** [comment]
You may do this but you will mix the meaning of two verbs into one. That would be sad.

**Client-side:** POST your request, and *override* the method; in a HTML form, you may do this:

```html
<form method="POST" action="/resource">
  <input type="hidden" name="_method" value="PATCH">
  <input type="submit">
</form>
```

or when building your request, you may send an extra `X-HTTP-Method-Override` header, like this: 

```bash
curl -H 'X-HTTP-Method-Override: PATCH' -X POST http://server/resource
```

**Server-side:** make sure to `set :method_override, true` ([explained here](http://www.sinatrarb.com/configuration.html#methodoverride---enabledisable-the-post-method-hack), some default config values [differ whether you're in modular or classic style](http://www.sinatrarb.com/intro.html#Modular%20vs.%20Classic%20Style)).

Both example requests above will be handled by this piece:

```ruby
patch '/resource' do
  # ...
end
```

However, if you want to handle multiple routes/verbs together, have a look at [sinatra-multiroute](http://www.sinatrarb.com/contrib/multi_route.html).

**Comment by zotherstupidguy** [comment]
rdalverny thanks, I agree with all your points. 

I only thought of this after seeing that twitter https://dev.twitter.com/rest/public is only using GET & POST, so as not to omit out RESTfarians perhaps there is a non-offense way of implementing this in Sinatra . . .

Thanks Again :+1:

**Comment by rdalverny** [comment]
Good point. It makes sense in their case. Found this comment about the Twitter move: http://stackoverflow.com/questions/8841188/why-would-twitter-have-deprecated-the-use-of-delete-as-a-request-method-in-their#answer-11044996 .

You would write it then:

```ruby
require 'sinatra'
require 'sinatra/multi_route' 

route :delete, :post '/resource/:id/destroy' do 
  # ...
end
```

For the sake of simplicity, I would rather have a single call path to a given feature (so here, just document why and use a `POST /resource/:id/destroy`) to avoid future complications. Take what works best for you.
