### ISSUE TITLE
Add option to silently startup Sinatra server? 

### ISSUE THREAD

**Issue by alex-hall** [sinatra/sinatra#1077]
Being that we spin up several Sinatra instances on demand in our rspec integration tests, we would like the ability to silence Sinatra's colorful startup message.

Using `disable :logging` doesn't appear to work. Is the startup and shutdown message handled differently than usual logging?

![screen shot 2016-01-22 at 3 22 02 pm](https://cloud.githubusercontent.com/assets/5599279/12521964/eb3526f4-c11b-11e5-9bb4-63d662404020.png)

Pairs:
@alex-hall
@davwards

**Comment by kgrz** [comment]
Yes, we don't check for the `disable: :logging` setting before printing those messages out to `STDERR`: https://github.com/sinatra/sinatra/blob/master/lib/sinatra/base.rb#L1503

**Comment by zzak** [comment]
@alex-hall Just curious, how are you spinning up the instances?

**Comment by jkowens** [comment]
Closed by #1153.
