### ISSUE TITLE
Upgrading with Sinatra-1.4.7 is taking forever and a lot of CPU right now.

### ISSUE THREAD

**Issue by antdude** [sinatra/sinatra#1082]
Hello!

$ sudo gem update
Updating installed gems
Updating sinatra
Fetching: sinatra-1.4.7.gem (100%)
Successfully installed sinatra-1.4.7
Parsing documentation for sinatra-1.4.7
Installing ri documentation for sinatra-1.4.7
Installing darkfish documentation for sinatra-1.4.7
Done installing documentation for sinatra after 567 seconds
Gems updated: sinatra

$ top
top - 08:46:27 up 23:17,  4 users,  load average: 1.28, 1.40, 1.32
Tasks: 191 total,   2 running, 189 sleeping,   0 stopped,   0 zombie
%Cpu(s): 26.4 us,  0.8 sy,  0.0 ni, 72.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   2057956 total,  1912936 used,   145020 free,   155664 buffers
KiB Swap:  3905532 total,    27280 used,  3878252 free.   691128 cached Mem
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
11519 root      20   0  262568 192124   7404 R 100.0  9.3   8:58.40 gem
11284 root      20   0       0      0      0 S   5.7  0.0   0:05.90 kworker/3:2
   23 root      20   0       0      0      0 S   4.7  0.0  13:44.32 ksoftirqd/3
    7 root      20   0       0      0      0 S   2.3  0.0  23:01.61 rcu_sched
11285 root      20   0       0      0      0 S   2.3  0.0   0:05.84 kworker/0:1
...

Is this normal to take so long on an old quad Intel system with its SSD? :/

Thank you in advance. :)

**Comment by canton7** [comment]
That's entirely between you and RubyGems

**Comment by zzak** [comment]
Yes, this would have nothing to do with Sinatra -- but maybe something you could report to RubyGems or RDoc?

**Comment by ctrlcctrlv** [comment]
Same story here...

Other gems install fine, so I don't understand how you can blame it entirely on RubyGems or RDoc. Perhaps some feature of RDoc is because used that takes forever to install, I don't know. This isn't a good way to get new users though.

```
master# gem install sinatra
Fetching: tilt-2.0.2.gem (100%)
Successfully installed tilt-2.0.2
Fetching: rack-1.6.4.gem (100%)
Successfully installed rack-1.6.4
Fetching: rack-protection-1.5.3.gem (100%)
Successfully installed rack-protection-1.5.3
Fetching: sinatra-1.4.7.gem (100%)
Successfully installed sinatra-1.4.7
Parsing documentation for tilt-2.0.2
Installing ri documentation for tilt-2.0.2
Parsing documentation for rack-1.6.4
Installing ri documentation for rack-1.6.4
Parsing documentation for rack-protection-1.5.3
Installing ri documentation for rack-protection-1.5.3
Parsing documentation for sinatra-1.4.7
Installing ri documentation for sinatra-1.4.7
Done installing documentation for tilt, rack, rack-protection, sinatra after 278 seconds
4 gems installed
```

**Comment by kgrz** [comment]
I tested this problem with versions 1.4.7, 1.4.6, 1.4.5, and 1.4.4 on following configurations:

Ruby versions: 2.2.0p0 and 2.1.6p336
Rubygems versions: 2.4.5 and 2.2.3 respectively

And I can see it takes atleast 300 seconds. I'm checking with other versions too and report back.

**Comment by lgustafson** [comment]
Yes, it hangs for a long time specifically on "Installing ri documentation for sinatra-1.4.7" on ruby 2.3.0 and rubygems 2.5.1 on linux.

**Comment by canton7** [comment]
Yes, ri and rdoc can take a long time. It's not something that changing any code in this repository will fix. Try passing `--no-ri` and `--no-rdoc`

**Comment by lgustafson** [comment]
Agreed, ultimately the problem is not Sinatra's, however, it may be possible to determine if there is something in particular in one of the translations, for instance, that is causing it to take so long.

**Comment by RailsDuck** [comment]
The same thing is happening here, but I know how to solve it. First of all, you either tried these codes:
`gem install padrino`
`sudo gem install padrino`

Now, for whatever you tried, type this code in instead and it will fix all of your problems:
`gem install padrino --no-ri --no-rdoc`
`sudo gem install padrino --no-ri --no-rdoc`

This will make your normal, 15 minute cycle drop to 30 seconds. I feel like I have wasted a ton of time, and I hope this doesn't happen to you too!

**Comment by antdude** [comment]
RailsDuck: Interesting. Well, with ri (what is it?) and rdoc (documents I assume?) should be fixed.

**Comment by RailsDuck** [comment]
As long as it worked, you should be good. 👍 or 👎 ?

**Comment by zzak** [comment]
This is an RDoc issue, so I'm locking this ticket.
