### ISSUE TITLE
Sinatra 2 is no longer able to display custom show_exception

### ISSUE THREAD

**Issue by ujifgc** [sinatra/sinatra#1084]
According to https://github.com/rack/rack/pull/836 (discussion) and https://github.com/rack/rack/pull/922 (actual PR) Rack 2 is now using pre-compiled constant TEMPLATE  to render it's show_exception while Sinatra still expects Rack to load it from `@template` variable.

The corresponding test is shut up by this commit: fad3619e96c1ceea98b1c394e32bf11a43e1e360

If this is official stance of Sinatra 2 to no longer provide custom exception HTML, then file https://github.com/sinatra/sinatra/blob/master/lib/sinatra/show_exceptions.rb is no longer needed.

**Comment by zzak** [comment]
@ujifgc I'm not sure our stance, can you give an example?

**Comment by ujifgc** [comment]
```
require 'sinatra'

enable :show_exceptions

get '/hi' do
  raise 'exception'
end
```

On Sinatra 1 and Rack 1 this code shows Sinatra exception page.
On Sinatra 2 alpha and Rack 2 alpha this code shows Rack exception page.

**Comment by zzak** [comment]
:( can confirm
