### ISSUE TITLE
Grabbing file from request body when not using form data

### ISSUE THREAD

**Issue by JoeeGrigg** [sinatra/sinatra#1088]
Does anyone know how I can grab a file from the request object body?

I am writing an api and I can only seem to grab the uploaded file when I use form data. I am wanting to just send a file in the request body.

I have googled for hours and cannot seem to find anything documented on this...

Any help would be appreciated...

Thanks,
Joe

**Comment by canton7** [comment]
http://www.sinatrarb.com/intro.html#Accessing%20the%20Request%20Object ?

**Comment by JoeeGrigg** [comment]
Yeah I have seen that and ```request.body.read``` works fine for when I am just passing text but when I pass a file does not. Like when I use form data and I get a file object, I want the same when passing a file as the body

**Comment by canton7** [comment]
Define "does not work fine". It should return the raw request body. What exactly did you try, what results did you get, and how do they differ from what you were expecting?

**Comment by JoeeGrigg** [comment]
When outputting my request using

```puts request.body.inspect```

I get this output

```#<Rack::Lint::InputWrapper:0x007ff584db4dc8 @input=#<Tempfile:/var/folders/74/0pzpvk3j7v54xst2pbwn4sdcwh2vyv/T/thin-body20160201-5785-10dqa88>>```

All I want to be able to do at that point is save the the file but I cannot figure out how.

No doubt I am being really silly but just cannot figure this out...

**Comment by canton7** [comment]
What exactly do you see if you run `request.body.read`, as you said you did?

**Comment by JoeeGrigg** [comment]
![screen shot 2016-02-01 at 15 04 03](https://cloud.githubusercontent.com/assets/8267620/12720931/14ca86fe-c8f5-11e5-8102-62efb62033c2.png)

That fills my terminal...

**Comment by canton7** [comment]
Right, so you tried to print a binary file to the terminal. Looks as it should to me?

**Comment by JoeeGrigg** [comment]
I just did that in debugging though...

How do I save the request body / file that I am sending to a file locally?

**Comment by canton7** [comment]
There are many ways to write a stream to a file in ruby - nothing to do with Sinatra.

One way:
```ruby
File.open('output_file', 'wb') do |output_stream|
  IO.copy_stream(request.body, output_stream)
end
```

[Many more here](https://www.google.co.uk/search?q=ruby+write+stream+to+file).

**Comment by JoeeGrigg** [comment]
Okay maybe it is nothing to do with sinatra and writing to a file like that does work. However when I pass a file as form data I get a file object that contains file name, file type, temp file etc. When I do it like you just said I do not...

Is there a simple way to do that? And get the original file uploaded name etc...

**Comment by canton7** [comment]
Right, so you're no longer just putting the file in the request body: you're also including the name, etc. So we've changed the original question.

The easiest way to include multiple bits of data like this in a request is to send it as multipart form data: one part contains the filename, other the file itself, etc. This is also well supported within Sinatrea: I think you know how to do this, since you said

> I can only seem to grab the uploaded file when I use form data

You could also use an alternative scheme: maybe send the request as JSON and base64-encode the file? If you did this, you'd feed `request.bodyread` into `JSON.parse`, and inspect the parsed json. Things start getting a bit ugly and potentially expensive at that point though.

**Comment by JoeeGrigg** [comment]
Okay, thank you for your help.

Sorry if it was a novice question but never done much with files.

Thanks again,
Joe

**Comment by canton7** [comment]
:smile:

**Comment by md-work** [comment]
> Yeah I have seen that and `request.body.read` works fine for when I am just passing text but when I pass a file does not. Like when I use form data and I get a file object, I want the same when passing a file as the body

Looks like in this scenario Sinatra just doesn't work if `Content-Type: application/octet-stream` is not set.  

I set client side. Example: `wget --header='Content-Type: application/octet-stream' ...`
