### ISSUE TITLE
Installing Gem shows `unable to convert "\x89" from ASCII-8BIT to UTF-8`

### ISSUE THREAD

**Issue by paulmenzel** [sinatra/sinatra#1089]
Using Debian GNU/Linux 8 (jessie), and RVM doing `gem install sinatra` shows conversion errors.

```
$ gem install sinatra
Fetching: rack-1.6.4.gem (100%)
Successfully installed rack-1.6.4
Fetching: rack-protection-1.5.3.gem (100%)
Successfully installed rack-protection-1.5.3
Fetching: sinatra-1.4.7.gem (100%)
Successfully installed sinatra-1.4.7
Parsing documentation for rack-1.6.4
Installing ri documentation for rack-1.6.4
Parsing documentation for rack-protection-1.5.3
Installing ri documentation for rack-protection-1.5.3
Parsing documentation for sinatra-1.4.7
unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/sinatra/images/404.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/sinatra/images/500.png, skipping
Installing ri documentation for sinatra-1.4.7
```

**Comment by kgrz** [comment]
Which ruby was installed on the machine?

**Comment by paulmenzel** [comment]
Ruby 2.0.0p645 is used.

```
$ ruby --version
ruby 2.0.0p645 (2015-04-13 revision 50299) [i686-linux]
```

**Comment by anbiniyar** [comment]
I tried installing Sinatra on a few different versions on Ruby. RVM on Mac OSX El Capitan

Ruby 2.0.0 -> `unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/sinatra/images/404.png, skipping`
Ruby 2.1.8 -> Success

Seems like this is an issue with `rdoc` gem. By default ruby 2.0.0 install `rdoc` 4.0.0. On ruby 2.1.0, `rdoc` 4.1.0 is installed.

A simple `gem update rdoc` makes this issue go away.

Please refer to this [StackOverflow](http://stackoverflow.com/questions/18235293/ruby-on-rails-unable-to-convert-x89-from-ascii-8bit-to-utf-8-for-xxx-xxxx-x)

With this, we can conclude that this is not a Sinatra bug. 

Hope this helps

**Comment by kgrz** [comment]
Closing this issue since this is not related to Sinatra per se, as explained above.
