### ISSUE TITLE
Detecting connection closed. 

### ISSUE THREAD

**Issue by adamgamble** [sinatra/sinatra#1093]
So I have a bit of a unique case. I'm using sinatra as a proxy for s3 to save on bandwidth charges. Sinatra is sitting on a host that effectively has free bandwidth and when a user requests a file from our static domain, nginx checks if the file exists locally, if not it hands off to sinatra to grab it from s3 and save it locally for future requests.

So this almost works perfectly. But sometimes assets get saved to disk half done. I'm thinking this happens when a user requests a file and then closes the connection mid stream. Here is my code.
Is there a way to ensure that I continue downloading the file even if the user cancels? Or detect that the connect died somehow?

I'm using puma for my server behind nginx if that matters.

Here is the relevant code. We open a remote file stream from s3, open a local file stream, and we stream from s3 to the local file and to the sinatra stream.
```
stream do |out|
  File.open(local_file, "wb") do |file|
    remote_file.read do |chunk|
      file.write chunk
      out.write chunk
    end
  end
end
```

**Comment by kgrz** [comment]
@adamgamble There's a method under the `Stream` class that provides rudimentary connection detection. Can you see if the `out.closed?` method suits your usecase?

**Comment by canton7** [comment]
My guess would be that `out.write` is throwing an exception after the output stream has been closed - can you confirm whether this is the case? If so, the obvious solution is to either check whether the stream has been closed before trying to write to it (but keep writing to the local file), as @kgrz suggested, or to catch the exception writing to `out` and carry on.

**Comment by zzak** [comment]
@canton7 is correct, and offered some possible solutions for this.

The problem is the web server your using doesn't provide a callback when the connection is closed, so you have to handle the exception yourself.

I've added this kind of tip to the documentation for streaming responses, hope that helps resolve any confusion in the future!
