### ISSUE TITLE
Capistrano crashes once Sinatra is required

### ISSUE THREAD

**Issue by roolo** [sinatra/sinatra#1094]
When I try to deploy with Capistrano and I have my Sinatra app required, it is not working. I was testing multiple Sinatra versions and Sintra is causing problems of this manner since at least 1.3.2. You don't even have to define any routes or create Sinatra app class. Requiring Sinatra is absolutely enough.

Error:
~~~
cap aborted!
TypeError: no implicit conversion of nil into Hash
/Users/mailo/.rvm/gems/ruby-2.3.0@deployr/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:73:in `merge'
/Users/mailo/.rvm/gems/ruby-2.3.0@deployr/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:73:in `with'
/Users/mailo/.rvm/gems/ruby-2.3.0@deployr/gems/capistrano-3.4.0/lib/capistrano/tasks/git.rake:28:in `block (3 levels) in <top (required)>'
/Users/mailo/.rvm/gems/ruby-2.3.0@deployr/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:16:in `instance_exec'
/Users/mailo/.rvm/gems/ruby-2.3.0@deployr/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:16:in `run'
/Users/mailo/.rvm/gems/ruby-2.3.0@deployr/gems/sshkit-1.8.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
~~~
The error starts with trying to `fetch(:git_environmental_variables)`

Gemfile:
~~~gemfile
source 'https://rubygems.org'

gem 'sinatra', '~> 1.4.7'
gem 'capistrano', '~> 3.4.0'
gem 'capistrano-rvm', '~> 0.1.2'
gem 'capistrano-bundler', '~> 1.1.4'
gem 'rake', '~> 10.5.0'
gem 'unicorn', '~> 5.0.1'
~~~

If somebody thinks this is not problem of Sinatra team, then please discuss it with Capistrano people before closing this issue.

cc: @mattbrictson

**Comment by mattbrictson** [comment]
Hi! Generally speaking, Capistrano does not play nicely with other libraries/apps that are loaded at the same time. Capistrano was designed to run as a command-line tool *outside* your application, not loaded *with* your application.

You are seeing the side effect of both Sinatra and Capistrano defining a DSL method called `set`. I don't know much about Sinatra, but `set` is fundamental to how Capistrano works, so when Sinatra redefines it, of course everything breaks.

So the short answer is: you can't require both libraries at the same time.

Why are you trying to load a Sinatra app inside of a Capistrano deployment script?

**Comment by roolo** [comment]
RE https://github.com/sinatra/sinatra/issues/1094#issuecomment-181134318:

I wanted to have some data defined inside the app and share it with the deploy scripts :/
