### ISSUE TITLE
How to auto-select a port?

### ISSUE THREAD

**Issue by stugol** [sinatra/sinatra#1103]
I'd like to have Sinatra choose a free port to bind to, without having to specify the port myself.

**Comment by kgrz** [comment]
@stugol How do you imagine it would work? User gets to specify the port range?

**Comment by stugol** [comment]
@kgrz Possibly. Or just "anything goes", if the user doesn't care. In which case, it should probably avoid ports with specific documented functions.

**Comment by kgrz** [comment]
The port binding is handled by the underlying handler (WEBrick/Puma et al.), and Sinatra simply provides a small helper for forwarding the port to the underlying handler. It would be a complication on the core API if the logic for checking free ports (considering the cross-platform nuances between *nix, windows etc) were to be included in the library. That said, this would be a pretty cool extension :)

Closing this issue for this reason. But please feel free to re-open if you think I'm missing something.
