### ISSUE TITLE
Disable redirect on error

### ISSUE THREAD

**Issue by gonace** [sinatra/sinatra#1108]
Hi
I'm trying to figure out how to disable the redirect when an error is thrown, when an error is thrown the browser redirects me to /error, I'm trying to handle exceptions on an ajax request. I use sinatra-partial to render a partial and if an error occurs I wan't to return a json string.

Everything works fine, but the problem is that I'm beeing redirected to /error even though I just return a json string in the rescure block.

**Comment by kytrinyx** [comment]
> when an error is thrown the browser redirects me to /error

Is this behavior that you have defined explicitly somewhere, and that you're trying to override for a particular endpoint?

**Comment by gonace** [comment]
I've looked deeper intro the matter today, and you're correct there where a gem installed that was the reason for casting the redirect.

So this issue was not port of Sinatra but another ruby gem.
