### ISSUE TITLE
Sinatra Gem Conflict

### ISSUE THREAD

**Issue by kylestengline** [sinatra/sinatra#1117]
I have a sinatra app with this in the gemfile 
 gem "rake"
gem "pg"
gem "sinatra" tried this uncommented then bundled //, :github => 'sinatra/sinatra', :branch => "master"
//gem "rack", "~> 1.5" commented this out then bundled, uncommented, then bundled again.
gem "sinatra-contrib"
gem "pry"
gem "rspec"
gem “capybara”

I’m getting this error 
``` Unable to activate sinatra-1.4.7, because rack-2.0.0.rc1 conflicts with rack (~> 1.5) (Gem::ConflictError) ```
 when I try to 
``` rackup -p 3000 ``` or ``` rackup ``` 
I tried ``` bundle update rack ``` and  ``` bundle update ``` tried to use the master branch in my gemfile for sinatra, but still getting this error. 
For some reason ``` bundle exec rackup ``` is the only way to load the server now. 
Anyone have any ideas or get this error before?

**Comment by zzak** [comment]
Sinatra release 1.4.7 gem is not compatible with current master branch on github, this is because they target 2 different major versions of Rack.

So if you already installed Sinatra 1.4.7 (which depends on Rack ~> 1.5) in your Gemfile.lock, then trying to install master will fail.

You need to either remove the rack constraint, or change it, in order to use sinatra from master; and _then_ update your Gemfile.lock.

Does that make sense?

**Comment by dreamingblackcat** [comment]
I encountered the same error too.  Here is my Gemfile

```ruby
source "https://rubygems.org"

gem 'bson_ext'
gem 'grape'
gem 'grape-entity'
gem 'mongo'
gem 'rake'
gem 'sinatra'

group :development do
  gem 'shotgun'
end

group :test do
  gem 'rack-test'
  gem 'rspec'
end
```
I tried downgrading sinatra gem to '1.4.6' in the Gemfile but strangely I got 
`Gem::ConflictError: Unable to activate sinatra-1.4.7, because rack-2.0.0.rc1 conflicts with rack (~> 1.5)` again.

**Comment by kylestengline** [comment]
Hi zzak,

Thank you so much for getting back to me. 
That makes sense. However, how do I remove that constraint or change it? 
I tried to ``` bundle update rack ``` as well as setting the rack version in my gemfile, but when I run ``` bundle ``` I get this error... 

You have requested:
  rack ~> 2.0.0

The bundle currently has rack locked at 1.6.4.
Try running `bundle update rack`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`

I tried searching around, but can't find a way to remove the constraint or change it. Would you have any suggestions?

**Comment by zzak** [comment]
If you want to use the old version of Sinatra, why not just revert the
change to your Gemfile and Gemfile.lock (assuming you committed both)?

Did you try "bundle update" without specifying rack?

**Comment by zzak** [comment]
Please try `bundle update` after changing your Gemfile to use master:

`gem 'sinatra', github: 'sinatra/sinatra'`


Thanks!

**Comment by mfrederickson** [comment]
Just in case anyone had a conflict like I did.... I was running capybara from within my sinatra application for checking the health of another web application and was getting argument problems and something about rack versions.  Once I removed the `include Capybara::DSL` from my class, everything worked fine (I wasn't using the shortcuts that provided).

```
App 25961 stderr: 2016-07-21 21:55:29 - ArgumentError - wrong number of arguments (given 1, expected 0):
App 25961 stderr: 	/usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:152:in `html'
App 25961 stderr: 	/usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
App 25961 stderr: 	/usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1072:in `invoke'
App 25961 stderr: 	/usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
App 25961 stderr: 	/usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
```

**Comment by fwolfst** [comment]
I have a similar problem with a gem depending on `active_records_migrations`, for which I'd like to use the 5.x line.

When will a `sinatra`-version with `rack` 2.0 support be released (roughly)?

**Comment by Jorybraun** [comment]
Also having this conflict

**Comment by Topher33** [comment]
@zzak seem like you are aware of the same conflict, but if you want to use sinatra master because of rails 5 conflict... seems like there is no way right now to use sinatra-contrib because of its dependancy on sinatra ~>1.4.7.... 

Anyone else have this issue, or solve?

**Comment by cls3** [comment]
same problem here

**Comment by zzak** [comment]
@cls3 Can you try using `gem 'sinatra', '2.0.0.rc2'`?

**Comment by cls3** [comment]
That did the trick!
