### ISSUE TITLE
StatsD reporting of specific sinatra routes

### ISSUE THREAD

**Issue by erez-rabih** [sinatra/sinatra#1119]
Hi,

I would like to report metrics for specific sinatra routes to statsd and then graphite.
For the route GET /users/:uid I would like to report to a metric name `request.get.users.uid`
The uid in the metric name cannot be the actual variable value since it is not a good practice to insert a variable into a graphite metric name.

For each route I would like to count response codes and execution time.

I tried to create a middleware to do that and saw that sinatra inserts a `sinatra.route` into the Rack env hash which I can use to get the request method and pattern a request was processed by.

``` ruby
class StatsdReporting

  def initialize(app)
    @app = app
  end

  def call(env)
    start_time = Time.now
    status, headers, body  = @app.call(env)
    time_took = (1000 * (Time.now - start_time)).round
    statsd_rport env["sinatra.route"], time_took
    [status, headers, body]
  end
end
```

The problem is that if I have a halt somewhere in a before filter that variable (sinatra.route) is not set in the Rack env hash so I'm missing the details I need in order to create the metric name.

Any good solution to report statsd specific route metrics by route patterns rather than the actual request uri?

**Comment by noahc** [comment]
Can't you order your before filters in such a way that the first thing it does is write out the data and then hits the halt?

**Comment by erez-rabih** [comment]
@noahc I don't want to use before filters because then I will have to explicitly report on every route I have.
I want to use middleware so that every route I have will be automatically reported without any changes to the application code itself.

**Comment by kgrz** [comment]
Hmm, not sure if there's a way as of now. Currently the routes are processed during the compilation phase and we don't store the actual route definition anywhere, just the compiled route. And the path info is available on the request context, which won't be available when the route is short circuited using `halt`.

We could probably store the actual unprocessed route definition in the compiled route array. Currently it looks like this:

```ruby
{
"GET"=>
  [[/\A\/([^\/?#]+)\z/,
    ["a"],
    [],
    #<Proc:0x007f98ac235ba8>]]
}
```

May be we could add one more item in that array:

```ruby
=> {"GET"=>
  [[/\A\/([^\/?#]+)\z/,
    ["a"],
    [],
    #<Proc:0x007f98ac235ba8>,
    "/:a"]]
}
```

@sinatra/team-sinatra what do you think?

**Comment by zzak** [comment]
@kgrz Sounds good to me

**Comment by dentarg** [comment]
Seeing no patch materialized in ~7 years I'll close this, but it sounds useful if anyone wants to contribute it.
