### ISSUE TITLE
Unable to overwrite configuration setting value with new hash value

### ISSUE THREAD

**Issue by aurcioli-handy** [sinatra/sinatra#1128]
``` ruby
configure do
    set :test, {}
end
```

irb(main):001:0> `require './app'`

=> `true`

irb(main):002:0> `MySinatraApp.test`

=> `{}`

irb(main):003:0> `MySinatraApp.test = {foo: "bar", bar: "foo"}`

=> `{:foo=>"bar", :bar=>"foo"}`

irb(main):004:0> `MySinatraApp.test`

=> `{:foo=>"bar", :bar=>"foo"}`

irb(main):005:0> `MySinatraApp.test = {foo: "bar"}`

=> `{:foo=>"bar"}`
#### => `{:foo=>"bar", :bar=>"foo"}`

irb(main):007:0> `MySinatraApp.test = nil`

=> `nil`

irb(main):008:0> `MySinatraApp.test = {foo: "bar"}`

=> `{:foo=>"bar"}`

irb(main):009:0> `MySinatraApp.test`

=> `{:foo=>"bar"}`

irb(main):010:0> 

As you can see, if you try to replace the configuration setting with a new hash, it won't take unless you set to `nil` first. Not sure if this is a sinatra or ruby thing, as I am somewhat a newb to both.

**Comment by dentarg** [comment]
Not sure I follow what's going on here, but this program

```ruby
arm64 $ cat config.ru
require 'sinatra/base'

class App < Sinatra::Base
  configure do
    # set :test, {}
    set :foo, {}
    set :foo, { foo: :bar }
    set :foo, { foo: :baz }
  end

  get '/' do
    body "OK foo=#{settings.foo.inspect}"
  end
end

run App
```

Responds like this

```
$ curl localhost:9292
OK foo={:foo=>:baz}
```

So I think it works.

Feel free to provide a more complete repro if you disagree.
