### ISSUE TITLE
Sinatra returns two different 404 responses for same exact request, seconds apart from eachother.

### ISSUE THREAD

**Issue by aurcioli-handy** [sinatra/sinatra#1130]
`curl -i -X GET "http://localhost:9393/data/fo" -H "Content-Type: application/json" -H "Authorization: Bearer redacted"`

HTTP/1.1 404 Not Found
Content-Type: application/json
Content-Length: 59
X-Content-Type-Options: nosniff
Connection: keep-alive
Server: thin

{"errors":[{"title":"Resource not found.","status":"404"}]}%

`curl -i -X GET "http://localhost:9393/data/fo" -H "Content-Type: application/json" -H "Authorization: Bearer redacted"`

HTTP/1.1 404 Not Found
Content-Type: application/json
X-Content-Type-Options: nosniff
Content-Length: 3
Connection: keep-alive
Server: thin

404%

Whenever I randomly get the correct response, you can see the request takes longer:
127.0.0.1 - - [28/Jun/2016:14:21:49 -0400] "GET /data/fo HTTP/1.1" 404 3 0.0463
127.0.0.1 - - [28/Jun/2016:14:21:51 -0400] "GET /data/fo HTTP/1.1" 404 3 0.0630
127.0.0.1 - - [28/Jun/2016:14:21:53 -0400] "GET /data/fo HTTP/1.1" 404 3 0.0459
**127.0.0.1 - - [28/Jun/2016:14:21:55 -0400] "GET /data/fo HTTP/1.1" 404 59 0.0478**
127.0.0.1 - - [28/Jun/2016:14:21:57 -0400] "GET /data/fo HTTP/1.1" 404 3 0.0496
127.0.0.1 - - [28/Jun/2016:14:21:58 -0400] "GET /data/fo HTTP/1.1" 404 3 0.0462
127.0.0.1 - - [28/Jun/2016:14:22:00 -0400] "GET /data/fo HTTP/1.1" 404 3 0.0485
127.0.0.1 - - [28/Jun/2016:14:22:02 -0400] "GET /data/fo HTTP/1.1" 404 3 0.0510

EDIT: rspec tests always receive the correct error response (first one)..

**Comment by aurcioli-handy** [comment]
```ruby
configure do
   disable :show_exceptions
end
```

Seems to fix it.. Still this is very unexpected behavior different error handlers fighting eachother?

**Comment by aurcioli-handy** [comment]
Looks like this is a problem with `shotgun` and not Sinatra.. as using rackup seems to fix that problem

**Comment by zzak** [comment]
@aurcioli-handy Thank you for following up with your investigation for anyone else who runs into this! <3
