### ISSUE TITLE
Tool gem name conflict

### ISSUE THREAD

**Issue by mikeastock** [sinatra/sinatra#1134]
The mustermann dependency relies on another [gem](https://github.com/rkh/tool) named "tool" which uses the namespace Tool. I work on an application that also has a domain object named tool.

Has this been an issue for anyone else? If so, would you guys be open to us renaming Tool to something more specific to Sinatra?

**Comment by zzak** [comment]
I have no idea who is using the gem, or the impact of changing the name.

So it's probably best to release a new gem, under a different namespace, and update the dependency on mustermann.

We should probably ask @rkh for his permission first, though.

I think this is our best option.

**Comment by mikeastock** [comment]
That sounds like a great plan. We can do the work once @rkh signs off!

**Comment by rkh** [comment]
👍🏾 we could also consider importing tool into mustermann and just remove the dependency. I once started a rewrite of Sinatra that was also using tool, but that didn't go anywhere.

**Comment by namusyaka** [comment]
I opened [a issue](https://github.com/sinatra/mustermann/issues/48), maybe I'll be able to try to import tool and remove the dependency.

**Comment by zzak** [comment]
:+1: to importing into mustermann under a different namespace, one less gem to maintain!

**Comment by mikeastock** [comment]
I went ahead and opened a PR that moves EqualityMap into the gem. https://github.com/sinatra/mustermann/pull/49

**Comment by zzak** [comment]
Is `EqualityMap` the only thing we need?

**Comment by mikeastock** [comment]
I believe so:

```
$ ag "Tool"                                                                                                                                                                                                                          [21:25:20]
mustermann/lib/mustermann/ast/pattern.rb
89:        @ast_cache ||= Tool::EqualityMap.new

mustermann/lib/mustermann/pattern.rb
57:      @map ||= Tool::EqualityMap.new

mustermann/README.md
40:### Additional Tooling
```

**Comment by zzak** [comment]
@mikeastock Thank you!
