### ISSUE TITLE
Sinatra::Reload load other files (besides .rb), such as .yml

### ISSUE THREAD

**Issue by zzak** [sinatra/sinatra#1139]
This ticket is copied from sinatra/sinatra-contrib#179

**Comment by georgenica** [comment]
@zzak as per sinatra/sinatra-contrib#179, this has been taken care since v2, with the introduction of `after_reload`. Looks like this issue could be closed.

If I'm mistaken, would you please indicate if there's anything else that needs done?

**Comment by jkowens** [comment]
Yes, it looks like PR https://github.com/sinatra/sinatra/pull/1150 added that feature. Thanks for updating this issue 👍
