### ISSUE TITLE
run! not defined with subclass

### ISSUE THREAD

**Issue by otheus** [sinatra/sinatra#1146]
Ruby 1.9.2
Sinatra 1.4.7

```
$ irb
require 'sinatra/base'
class S < Sinatra::Base
set :server, :thin # just in case
end
my_app=S.new
irb> my_app.run!
NoMethodError: undefined method `run!' for #<Sinatra::Wrapper:0x00000001966b20>

irb> my_app.methods
=> [:settings, :helpers, :call, :inspect, :nil?, :===, :=~, :!~, :eql?, :hash, :<=>, :class, :singleton_class, :clone, :dup, :initialize_dup, :initialize_clone, :taint, :tainted?, :untaint, :untrust, :untrusted?, :trust, :freeze, :frozen?, :to_s, :methods, :singleton_methods, :protected_methods, :private_methods, :public_methods, :instance_variables, :instance_variable_get, :instance_variable_set, :instance_variable_defined?, :instance_of?, :kind_of?, :is_a?, :tap, :send, :public_send, :respond_to?, :respond_to_missing?, :extend, :display, :method, :public_method, :define_singleton_method, :object_id, :to_enum, :enum_for, :==, :equal?, :!, :!=, :instance_eval, :instance_exec, :__send__, :__id__]

```

This conflicts with at least 1 example on main doc page.

**Comment by kgrz** [comment]
Is that a typo in your example? `class S` and `F.new.run!`?

**Comment by otheus** [comment]
Yes, typo. I was copying the example from the full names I gave it.

**Comment by otheus** [comment]
It looks like `#run!` is a _class_ method. I'm not sure if that's a bug in the implementation or the documentation.

**Comment by kgrz** [comment]
Yes, you are right, `run!` is a class method.

Can you point me to the documentation? If you're referring to this: http://www.sinatrarb.com/intro.html#Dynamic%20Application%20Creation, then note that the class creation is a little different. That example uses a classic style constructor (note the `Sinatra.new` call vs `Sinatra::Base` in the example you've posted)

**Comment by otheus** [comment]
That is precisely the documentation I was looking at. 

Yes, I see now that it's a little different, but in the case...

```
class S < Sinatra
end
```
doesn't work because Sinatra is a module, not a class. How does ```Sinatra.new``` even work in that case?!?

I suppose then that there's a trick implemented to make Sinatra act like a class. Maybe somewhere in the documentation it should be mentioned that Sinatra is actually a singleton. Doesn't that present some problems in Ruby ... multiple derived classes from a singleton class?

**Comment by kgrz** [comment]
The relevant portion of code that defines this behaviour is [here](https://github.com/sinatra/sinatra/blob/5e9e23621c1f6abbd793b46452cb11ae8ca1277e/lib/sinatra/base.rb#L1500-L1503).

> I suppose then that there's a trick implemented to make Sinatra act like a class. 

Yep!  You can define a `new` method on a module! Many DSL-style libraries do this (Cucumber is one example I can recall that had that kind of code long back).

I'm not too sure I understand about the singleton part. In general, two styles are followed when writing Sinatra apps: classic and modular. Classic is where you don't inherit from anything and Modular is where you inherit from `Sinatra::Base` (not `Sinatra::Application` which is a wrapper around Base that lets you write the classic style applications).

If you think the documentation confuses this part out of people, we can modify that bit to make the intent clear and use a consistent style. Feel free to open a PR if you are comfortable with it.

**Comment by otheus** [comment]
> I'm not too sure I understand about the singleton part. 
Normally when you define a class, you expect to be able to instantiate it as an object. When you have examples showing that CLASS.new can be done, it's quite reasonable to expect that this class behaves like a classical class, ie, can be instantiated. But Sinatra is clearly an exception to that rule.  Sinatra::Base (and derived classes, such as Sinatra::Application) are "singletons" in that only one instance of a class can be made. Except that's not really the case, because the class isn't meant to be actually instantiated -- all the functionality is wrapped up in class methods.

I'm far from being an OO expert, so I can't tell you if this follows a classical pattern or not. However, it's certainly an unexpected pattern. 

What's PR?

**Comment by zzak** [comment]
`run!` is a class method, but you're calling it on an instance:

> my_app=S.new
> irb> my_app.run!

Let us know when you get it working! <3

**Comment by llamicron** [comment]
@zzak I know this issue is closed and all, but your solution was correct for me:

> run! is a class method, but you're calling it on an instance:
> 
> > my_app=S.new
> > irb> my_app.run!
> Let us know when you get it working! <3
