### ISSUE TITLE
Could not find gem 'rack-protection (~> 2.0)', which is required by gem 'sinatra', in any of the sources.

### ISSUE THREAD

**Issue by salmagomaa** [sinatra/sinatra#1149]
I was working with sinatra master since my upgrading to Rails 5, but today it seems there are some updates to the master, that throws the following error when I am trying to update the bundle.

The thrown error is:

Bundler could not find compatible versions for gem "rack-protection":
  In Gemfile:
    sinatra was resolved to 2.0.0.pre.alpha, which depends on
      rack-protection (~> 2.0)

Could not find gem 'rack-protection (~> 2.0)', which is required by gem
'sinatra', in any of the sources.

Any help please?

**Comment by tloszko** [comment]
Use github's version:

`gem "rack-protection", :github => "sinatra/rack-protection"`

**Comment by salmagomaa** [comment]
Thanks a million! It works for me.

**Comment by Rim-777** [comment]
For rails 6 helped to set the gem globally
`gem install  "rack-protection"`
