### ISSUE TITLE
Sinatra dependancy broken

### ISSUE THREAD

**Issue by kgathi2** [sinatra/sinatra#1152]
Bundled Sinatra a few days ago and it worked. But now not working
```ruby
# Gemfile
gem 'sinatra', require: false, github: 'sinatra'
```

```console
# Console error
Bundler could not find compatible versions for gem "rack-protection":
  In Gemfile:
    sinatra was resolved to 2.0.0.pre.alpha, which depends on
      rack-protection (~> 2.0)

Could not find gem 'rack-protection (~> 2.0)', which is required by gem 'sinatra', in any of the sources.
```

Had to require last stable commit
```
gem 'sinatra', require: false, github: 'sinatra', ref: 'e7ef8e234fd36e389ec7e23d562de488fde7abff'
```
Waiting for stable release. Can't use `gem sidekiq-web` for now due to an [Issue](https://github.com/mperham/sidekiq/issues/2839)

**Comment by kgathi2** [comment]
Had to require last stable commit
```
gem 'sinatra', require: false, github: 'sinatra', ref: 'e7ef8e234fd36e389ec7e23d562de488fde7abff'
```
Waiting for stable release. Can't use `gem sidekiq-web` for now due to an [Issue](https://github.com/mperham/sidekiq/issues/2839)

**Comment by b264** [comment]
https://github.com/sinatra/sinatra/issues/1149

**Comment by kgathi2** [comment]
Thanks

`gem "rack-protection", github: "sinatra/rack-protection"`
