### ISSUE TITLE
unable to find a version of 'sinatra' to activate (Gem::LoadError)

### ISSUE THREAD

**Issue by polyglot0027** [sinatra/sinatra#1162]
Hello everyone! I have a problem with using tux gem and sinatra on win8 platform. When i try to execute the tux gem there is appears the following error. The screenshot pinned. Bundle install command didn't solve an issue. Thank you in advance! :)
![error](https://cloud.githubusercontent.com/assets/18975138/17462768/32a7207e-5cc0-11e6-8a14-de2a49e2f9f0.gif)

**Comment by zzak** [comment]
This appears to be a problem with your environment, as you seem to have multiple versions of sinatra installed on your system -- however unable to activate it.

I would recommend to report this issue, with any steps to reproduce it, to the `tux` gem you are using.

**Comment by polyglot0027** [comment]
Yep, I've just clean up old versions of Sinatra and the problem has gone. Thanks! :)

**Comment by zzak** [comment]
@polyglot0027 Glad you figured it out! <3
