### ISSUE TITLE
still can't build sinatra master gem 

### ISSUE THREAD

**Issue by tigernassau** [sinatra/sinatra#1163]
wish a new pre release gem was available 

cloned sinatra master
rake sinatra.gemspec
rake install
trying to build => ERROR:  Could not find a valid gem 'rack-protection' (~> 2.0) in any repository

added to gemfile:  gem "rack-protection", :github => "sinatra/rack-protection"
we ran bundle install => complete
but then still get error for rack-protection 
running on fedora 24 ruby ruby 2.3.1p112 (2016-04-26 revision 54768)

any thoughts

**Comment by zzak** [comment]
@tigernassau In this case, you will first have to build and install the `rack-protection` gem from source.

Hang tight, a pre-release is coming soon!
