### ISSUE TITLE
Rack::Protection document AuthenticityToken

### ISSUE THREAD

**Issue by zzak** [sinatra/sinatra#1165]
From original ticket (sinatra/rack-protection#106):

> To accept a form i'd need to submit the authenticity_token param along with the form. This token is set in the session currently. Is there no way to get that in a meta tag so I can embed in page?

Also #1154

**Comment by tonytonyjan** [comment]
Any progress to this, I wonder.

I've made [a gist of minimal example and explanation](https://gist.github.com/tonytonyjan/8a551a9808295287a8c3c43a6ecdaf0e), willing to send a PR but don't know which file to commit, any idea?
