### ISSUE TITLE
Can't use sinatra 2.0 beta as rack-protection beta isn't loadable via bundler

### ISSUE THREAD

**Issue by rkh** [sinatra/sinatra#1174]
Due to `rack/protection/version` using `::Sinatra::VERSION` and `rack/protection` and 
`rack/protection` requiring it.

Potential action:

* Have `rack/protection` not load `rack/protection/version`.
* Have `rack/protection/version` not depend on Sinatra, maybe we could generate the file?

**Comment by rkh** [comment]
Workaround for anyone running into this with Sinatra:

``` ruby
require 'sinatra/version'
require 'sinatra/base' # or require 'sinatra'
```

Workaround for anyone running into this without using Sinatra:

``` ruby
module Sinatra
  VERSION = '2.0.0-beta1'
end

require 'rack/protection'
```

**Comment by zzak** [comment]
I cut beta2 to fix this:
https://github.com/sinatra/sinatra/releases/tag/v2.0.0.beta2
