### ISSUE TITLE
Symbolic Headers Pass During RSpec, But Fail in Rackup

### ISSUE THREAD

**Issue by jonmchan** [sinatra/sinatra#1177]
I set headers as a symbol:

`headers( { x-custom-header: 'test' })` and it passed when I asserted that the response header x-custom-header existed. However, when I ran it within rack, I received the following error:

`Rack::Lint::LintError: header key must be a string, was Symbol`

Is there a way that we can make the improper symbolic headers fail in test too?

**Comment by zzak** [comment]
@jonmchan How are you testing "that the response header existed"?

**Comment by jonmchan** [comment]
The tests are the following:

```
context 'when a proper authentication string is passed' do
      let(:header) { { 'HTTP_AUTHORIZATION' => "Basic authentication=\"#{valid_credentials}\""  } }

      it 'is expected not to return a 403 or 401' do
        api_call
        expect(last_response.status).to_not eql(403)
        expect(last_response.status).to_not eql(401)
      end
    end
```

The issue is that both ```let(:header) { { 'HTTP_AUTHORIZATION' => "Basic authentication=\"#{valid_credentials}\""  } }``` and ```let(:header) { { HTTP_AUTHORIZATION: "Basic authentication=\"#{valid_credentials}\""  } }``` both work during the test, but only the first works in a real rack environment.

**Comment by mwpastore** [comment]
This appears to be due to the fact that Rack::Response uses Rack::Utils::HeaderHash, but Rack::MockResponse does not.

**Comment by mwpastore** [comment]
This appears to be due to the fact that Rack::Lint is used in production, but Rack::Test does not wrap the application in a Rack::Lint by default. There is Rack::MockRequest option to do so, but it looks like you specify it per invocation. So you have a few options here:

1. Use string keys for the `params`, `env`, `response`, etc. (pseudo-)hashes and Rack::Test hooks like `:header` in your test cases. This is what most Rack::Test-writers do, I think.

2. When you define `app` in your test case(s), just wrap it in a Rack::Link:

    ```ruby
    def app
      Rack::Lint.new(MyApp.new)
    end
    ```

3. Pass `:lint=>true` in your calls to `get`, `post`, etc. in your test case(s). 

Hope this helps!

**Comment by jonmchan** [comment]
I certainly know to do what you prescribe in # 1 at this point, but it would be great if sinatra tests default to use Rack::Lint. I think it is bad when you have to go to the deployed environment to catch this bug when you should somehow have this caught in the testing stage. This type of inconsistent behavior invalidates the use of tests when it fails in production but succeeds in test.

**Comment by mwpastore** [comment]
You're welcome to submit an issue/PR to brynary/rack-test to have them make linting enabled by default, although I suspect their answer is going to be "it's easy enough to do so on an application-by-application basis." They might be willing to call it out more clearly in the documentation. Unfortunately, there's not much we can do about it in Sinatra. You might take a look at the Sinatra::TestHelpers module provided by sinatra-contrib, which does (2) above by default, although it doesn't appear to be very well-documented.
