### ISSUE TITLE
Add option to continue allowing anchors in regexp patterns

### ISSUE THREAD

**Issue by wjordan** [sinatra/sinatra#1178]
I have a Rack application that uses Sinatra for some routes and Rails for others, which I'm trying to upgrade in lockstep to Rack 2.x (Rails 4.x -> 5.x, Sinatra 1.x -> 2.x). Many existing Sinatra route patterns are written as Regexp with anchors. With Sinatra's new dependency on Mustermann, anchors are explicitly disallowed in its route patterns, which breaks my application. Rather than rewrite the behavior of my existing application, I'd like to see an option to continue allowing anchors in Sinatra 2.x regexp patterns. (It's fine if this is disabled by default, as long as there's a way to enable it.)

In the meantime, I've come up with this monkey-patch as a workaround:

``` ruby
class Sinatra::Base
  # Patch Sinatra 2.x to allow anchors in regexp patterns,
  # to match 1.x behavior.
  def self.compile(path)
    opts = path.is_a?(Regexp) ? {check_anchors: false} : {}
    Mustermann.new(path, opts)
  end
end
```

**Comment by mwpastore** [comment]
Agreed. I have an extension that registers routes, and I'd like some clear upgrade path or pattern for this issue so I don't have to pin the gemspec to either Sinatra < 2.0 or >= 2.0.

**Comment by zzak** [comment]
Hmm, if anyone can tell me why anchors are disabled by default I might consider changing the behaviour to match.

**Comment by mwpastore** [comment]
I've worked around this by including Mustermann in the gemspec and registering it if it's not Sinatra 2.0.

**Comment by wjordan** [comment]
@zzak According to the commit [`23c1548c`](https://github.com/sinatra/mustermann/commit/23c1548cd94b831ec6421d72b8508bcd22ef0733),

> Using anchors will break peeking and concatenation.

I don't know what either of these Mustermann features are (or if they're currently used by Sinatra).

**Comment by mwpastore** [comment]
I think the default behavior is fine (actually, I prefer it to having to anchor every regexp path), but I can see a case for exposing a hook for setting Mustermann options at the application level. Something like [this](https://github.com/mwpastore/sinatra/commit/02e3eb447f9e8315730519f8404a7b834e9bd5af)?

**Comment by zzak** [comment]
@mwpastore PR please :bow:

**Comment by mwpastore** [comment]
Will do! Was waiting to see if you're comfortable with the API. PR is forthcoming...

**Comment by mwpastore** [comment]
@wjordan How did you work around this error?

```
ArgumentError: unsupported option :check_anchors for Mustermann::Sinatra
    /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/mustermann-1.0.0.beta2/lib/mustermann/pattern.rb:54:in `new'
    /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/mustermann-1.0.0.beta2/lib/mustermann.rb:67:in `new'
    /Users/mwp/Code/sinatra/lib/sinatra/base.rb:1645:in `compile'
```

**Comment by wjordan** [comment]
@mwpastore I didn't encounter that error in my project, I'm still currently using the patch I posted above (see [commit](https://github.com/code-dot-org/code-dot-org/commit/f5abdb137051a69e0be702054cded766013fa2fa)) without problems. Are you getting that error with the above patch, or using some other code? (Specifically, the `check_anchors` option will only work with `Regexp`-type paths because `Mustermann::Regular` is the only class that supports this option.)

**Comment by zzak** [comment]
I think what @wjordan is right, it looks like you're getting a `Sinatra` pattern instance instead of `Regexp` type which doesn't support that option.

**Comment by mwpastore** [comment]
Thank you both, I modified my tests to pass in `:type => :regexp` as well.

The more I look at this, the more I feel like it should be configurable per route, as opposed to per application. This would mean treating a `:mustermann_opts` route option specially, kind of like `:host`. Thoughts, @zzak?

**Comment by zzak** [comment]
@mwpastore I'm not sure I understand, could you explain with a patch or tests?

**Comment by mwpastore** [comment]
I'm working on a patch. Here's an example of what it might look like in practice:

```ruby
get '/normal-route' do
  # ..
end

get '\A/special-route\z', :mustermann_opts=>{ :type=>:regexp, :check_anchors=>false } do
  # ..
end
```

**Comment by zzak** [comment]
Isn't this the same as the patch to `compile`?

**Comment by mwpastore** [comment]
No. The patch I shared earlier would enable the following:

```ruby
configure do
  set :mustermann_opts, { :type=>:regexp, :check_anchors=>false }
end

get '\A/route\z' do
  # ..
end
```

I.e. all routes take the application-wide Mustermann options.

**Comment by zzak** [comment]
Why not both? :)

**Comment by mwpastore** [comment]
Sure, why not! Take a gander at #1233.
