### ISSUE TITLE
Add lifecycle callbacks

### ISSUE THREAD

**Issue by tobymurray-nanometrics** [sinatra/sinatra#1184]
## Description

Looking at the (admittedly not super popular) questions on StackOverflow like [this](http://stackoverflow.com/q/2589356/4970406) and [this](http://stackoverflow.com/q/6557079/4970406), I think it'd be handy to have some usable lifecycle callbacks for Sinatra. In particular, a callback when Sinatra is completely set up and a callback when Sinatra has completely stopped.
## Use case

We use JRuby for a Rails application, but we also use Java code. The Ruby code calls out to a Java HTTP client, so when we're writing tests for that code we can't use any Ruby mocking libraries. Instead of an elaborate refactor whereby a mock Java HTTP client can be injected for testing, we use a number of tiny Sinatra servers that have very simple and predetermined responses to "mock" the third party servers. So far it has worked excellently, and allows us to keep our testing and production code very similar (mocks have bitten us by not failing in ways their production equivalents would).

To accomplish this, we've mashed together something like the linked answers above whereby we block until Sinatra has started. Unfortunately, there doesn't seem to be a similar solution for `stop!`, so rapidly starting and stopping Sinatra servers occasionally fails (client can't connect). My suspicion right now is that the previous Sinatra server has not fully stopped before the next one is attempting to start.

For us it'd be extremely useful to have an `on_start` and `on_quit` (with whatever names are appropriate for the lifecycle which would indicate Sinatra is completely up, running, and ready to go and completely stopped).

**Comment by zzak** [comment]
@tobymurray-nanometrics I am open to the idea. Could you submit a patch?

**Comment by tobymurray-nanometrics** [comment]
I could take a look at it, sure. No guarantees on timeliness...

If anyone is looking for the same functionality from the current Sinatra, we've added an extra layer on top of `Sinatra::Base` to give us the start the server, execute some code, then stop the server. It's a bit hacky, but it's worked very well for us - exclusively in a test environment. Here's the code:

```
require 'sinatra/base'

class TestSinatraBase < Sinatra::Base
  SERVER_STARTED_SUCCESSFULLY = true
  SERVER_FAILED_TO_START = false

  def self.start_and_block_until_running(opts)
    queue = Queue.new
    @@server_thread = Thread.new do
      begin
        run!(opts) do
          queue.push SERVER_STARTED_SUCCESSFULLY
        end
      ensure
        queue.push SERVER_FAILED_TO_START if queue.empty?
      end
    end
    successful = queue.pop # Blocks until the the app has started and the block provided to `run!` executes
    raise "Sinatra server failed to start, look at the logs for more information." unless successful
  end

  def self.execute_test(opts)
    start_and_block_until_running(opts)

    begin
      yield if block_given?
    ensure
      stop!
      @@server_thread.join(10) if @@server_thread&.alive?
    end
  end
end
```

**Comment by jevin** [comment]
Taking this! Will have something early next week.

**Comment by jevin** [comment]
The PR is ready for this. If anyone could have a look that would be wonderful!

**Comment by dentarg** [comment]
Resolved by https://github.com/sinatra/sinatra/pull/1913
