### ISSUE TITLE
bundle security warning in development

### ISSUE THREAD

**Issue by grempe** [sinatra/sinatra#1200]
When doing `bundle` in a freshly cloned copy of the sinatra repository directory results in the following security warning:

```
$ bundle
The git source `git://github.com/rack/rack.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/rack/rack.git
...
```

I believe this is being driven by the following line in the Gemfile:

https://github.com/grempe/sinatra/blob/master/Gemfile#L14

This change to show this warning was introduced way back in March 2015 to bundler:

https://github.com/bundler/bundler/issues/3448

**Comment by zzak** [comment]
To be honest, this seems like bundler should prefer https for the `github` option.. but that's none of my business.

Happy to accept a patch which changes it to enforce https to get rid of the warning.

**Comment by grempe** [comment]
@zzak I already fixed this in PR https://github.com/sinatra/sinatra/pull/1202 which is referenced above. The PR has still not been merged yet.

Here is the commit in that PR that fixes it:

https://github.com/sinatra/sinatra/pull/1202/commits/e35dca6b06bf60e4cedc487d3fb45af8252013d2

**Comment by romenigld** [comment]
thank's @grempe!!!
