### ISSUE TITLE
Modernize Rack::Protection::ContentSecurityPolicy with CSP Level 2 and 3 Directives

### ISSUE THREAD

**Issue by grempe** [sinatra/sinatra#1201]
The current ContentSecurityPolicy config is limited to a subset of the CSP level 2 directives.

It should support the configuration of all CSP Level 2 and Level 3 directives as defined by the W3C including directives which do not take any arguments (e.g. `upgrade-insecure-requests`).

https://www.w3.org/TR/CSP2/
https://www.w3.org/TR/CSP3/

For an excellent reference to the current state of the art as supported by some or all browsers see:

https://scotthelme.co.uk/csp-cheat-sheet/

Directives which are not supported by any browser version are ignored.

**Comment by grempe** [comment]
Pull request has been submitted for this issue:

https://github.com/sinatra/sinatra/pull/1202

**Comment by zzak** [comment]
/cc @jkowens 

And #1216 if we can get this in time.
