### ISSUE TITLE
unable to see logger calls outside of development environment 

### ISSUE THREAD

**Issue by damienh** [sinatra/sinatra#1203]
Hi, I cant get my head around why I am unable to see logger calls outside of development environment. 

I am using Sinatra `1.4.7` and inside my app I am defining logging as follows:

```ruby
configure do
  file = File.new("log/#{ENV['RACK_ENV']}.log", 'a+')
  file.sync = true
  use Rack::CommonLogger, file
end

configure do
  set :logging, true
end
```

and within the app I am calling the logger like so:

```ruby
get '/' do
  logger.info 'log this ?'
end
```

In development mode I can see `I, [2016-11-14T16:09:17.275939 #11703]  INFO -- : log this ?` but in my other staging and production environments it simply doesnt show. I have tried other calls such as `warn` and `error`.

I am using puma `2.12.3` in all my environments, however in staging and production `stdout_redirect` is set to for `puma_access.log` and `puma_error.log`. and I checked to see if they're going there but it doesnt include any logger calls. Worth noting that in staging and production calls are being log to their respective `env`.log file e.g.

`10.33.33.30 - - [14/Nov/2016:15:45:30 +0000] "GET /a-page/ HTTP/1.0" 404 7730 0.0322`

Is there anything I am missing or doing wrong in order for my logger calls to appear? 

Any help would be much appreciated.

**Comment by mwpastore** [comment]
You will have to upgrade to Puma 3.x, but there is a new-ish `--log-requests` command-line (or `log_requests` in a Puma configuration file) option that will enable request logging to stdout/stderr in non-development environments. For a full explanation and tortured history of this problem, see [this Puma issue](https://github.com/puma/puma/issues/731).

**Comment by damienh** [comment]
@mwpastore I upgraded to puma `3.2.0` and my puma config file looks like:

```
#!/usr/bin/env puma

directory '/var/www/staging.codeclubprojects.org/current'
rackup "/var/www/staging.codeclubprojects.org/current/config.ru"
environment 'staging'

pidfile "/var/www/staging.codeclubprojects.org/shared/tmp/pids/puma.pid"
state_path "/var/www/staging.codeclubprojects.org/shared/tmp/pids/puma.state"
stdout_redirect '/var/www/staging.codeclubprojects.org/shared/log/puma_access.log', '/var/www/staging.codeclubprojects.org/shared/log/puma_error.log', true
log_requests true

threads 0,6
bind 'unix:///var/www/staging.codeclubprojects.org/shared/tmp/sockets/puma.sock'
workers 1
worker_timeout 30
daemonize true
preload_app!

on_restart do
  puts 'Refreshing Gemfile'
  ENV["BUNDLE_GEMFILE"] = "/var/www/staging.codeclubprojects.org/current/Gemfile"
end
```

But the only thing that actually gets logged to `staging.log` is:

```
Nov 16 11:46:08 staging.codeclubprojects.org staging.log:  I, [2016-11-16T11:46:08.651683 #29882]  INFO -- sentry: ** [Raven] Raven 2.1.2 ready to catch errors
Nov 16 11:46:08 staging.codeclubprojects.org staging.log:  [29882] * Inherited unix:///var/www/staging.codeclubprojects.org/shared/tmp/sockets/puma.sock
Nov 16 11:46:08 staging.codeclubprojects.org staging.log:  [29882] * Daemonizing...
Nov 16 11:46:26 staging.codeclubprojects.org staging.log:  I, [2016-11-16T11:46:26.808952 #30179]  INFO -- sentry: ** [Raven] Raven 2.1.2 ready to catch errors
Nov 16 11:46:26 staging.codeclubprojects.org staging.log:  [30179] * Inherited unix:///var/www/staging.codeclubprojects.org/shared/tmp/sockets/puma.sock
Nov 16 11:46:26 staging.codeclubprojects.org staging.log:  [30179] * Daemonizing...
Nov 16 11:57:55 staging.codeclubprojects.org staging.log:  I, [2016-11-16T11:57:55.702382 #31055]  INFO -- sentry: ** [Raven] Raven 2.1.2 ready to catch errors
Nov 16 11:57:55 staging.codeclubprojects.org staging.log:  [31055] * Inherited unix:///var/www/staging.codeclubprojects.org/shared/tmp/sockets/puma.sock
Nov 16 11:57:55 staging.codeclubprojects.org staging.log:  [31055] * Daemonizing...
Nov 16 12:00:29 staging.codeclubprojects.org staging.log:  I, [2016-11-16T12:00:29.490512 #31339]  INFO -- sentry: ** [Raven] Raven 2.1.2 ready to catch errors
Nov 16 12:00:29 staging.codeclubprojects.org staging.log:  [31339] * Inherited unix:///var/www/staging.codeclubprojects.org/shared/tmp/sockets/puma.sock
Nov 16 12:00:29 staging.codeclubprojects.org staging.log:  [31339] * Daemonizing...
```

I added these to a `get` to test appearance in the logs:

```ruby
logger.error 'Sample Error'
logger.info 'Sample Info'
logger.warn 'Sample Warn'
```

but nothing. I have ensured that the config for puma is being applied.

Worth noting that these calls aren't showing in pumas `access.log` or `error.log` but these files are being populated with gets and 404s ect. 

Im happy to move this to the puma repo if needed.

**Comment by mwpastore** [comment]
You've solved the Puma problem, but now you're back to the issue that it's somewhat tricky to log to both a file and stdout from Rack applications. Your solution is close, but it looks like you need to put your `set :logging, true` statement *before* your `use Rack::CommonLogger, file` statement. More information is available [here](http://recipes.sinatrarb.com/p/middleware/rack_commonlogger).

**Comment by damienh** [comment]
@mwpastore Managed to work out it was infact nginx serving static files that caused the logs not to appear as it never got handed off to the server. Found this out when I noticed it did log when it actually hit error pages.

Cheers for your help though
