### ISSUE TITLE
Rack middleware initialization happens at different time than rackup

### ISSUE THREAD

**Issue by itamarst** [sinatra/sinatra#1205]
Use case: I want to register the server with a service discovery mechanism at startup. The additional functionality involved is well-suited to middleware, and the registration is currently implemented in the middleware's `initialize` method.

With rackup the middleware is initialized upon server startup.

With Sinatra's `use`, either at top-level or inside a `Sinatra::Base`, the middleware is only initialized after the first request is received:

It would be useful if Sinatra had same behavior as rackup, initializing all middleware at server startup.

Sinatra: 1.4.7
Rack: 1.6.4

**Comment by itamarst** [comment]
Example that shows the problem: message is only printed after first request.

[example.txt](https://github.com/sinatra/sinatra/files/604456/example.txt)

**Comment by zzak** [comment]
This has the added benefit of speeding up the first requests response time :+1:
