### ISSUE TITLE
Remove backports dependency from sinatra-contrib

### ISSUE THREAD

**Issue by mwpastore** [sinatra/sinatra#1207]
Now that the minimum Ruby version is 2.2 (.2 due to Rack 2), can we remove sinatra-contrib's dependency on backports? Tests pass on 2.2.2 without it with some light refactoring around String#underscore and Object#try. 

Why is Rack::Test a runtime dependency and not a development dependency?

I've submitted a PR with these changes but wanted to see what "tribal knowledge" might be out there.

**Comment by zzak** [comment]
I think it's ok, but want to focus what limited time budget I have on shipping and will probably put this kind of stuff off until after the release.

**Comment by zzak** [comment]
#1208 resolves this

**Comment by mwpastore** [comment]
Partially. Just the Rack::Test part. The other stuff is still outstanding per your guidance.

**Comment by zzak** [comment]
@mwpastore hehe no, that patch actually has the bits that remove backports. I already merged the rack-test patch ;)

**Comment by mwpastore** [comment]
@zzak Derp. Deleting my last comment as well as this one.

**Comment by ChrisBAshton** [comment]
Can you close this issue please? #1208 has been merged 🎉
