### ISSUE TITLE
2.0.0

### ISSUE THREAD

**Issue by zzak** [sinatra/sinatra#1216]
For organizing what's left in the release, will tag this issue with stuff that gets merged or needs attention for 2.0.

**Comment by zzak** [comment]
#1202 should be added to release notes

**Comment by zzak** [comment]
#1209 should be added to release notes

**Comment by burningTyger** [comment]
Are you going to remove the deprecated methods and lines with 2.0 warnings in base.rb?

**Comment by zzak** [comment]
@burningTyger Can you be more specific?

**Comment by burningTyger** [comment]
https://github.com/sinatra/sinatra/blob/master/lib/sinatra/base.rb#L941
https://github.com/sinatra/sinatra/blob/master/lib/sinatra/base.rb#L1183
https://github.com/sinatra/sinatra/blob/master/lib/sinatra/base.rb#L1376

**Comment by zzak** [comment]
@burningTyger Sure! Can you send a PR?

**Comment by burningTyger** [comment]
#1221 includes that

**Comment by grosser** [comment]
is all good to go here ... would love to get a version that works with rack 2
... otherwise how about a release of 1.x that works with rack 2 ?

**Comment by zzak** [comment]
I will try to do an rc in the next week or two.

**Comment by zzak** [comment]
RC :clapper: 
https://github.com/sinatra/sinatra/releases/tag/v2.0.0.rc1
https://rubygems.org/gems/sinatra/versions/2.0.0.rc1

**Comment by namusyaka** [comment]
Awesome :1st_place_medal:

**Comment by iffyuva** [comment]
@zzak we can close this issue, close the milestone and call it a day?
