### ISSUE TITLE
it's possible to change public_folder dynamically in runtime?

### ISSUE THREAD

**Issue by nvoynov** [sinatra/sinatra#1217]
Hello,

I'm trying to set public folder dynamically during execute CLI command. But all my attempts failed.
I just want to serve content from markdown file and its image assets, that I produce from other my gem. And I write a simple gem for serving - just one `def '\'` plus code for markdown to html transformation, and CLI to provide parameters like file and port.

I was able to get to work only one thing - run application through system exec `ruby app.rb file_name`. Are there any other possibility to get it work where I can set public_folder based on parameters of my cli command?

Sinatra 1.4.7, the application is simple enough

```ruby
require 'sinatra'
require 'sinatra/content_for'
require 'haml'
require_relative 'kmarkdown'

configure do
  enable :inline_templates
  set :environment, :production
  set :haml, { :ugly => true }
  set :public_folder, Dir.pwd
end

get '/' do
  markdown = File.join(settings.public_folder, "requirements.md")
  mdoc = Kmarkdown.new(File.read(markdown))
  @doc = mdoc.html
  @toc = mdoc.toc
  haml :index
end

# TODO check format parameter is odt or pdf?
get 'download/:fmt' do
  send_file File.join(settings.public_folder, "requirements.md")
end

__END__
@@ index
# skipped
```

And followed simple Thor command

```ruby
desc "serve [REPOSITORY]", "Serve web application for REPOSITORY"
method_option :port, aliases: "-p", type: :numeric, desc: "port"
def serve(repository = nil)
  repository ||= Dir.pwd
  Dir.chdir(repository) do
     `ruby #{File.join(Gem.root, 'lib/gem/web.rb'}`
  end
end
```

How can I change this ugly system exec `ruby #{File.join(Gem.root, 'lib/gem/web.rb'}` and start sinatra app in `repository folder`? Under repository folder I have target file and assets:

```
- requirements.md
- assets/
   - image.png
   - image.2.png
   - others
```

**Comment by mwpastore** [comment]
There are a number of ways to do what you're trying to do. Probably the easiest way would be:

1. In your Sinatra application's `configure` block, set `:public_folder` to something like `proc { fail "Must set public folder!" }` (i.e. some invalid default value)
1. And then for Thor:

    ```ruby
    def serve(repository = Dir.pwd)
      Sinatra::Application.public_folder = repository
      Sinatra::Application.run!
    end
    ```

Does that meet your needs?

**Comment by nvoynov** [comment]
Thanks for your hint! I'll try it now

**Comment by mwpastore** [comment]
Happy to help! Please close the issue if there's nothing further. Have a great day!
