### ISSUE TITLE
Change logger format globally

### ISSUE THREAD

**Issue by scalp42** [sinatra/sinatra#1219]
How would someone go around changing the logger formatting "globally" for the whole app without having to do it in every route ?

Assuming the subclass approach:

```ruby
class MainController < Sinatra::Base
end

class SubController < MainController
  get '/ping' do
    logger.formatter = proc do |severity, datetime, progname, msg|
      "[#{datetime} #{severity}] #{msg}\n"
    end
    logger.info 'Changed the formatting!'
    'pong'
  end
end
```

Thanks in advance!

**Comment by mwpastore** [comment]
In MainController (or SubController):

```ruby
class MainController < Sinatra::Base
  before do
    logger.formatter = proc do |severity, datetime, progname, msg|
      "[#{datetime} #{severity}] #{msg}\n"
    end
  end
end
```

This might be slightly less inefficient, although I haven't benchmarked it:

```ruby
module MyFormatter
  def self.call(severity, datetime, progname, msg)
    "[#{datetime} #{severity}] #{msg}\n"
  end
end

class MainController < Sinatra::Base
  before do
    logger.formatter = MyFormatter
  end
end
```

Rack::Logger is kind of inefficient to begin with because Rack creates a new instance of Logger on every request. You are making it even more inefficient by setting a formatter on every request. If performance is a concern—and especially if you don't need request logging—you might consider leaving `:logging` disabled and keeping your own logger instance as an application global. Logger is thread-safe.

**Comment by scalp42** [comment]
@mwpastore thanks for the input, I didn't know about that.

Any chance you could share how it would look like ? I'm assuming turning off Rack::Logger would be done through the `enable :logging` parameter but I'm not sure about the application global:

```ruby
class MainController < Sinatra::Base
  enable :logging
end
```

Thanks a lot!

**Comment by mwpastore** [comment]
Logging is disabled by default when you subclass Sinatra::Base, so just leave out your `enable :logging` and it will stay disabled.

An application global might take the form of a Sinatra setting (your solution is close), like so:

```ruby
require 'logger'

class MainController < Sinatra::Base
  configure do
    set :mylog, Logger.new(STDOUT).tap do |logger|
      logger.formatter = proc do |severity, datetime, progname, msg|
        "[#{datetime} #{severity}] #{msg}\n"
      end
    end
  end

  get '/ping' do
    settings.mylog.info 'test'
    'pong'
  end
end
```

Or a top-level constant, like so:

```ruby
require 'logger'

MYLOG = Logger.new(STDOUT).tap do |logger|
  logger.formatter = proc do |severity, datetime, progname, msg|
    "[#{datetime} #{severity}] #{msg}\n"
  end
end

class MainController < Sinatra::Base
  get '/ping' do
    MYLOG.info 'test'
    'pong'
  end
end
```

**Comment by scalp42** [comment]
@mwpastore thanks so much, I get it now.

I'll look more into Rack::Logger regarding the inefficiency (been doing this in other apps) as I didn't know.

Closing the issue, much appreciated!

**Comment by mwpastore** [comment]
Happy to help!

Creating an object on every request isn't *terrible* (Sinatra::Base and its dependencies already create almost 200 of them on every request), so I don't want to overstate it, but it's something to be aware of. You can see what I'm talking about [here](http://www.rubydoc.info/github/rack/rack/Rack%2FLogger%3Acall) if you're interested. Good luck!
