### ISSUE TITLE
newline-handling problem in Sinatra's erb implementation

### ISSUE THREAD

**Issue by RichMorin** [sinatra/sinatra#1228]
The Embedded Ruby implementation for Sinatra (1.4.7) removes (some) newlines. Basically, if an interpolated string is on a line by itself (no text either before or after), the newline goes away.  The Ruby (2.0.0p481) ERB library does not exhibit this problem.

See https://gist.github.com/RichMorin/055bb69484207885ab51e7cdd6ac44dd for details.

-r

P.S.  I tried posting this to the mailing list, but (like a post I made a couple of weeks ago) it was held for review.  Hello?

**Comment by mwpastore** [comment]
Sinatra uses [Tilt](https://github.com/rtomayko/tilt) behind the scenes to dispatch calls to its [`render`](http://www.sinatrarb.com/intro.html#Views%20/%20Templates) helper (and associated `erb`, `haml`, etc. helpers) to different rendering engines. When Tilt invokes [ERB](http://ruby-doc.org/stdlib-2.4.0/libdoc/erb/rdoc/ERB.html), it sets `trim_mode` to `<>` by default, which "omits newlines for lines starting with `<%` and ending in `%>`." Your call to ERB sets `trim_mode` to `nil` (by dint of your not including it in the call), so it doesn't trim anything. 

This is the source of the inconsistency in your results. To align the results, you can either:

1. Set `:trim` to `false` in your call to `render` (see [here](https://github.com/rtomayko/tilt/blob/master/docs/TEMPLATES.md))
1. Set `trim_mode` to `<>` in your call to [ERB.new](http://ruby-doc.org/stdlib-2.4.0/libdoc/erb/rdoc/ERB.html#method-c-new)
1. Use an alternate ERB implementation such as [Erubis](https://github.com/kwatch/erubis) or [Erubi](https://github.com/jeremyevans/erubi) (although I think Tilt only supports Erubis out of the box through [Tilt::ErubisTemplate](https://github.com/rtomayko/tilt/blob/master/docs/TEMPLATES.md#erubis))

I'll defer the mailing list question to @zzak! I'm not sure if anyone is moderating it; last time I looked at it there had only been a handful of posts in the past year.

**Comment by RichMorin** [comment]
Thanks for clarifying the situation and suggesting alternatives.

**Comment by zzak** [comment]
Here is fine, I'm not sure anyone really uses the Mailing List anymore.

We also have [slack](https://sinatra-slack.herokuapp.com/).
