### ISSUE TITLE
Update 2.0 README translations

### ISSUE THREAD

**Issue by burningTyger** [sinatra/sinatra#1249]
The Readme is our comprehensive sinatra documentation and deserves a lot of love. Thank you for everybody who has contributed to it so far!

The translations are great but some of them seem incomplete or outdated. For sinatra 2.0 they need a major overhaul and here's a list of languages that need to be worked on:

- [x] German
- [x] Spanish
- [ ] French
- [ ] Hungarian
- [x] Portuguese (Brasil/Portugal)
- [ ] Korean
- [x] Russian
- [x] Chinese

**Comment by zzak** [comment]
Here are all the commits on README, most everything since the last release fits on one page:
https://github.com/sinatra/sinatra/commits/master/README.md

**Comment by romasks** [comment]
Hi. I'd like to update [Russian](https://github.com/sinatra/sinatra/blob/master/README.ru.md) translation of 2.0 README.

**Comment by romasks** [comment]
There is a phrase in section [Literal Templates](https://github.com/sinatra/sinatra/blob/master/README.md#literal-templates): "if there is a filesystem path **or** line associated with that string". Maybe **and** will be more suitable in this context?

**Comment by Ice-Storm** [comment]
Hi. I'd like to update [Chinese](https://github.com/sinatra/sinatra/blob/master/README.zh.md) translation of 2.0 README. 
PR [#1323](https://github.com/sinatra/sinatra/pull/1323)

**Comment by CharlyJazz** [comment]
I am currently working on the Spanish translation. :construction_worker_man:

**Comment by nbulaj** [comment]
Check out #1393 with up-to-date RU translation.

**Comment by raphaeltelatim** [comment]
@burningTyger Do you still need pt-BR translation for 2.0 README?

**Comment by burningTyger** [comment]
@raphaeltelatim Sorry, my Portuguese is not good enough to tell if it's up to date :) But if it needs new docs we're happy to merge them! Thank you for your efforts.

**Comment by Klockner** [comment]
@burningTyger I've checked the pt-BR translation from README and realized that it is outdated, can I work on it? =)

**Comment by burningTyger** [comment]
@Klockner sure, that would be great. :+1:

**Comment by Klockner** [comment]
@burningTyger It is my first contribution, so I will start with this little one (https://github.com/sinatra/sinatra/pull/1497) and keep moving forward. Should I use this same PR for all the changes that will come or should I do it in separated parts?
Any advice would be welcome, thanks. 👍

**Comment by burningTyger** [comment]
@Klockner this looks good so far. I suggest you translate the explanations around the code samples which you already did along with the different configuration settings and then sqash them into one commit so it looks nice. If all you edit is the md file you can add a `[ci skip]` to your commit message so the tests are not run on it. If you manage to translate even more that would also be very nice. Do you know someone who could look over your translation? My Portuguese is really poor.

One more thing I noticed. Could you try to keep each line with 80 characters or less? ie. make a line break before 80 characters? I know, it's a relic from the past but I found it quite useful later on when comparing line changes.

**Comment by Klockner** [comment]
@burningTyger I got someone pt-br native to do the review. I have also applied your suggestions on it.
What are the next steps?

**Comment by christopherganda** [comment]
I would like to add indonesian translation, is there any requirements I need to understand?

**Comment by burningTyger** [comment]
@christopherganda first of all welcome to sinatra! If you would like to translate feel free just start with the basics. The documentation is quite comprehensive and even a subset is a great start. It helps if you have someone you can work with and who can proof read your translations. I will be checking your translation afterwards for style errors and the like.

**Comment by christopherganda** [comment]
@burningTyger Cool! Working on it

**Comment by jeduardo824** [comment]
I noticed that pt-br translation needs some updates. @Klockner are you working on this? I can start to work on those updates if you stopped to translate :)

**Comment by Klockner** [comment]
@jeduardo824 sounds great for me, if it's ok for @burningTyger go ahead! I can also do the pt-br review for you =)

**Comment by burningTyger** [comment]
sure, just go ahead.

**Comment by pedropaulino** [comment]
Anyone need help with the Brazilian Portuguese ?

**Comment by pedropaulino** [comment]
Is the topic still valid ?

**Comment by jeduardo824** [comment]
@pedropaulino I updated Brazillian Portuguese translation. Waiting for the merge.

**Comment by burningTyger** [comment]
I've had a very quick glance at it. Please fix the following parts:
-[Definindo Corpo, Código de Status e Cabeçalhos] (#definindo-corpo-codigo-de-status-cabeçalhos) -> space
- Configurações Disponíveis has a messed up markup, parts of it show up in monospaced font
- there is something wrong at the very bottom of the file

**Comment by camillesk** [comment]
the issue still valid to new translations?

**Comment by burningTyger** [comment]
Sure, but it would be good if someone took this over from me.

**Comment by pabuisson** [comment]
I can give a go at updating the French readme, looks like it's not been updated for 6 months.

**Comment by pabuisson** [comment]
Got a PR for updates on the French readme : https://github.com/sinatra/sinatra/pull/1568

I might make a separate PR someday for the "sessions" section where a lot of new content is missing. But don't have enough time for it right now.

**Comment by camillesk** [comment]
My PR for pt-br translations is here: https://github.com/sinatra/sinatra/pull/1573

Soon I'll update the other half of the file

**Comment by jeduardo824** [comment]
I already have a PR with an updated PT-BR translation @camillesk

**Comment by pabuisson** [comment]
Hey guys 👋 I was wondering what would be the best way to act on those documentation PRs and have them merged? They would improve locale documentation for the whole Sinatra project, seems it'd be a shame to let them die.

Any maintainer in particular we should ping about this?
