### ISSUE TITLE
Showexceptions error when install sinatra from Rubygems

### ISSUE THREAD

**Issue by VoTaiTri** [sinatra/sinatra#1252]
```ruby
gem "sinatra"
gem "rack-protection"
```
bundle installed (Rails 5.0.1, ruby 2.3.1p112), i have : 
- sinatra-1.0
- rack-2.0.1
- rack-protection-1.5.3
but when i run server, i get this error : 
```
/bundle/ruby/2.3.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require': cannot load such file -- rack/showexceptions (LoadError)
```
if i install sinatra from master branch on github like: `gem "sinatra", github: "sinatra/sinatra", branch: "master"`, everything's ok
i want to direct install sinatra from rubygems, don't throught github
so, can i do it? i need your help, thanks.

**Comment by mwpastore** [comment]
Sinatra 1.0 is extremely old and to the best of my knowledge no longer supported. When you install from master branch you are installing the 2.0 beta. The current stable version of Sinatra is 1.4.8. Maybe give this a try:

```ruby
gem "sinatra", "~> 1.4.8"
```

No need to include rack-protection in your Gemfile.

**Comment by VoTaiTri** [comment]
thanks @mwpastore
i remove rack-protection and try bundle update with only
```ruby
gem "sinatra", "~> 1.4.8"
```
and i get error like : 
```
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rails (< 5.1, >= 5.0.0.rc1) was resolved to 5.0.0.rc1, which depends on
      actionpack (= 5.0.0.rc1) was resolved to 5.0.0.rc1, which depends on
        rack (~> 2.x)

    sinatra (~> 1.4.8) was resolved to 1.4.8, which depends on
      rack (~> 1.5)
```

**Comment by mwpastore** [comment]
Are you trying to load Rails 5 and Sinatra in the same Ruby application? In that case, you have to use Sinatra 2.0, either the master branch from GitHub, or the beta2 release on RubyGems:

```ruby
gem "sinatra", ">= 2.0.0.beta2", "< 3"
```

**Comment by VoTaiTri** [comment]
i load Rails 5 and Sinatra in the same Ruby app. it's ok with Sinatra 2.0
thanks

**Comment by VoTaiTri** [comment]
@mwpastore 
ah, why we don't need include rack-protection in my Gemfile ?

**Comment by mwpastore** [comment]
Because Sinatra [includes it in its runtime dependencies](https://github.com/sinatra/sinatra/blob/c4fff34a747149c9749149175d359bc299572f58/sinatra.gemspec#L20) and [requires it automatically](https://github.com/sinatra/sinatra/blob/93a7997c14afabc50cbdcf252cb081bf06d6c190/lib/sinatra/base.rb#L7).

**Comment by VoTaiTri** [comment]
i got it now, thanks @mwpastore

**Comment by mwpastore** [comment]
You're welcome. Happy to help!
