### ISSUE TITLE
sinatra-namespace: cannot set :layout

### ISSUE THREAD

**Issue by mkaito** [sinatra/sinatra#1254]
What's the logic behind the check at line [282](https://github.com/sinatra/sinatra/blob/master/sinatra-contrib/lib/sinatra/namespace.rb#L282)? It seems you can, in fact, only `set :views` inside a namespace.

I'd like to set the layout for an entire namespace, in this case a CMS-like backend. And I'd like to do so without having to pass the same `:layout` argument to the `erb` method every time.

EDIT: Apparently `set :layout` is not a thing at all. Perhaps it should?
EDIT EDIT: Seems to be `set :erb, :layout => :something` instead, to set the default layout. But that has `sinatra-namespace` complaining about `set :erb`, which brings me back to the question above.

**Comment by mwpastore** [comment]
`set :erb` isn't a thing. You'll have to pass the layout each time. You can wrap the ERB helper like this (untested):

```ruby
namespace '/foo' do
  helpers do
    def erb(template, options={}, locals={}, &block)
      options[:layout] ||= :something
      super(template, options, locals, &block)
    end
  end
end
```

**Comment by mkaito** [comment]
Oh, but it is a thing. See this [right here](https://github.com/sinatra/sinatra/blob/f6395dce3e1bc3a9b3cc7da374d1748d3d3207fb/lib/sinatra/base.rb#L811). You can `set :<engine>, <options_hash>` and it checks for the `:layout` option [here](https://github.com/sinatra/sinatra/blob/f6395dce3e1bc3a9b3cc7da374d1748d3d3207fb/lib/sinatra/base.rb#L820).

**Comment by mwpastore** [comment]
Ah, it's not an official setting, but you're right, `render` will look for it if it exists. Good catch. 

I don't know why almost all settings are prohibited in namespaces. I've run into this issue myself and the workarounds are... clumsy. Perhaps someone else can chime in and explain the historical reasoning behind this decision.

**Comment by mkaito** [comment]
Without changing the code in `sinatra-namespace`, and to resolve this, I can `set :views` to different things depending on the namespace. Some template duplication aside (does tilt play well with symlinks, you think?), it should solve my use case decently.

The question about only allowing `set :views` still stands though. I'm not familiar enough with Sinatra internals to know whether there are any actual issues, and `sinatra-contrib` has some ancient code by people that haven't been around for years, so who knows. Does this stuff have any tests?

**Comment by mwpastore** [comment]
Is the `erb` helper solution not an option for some reason? Tilt should be fine with symlinks, but Git (and other version control systems) not so much. 

Agreed about sinatra-contrib. I and other contributors have been trying to chip away at some of the bit-rot over the past months. Code coverage is pretty good, all things considered.

**Comment by mkaito** [comment]
> Is the erb helper solution not an option for some reason?

No, it'd work just fine. It's just very clumsy. Not anyone's fault, since the code we're working around is just a little weird.

> Tilt should be fine with symlinks, but Git (and other version control systems) not so much.

Agreed, I just looked into it, and git doesn't handle project-relative symlinks in any way, which wouldn't work unless everyone stores their git clones in the same path.

> Agreed about sinatra-contrib. I and other contributors have been trying to chip away at some of the bit-rot over the past months. Code coverage is pretty good, all things considered.

I might see if I can just "expand" the allowed `set`tings and see if anything breaks. It might just be fine, who knows.

**Comment by mkaito** [comment]
I just did a minor refactor of that section, and all tests still pass. I'm putting up a PR so others can give it a test drive.

**Comment by mkaito** [comment]
Done in https://github.com/sinatra/sinatra/pull/1255
