### ISSUE TITLE
1.4.8 changelog?

### ISSUE THREAD

**Issue by adamdavis40208** [sinatra/sinatra#1258]
The changelog jumps from 1.4.7 to 2.0 -- was there anything in particular of interest in 1.4.8?

Thanks!

**Comment by mwpastore** [comment]
[Here](https://github.com/sinatra/sinatra/compare/v1.4.7...v1.4.8) is a comparison of the two releases. The major changes were 1. fixing Travis and 2. addressing the Fixnum deprecation warning in Ruby 2.4. That's it!

**Comment by joelpresence** [comment]
+1
