### ISSUE TITLE
`IndifferentHash#dig` not fetching proper value

### ISSUE THREAD

**Issue by edgarjs** [sinatra/sinatra#1268]
If any key in the chain is not a symbol, it doesn't return the proper value.

https://gist.github.com/edgarjs/ee81ef25f3a377f8c4379acac3a43cc5

**Comment by mwpastore** [comment]
I'm working on an improved IndifferentHash that will address this issue.

**Comment by zzak** [comment]
D'oh, thanks for your report @edgarjs!

Awaiting your patch @mwpastore :)

**Comment by zzak** [comment]
Closed by #1279
