### ISSUE TITLE
Regular expression based routes result in infinite loop

### ISSUE THREAD

**Issue by dometto** [sinatra/sinatra#1269]
Thanks for your work on sinatra 2.0! When checking compatibility between [gollum](https://github.com/gollum/gollum/) and `sinatra v2.0.0rc2`, I ran into the following issue. The app would get stuck when attempting to parse the following route definition:

```ruby
get %r{
      /compare/ # match any URL beginning with /compare/
      (.+)      # extract the full path (including any directories)
      /         # match the final slash
      ([^.]+)   # match the first SHA1
      \.{2,3}   # match .. or ...
      (.+)      # match the second SHA1
    }x  do |path, start_version, end_version|
```

Basically it would keep returning to `mustermann-1.0.0/lib/mustermann/regular.rb:39`, in the `check_anchors` method. So I tried to define the route with `check_anchors` disabled:

```ruby
get %r{
      /compare/ # match any URL beginning with /compare/
      (.+)      # extract the full path (including any directories)
      /         # match the final slash
      ([^.]+)   # match the first SHA1
      \.{2,3}   # match .. or ...
      (.+)      # match the second SHA1
    }x, :mustermann_opts => { :type => :regexp, :check_anchors => false } do |path, start_version, end_version|
```

...and the app works fine. But as far as I can see, the route definition doesn't employ any illegal anchors. And according to the `mustermann` docs, even if it did, it should just raise a `Mustermann::CompileError`. Can anyone explain the need for the addition? I would like to understand whether this is a bug, or whether sinatra `v2.0` just requires me to define routes in a different way.

**Comment by namusyaka** [comment]
Looks like a bug of mustermann.
Mustermann::Regular didn't consider regexp pattern built with Regxp::EXTENDED.

**Comment by dometto** [comment]
Thanks. I opened the issue there.
