### ISSUE TITLE
Tie Rack::Protection, Sinatra::Contrib version to Sinatra::VERSION

### ISSUE THREAD

**Issue by zzak** [sinatra/sinatra#1274]
I plan to maintain/release these gems in unison, so it's better to re-use the same VERSION to avoid confusion.

Much in the way that Rails ships activerecord, actionpack, etc

/cc #1216

**Comment by iffyuva** [comment]
@zzak should we have something like this https://github.com/rails/rails/blob/master/tasks/release.rb ?
