### ISSUE TITLE
Find out why `paper_trail` gem doesn't work w/ Sinatra 2

### ISSUE THREAD

**Issue by zzak** [sinatra/sinatra#1277]
https://github.com/airblade/paper_trail/issues/856

**Comment by jkowens** [comment]
I've sent up a PR to the paper_trail-sinatra project to add Sinatra 2 support:

https://github.com/jaredbeck/paper_trail-sinatra/pull/1

As far as I can tell there wasn't any conflict with Sinatra 2.

**Comment by jkowens** [comment]
Good news, the PR was merged and will be included in the next paper_trail-sinatra release.

**Comment by zzak** [comment]
Nice @jkowens, thank you for working on this! :bow:
