### ISSUE TITLE
Can we make an official subdomain support in sintra-contrib?

### ISSUE THREAD

**Issue by chenillen** [sinatra/sinatra#1289]
Since https://github.com/fnando/sinatra-subdomain subdomain hasn't updated for a long while.

**Comment by zzak** [comment]
Is this something people really want?

Would you be able to supply a patch and maintain it?

**Comment by codeblooded** [comment]
I'm a new contributor, and (if this really is a wanted feature), I could supply a patch and maintain it.

**Comment by chenillen** [comment]
Sorry guys, I think the project is under maintaining now.

**Comment by zzak** [comment]
I think it's up to @fnando tbh

**Comment by fnando** [comment]
I recently moved to a different country and that required all my focus. My life is getting back on track and I'm slowly tackling outstanding PRs/bugs on my projects. Sorry for the lack of communication.

As for moving sinatra-subdomain into sinatra-contrib: I have no objections. I'm not sure I'll be able to maintain it though.

**Comment by zzak** [comment]
@fnando Thanks for your quick reply!

I'm happy to give you commit if you want to send a PR to merge your extension! :bow:

**Comment by chenillen** [comment]
It's great to hear that, thanks a lot. @fnando and @zzak.
