### ISSUE TITLE
In modular style, instance variables are not passed from filter to route 

### ISSUE THREAD

**Issue by j4zzcat** [sinatra/sinatra#1290]
Consider the following code:
```
require 'sinatra/base'

class Filters < Sinatra::Base
  before do
    @var1 = 'var1'
  end
end

class Logic < Sinatra::Base
  before do
    @var2 = 'var2'
  end

  get '/something' do
    puts @var1.inspect # -> nil 
    puts @var2.inspect # -> 'var2'
  end
end

class Launcher < Sinatra::Base
  configure do
    use Filters
    use Logic
  end
end
```
As far as I understand, both ```@var1``` and ```@var2``` should have properly passed from their respected filter. However, only the instance variable ```@var2``` (was set in the same module as the route) get passed. 

Please advise.

**Comment by mwpastore** [comment]
This is more or less by design. Each middleware is its own class, so why would you expect instance variables to be shared between them? If you want to pass "things" from an outer middleware to an inner middleware or the app, the typical pattern is to stash it in the `env` hash.

**Comment by j4zzcat** [comment]
Thanks.
