### ISSUE TITLE
Unable to activate dm-serializer-1.2.2, because json-2.0.2 conflicts with json (~> 1.6) (Gem::ConflictError)

### ISSUE THREAD

**Issue by frankymad** [sinatra/sinatra#1294]
After Sinatra update to 2.0.0 version, my project fail to start.
Downgrade to sinatra 1.4.6 solved my issue.
Sinatra + Datamapper 1.2.0

How can i use SInatra 2.0.0 with Datamapper?

**Comment by zzak** [comment]
Could you provide a stacktrace?

**Comment by Sandro1991** [comment]
Help... Issue in my Proyect.

**Comment by smanezItec** [comment]
`# frozen_string_literal: true
source "https://rubygems.org"

# gem "rails"

gem "sinatra", "~> 1.4.6"

gem "json", "~> 1.6"`

My Gemfile. Help. I'm sorry for my english.

**Comment by zzak** [comment]
@smanezItec Could you send us a backtrace please? :bow:

**Comment by Ianden** [comment]
Having the same issue.

`
        from /home/landen/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
        from /home/landen/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/specification.rb:1428:in `each'
        from /home/landen/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/specification.rb:1428:in `activate_dependencies'
        from /home/landen/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/specification.rb:1410:in `activate'
        from /home/landen/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems.rb:220:in `rescue in try_activate'
        from /home/landen/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems.rb:213:in `try_activate'
        from /home/landen/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
        from /home/landen/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from main.rb:4:in `<main>'
`

**Comment by milesalex** [comment]
I have this error too!

**Comment by goocastro** [comment]
Same here

**Comment by smanezItec** [comment]
Soluciòn: utilizar Bundler con un archivo Gemfile

Supongamos que tu aplicación se llama MiApp, se encuentra en mi_app/app.rb y tiene el siguiente código:

require 'sinatra'

class MiApp < Sinatra::Base
  get "/" do
    "Hola mundo!"
  end
end

    Crea un archivo Gemfile, en el directorio raíz de tu aplicación, con el siguiente contenido:

    source "https://rubygems.org"

    ```
gem 'sinatra',           '1.4.8'
    gem 'data_mapper',       '1.2.0'
    gem 'dm-sqlite-adapter', '1.2.0'
    gem 'json',              '~>1.6'
    gem 'thin',              '1.7.0'
    gem 'slim',              '3.0.8'
    gem 'shotgun',           '0.9.2'
```

    Crea un archivo configu.ru, también en el directorio raíz de tu aplicación, con el siguiente contenido:

   ```
 require 'rubygems'
    require 'bundler'

    Bundler.require

    require './app'
    run MiApp

```
    Donde app se refiere al nombre de tu archivo (i.e. app.rb) y MiApp al nombre de tu clase dentro de ese archivo.

    Ejecuta shotgun utilizando bundle exec (para utilizar la versión de rake adecuada):

    `$ bundle exec shotgun`

Con esta configuración garantizas que tu aplicación utilice las gemas y versiones indicadas en el Gemfile, independientemente de las versiones que tengas instaladas en tu sistema.

**Comment by hamad2030** [comment]
I have the same problem >> any solutions yet?

**Comment by zzak** [comment]
Please remove the `gem 'json', '...'` from your Gemfile and try again :bow:

**Comment by mike-bailey** [comment]
I got this area, and I don't have JSON in my Gemfile, but I have plenty of other stuff:

```
source 'https://rubygems.org'
gem 'sinatra'
gem 'data_mapper'
gem 'webrick'
gem 'dm-sqlite-adapter'
gem 'actionview'
gem 'sinatra-flash'
gem 'rubyzip'
gem 'httparty'
gem 'aws-sdk'
gem 'net-ldap'
gem 'net-ssh'
gem 'duo-api'
```

**Comment by casi** [comment]
Apparently it is necessary to write this gem versions explicitly in the Gemfile and to use a config.ru to configure Rack. Smanezitec's solution with using Ruby 2.3.3 works fine for me:

My Gemfile:
```ruby
source 'https://rubygems.org'

gem 'sinatra',            '1.4.8'
gem 'data_mapper',        '1.2.0'
gem 'dm-sqlite-adapter',  '1.2.0'
gem 'json',               '~>1.6'
gem 'shotgun',            '0.9.2'
gem 'slim',               '3.0.8'
gem 'thin',               '1.7.0'
```

my config.ru:
```ruby
require 'rubygems'
require 'bundler'

Bundler.require

require './app'
run MiApp
```

my main.rb:
```ruby
require 'sinatra'
require 'data_mapper'

# setup the database connection
DataMapper.setup(
  :default,
  ENV['DATABASE_URL'] || "sqlite3://#{Dir.pwd}/development.db"
)

# model definitions etc. placed here ...

# check the integrity of the models
DataMapper.finalize

class MiApp < Sinatra::Base
  get '/' do
    "Hello World!"
  end
end
```

**Comment by mike-bailey** [comment]
Still an issue for me, used the above gemfile pretty much to the T and still didn't go

**Comment by casi** [comment]
Ok, so then change the line
```ruby
gem 'json', '~>1.6'
```
into
```ruby
gem 'json', '1.8.6'
```
or uninstall json 2.1 if possible, and do a ```bundle install``` again.

**Comment by mike-bailey** [comment]
Even with both JSONs uninstalled, different combinations, etc this still persists.

**Comment by szabcsee** [comment]
This issue still persist and Sinatra 2.0 can not be used with data_mapper, am I right?

**Comment by zzak** [comment]
I'm not sure this is even an issue, or how Sinatra would be at fault.

We don't even specify json as a dependency:
https://github.com/sinatra/sinatra/blob/master/sinatra.gemspec#L28-L31

It must be caused through some transitive dependency that is apart of your application.

If anyone can provide a `Gemfile.lock` which reproduces the issue, and stacktrace to go with it, we could probably figure out which one.

**Comment by mike-bailey** [comment]
https://github.com/sinatra/sinatra/issues/1294#issuecomment-313166451

**Comment by zzak** [comment]
@mike-bailey could you share your lockfile?

**Comment by mike-bailey** [comment]
Given this is like a season old I don't still have the project around in that state, but my gemfile at the time was what was linked.

**Comment by frankymad** [comment]
@zzak 
[https://github.com/frankymad/sinatra-datamapper-sample/blob/master/lockfile](url)

**Comment by elisaado** [comment]
@zzak, thank you for wanting to help, my lockfile: https://hastebin.com/raw/otihuqujib (hastebin because it's pretty long)

**Comment by peterwdj** [comment]
I've also been having this exact issue! Has anyone yet found a resolution?

**Comment by SirKeebz** [comment]
This issue still hasn't been resolved? I'm currently have the same problem.

**Comment by kgrz** [comment]
@SirKeebz do you have a backtrace for this?

**Comment by lshep** [comment]
I'm still getting this same issue - I'm trying to use sinatra (2.0.1) and  data_mapper (1.2.0) - has there been any resolution yet?

**Comment by dentarg** [comment]
@lshep can you provide a Gemfile.lock and stack trace that reproduces the issue?

**Comment by lshep** [comment]
So I don't have a Gemfile.lock. I'm admittedly am a notice trying to learn and work thought examples.  I am working through 
[Just Do It Part I](https://www.sitepoint.com/just-do-it-learn-sinatra-i/) and made it through no problem but now when I am working through [Just Do It Part II](https://www.sitepoint.com/just-do-it-learn-sinatra-ii-2/).  I haven't installed any specific versions of gems so I assume I am running all the latest.  But when I run

**Comment by dentarg** [comment]
@lshep I see

If you create `Gemfile` with the following content:

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra"
gem "data_mapper"

```

and issue the commands

    gem install bundler
    bundle install

you will be able to run `irb` like this:

```ruby
$ bundle exec irb
irb(main):001:0> require './main'
=> true
```

and `main.rb` like this:

    bundle exec ruby main.rb

**Comment by lshep** [comment]
I get the same error but the following is the Gemfile.lock that was produced:
```
JustDoIt$ cat Gemfile.lock 
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    bcrypt (3.1.12)
    bcrypt-ruby (3.1.5)
      bcrypt (>= 3.1.3)
    data_mapper (1.2.0)
      dm-aggregates (~> 1.2.0)
      dm-constraints (~> 1.2.0)
      dm-core (~> 1.2.0)
      dm-migrations (~> 1.2.0)
      dm-serializer (~> 1.2.0)
      dm-timestamps (~> 1.2.0)
      dm-transactions (~> 1.2.0)
      dm-types (~> 1.2.0)
      dm-validations (~> 1.2.0)
    dm-aggregates (1.2.0)
      dm-core (~> 1.2.0)
    dm-constraints (1.2.0)
      dm-core (~> 1.2.0)
    dm-core (1.2.1)
      addressable (~> 2.3)
    dm-migrations (1.2.0)
      dm-core (~> 1.2.0)
    dm-serializer (1.2.2)
      dm-core (~> 1.2.0)
      fastercsv (~> 1.5)
      json (~> 1.6)
      json_pure (~> 1.6)
      multi_json (~> 1.0)
    dm-timestamps (1.2.0)
      dm-core (~> 1.2.0)
    dm-transactions (1.2.0)
      dm-core (~> 1.2.0)
    dm-types (1.2.2)
      bcrypt-ruby (~> 3.0)
      dm-core (~> 1.2.0)
      fastercsv (~> 1.5)
      json (~> 1.6)
      multi_json (~> 1.0)
      stringex (~> 1.4)
      uuidtools (~> 2.1)
    dm-validations (1.2.0)
      dm-core (~> 1.2.0)
    fastercsv (1.5.5)
    json (1.8.6)
    json_pure (1.8.6)
    multi_json (1.13.1)
    mustermann (1.0.2)
    public_suffix (3.0.2)
    rack (2.0.5)
    rack-protection (2.0.3)
      rack
    sinatra (2.0.3)
      mustermann (~> 1.0)
      rack (~> 2.0)
      rack-protection (= 2.0.3)
      tilt (~> 2.0)
    slim (3.0.9)
      temple (>= 0.7.6, < 0.9)
      tilt (>= 1.3.3, < 2.1)
    stringex (1.5.1)
    temple (0.8.0)
    tilt (2.0.8)
    uuidtools (2.1.5)

PLATFORMS
  ruby

DEPENDENCIES
  data_mapper
  sinatra
  slim

BUNDLED WITH
   1.16.2
```

**Comment by dentarg** [comment]
I don't get the error with your `Gemfile.lock`, are you sure it is the same error? Please post all the commands and their output

**Comment by lshep** [comment]
Nevermind -  I had to add the dm-sqlite-adapter to the Gemfile and re install.  @dentarg  thank you for your assistance!

**Comment by sandstrom** [comment]
For anyone who find this via google:

```
gem uninstall -Vax --force --no-abort-on-dependent json
# specify your desired json gem version in Gemfile
bundle install
```

**Comment by noahniuwa** [comment]
> Apparently it is necessary to write this gem versions explicitly in the Gemfile and to use a config.ru to configure Rack. Smanezitec's solution with using Ruby 2.3.3 works fine for me:
> 
> My Gemfile:
> 
> ```ruby
> source 'https://rubygems.org'
> 
> gem 'sinatra',            '1.4.8'
> gem 'data_mapper',        '1.2.0'
> gem 'dm-sqlite-adapter',  '1.2.0'
> gem 'json',               '~>1.6'
> gem 'shotgun',            '0.9.2'
> gem 'slim',               '3.0.8'
> gem 'thin',               '1.7.0'
> ```
> 
> my config.ru:
> 
> ```ruby
> require 'rubygems'
> require 'bundler'
> 
> Bundler.require
> 
> require './app'
> run MiApp
> ```
> 
> my main.rb:
> 
> ```ruby
> require 'sinatra'
> require 'data_mapper'
> 
> # setup the database connection
> DataMapper.setup(
>   :default,
>   ENV['DATABASE_URL'] || "sqlite3://#{Dir.pwd}/development.db"
> )
> 
> # model definitions etc. placed here ...
> 
> # check the integrity of the models
> DataMapper.finalize
> 
> class MiApp < Sinatra::Base
>   get '/' do
>     "Hello World!"
>   end
> end
> ```

How did you know which version numbers to use?

**Comment by voodoologic** [comment]
I had this problem w/ ruby 2.6.3 and I just reverted to ruby 2.3.7

**Comment by srgx** [comment]
Add require 'bundler/setup' to main.rb.

**Comment by srgx** [comment]
Add `require bundler/setup` to main.rb.

**Comment by scanclini** [comment]
I solved this issue by: 
gem 'json', '~> 1.6', '>= 1.6.7'

**Comment by mike-bailey** [comment]
Are contributors still looking at this? Tried multiple things in this thread to limited/no avail. Gonna work on getting a Lockfile or something.

**Comment by mike-bailey** [comment]
After trying to make myself useful, I've noticed data_mapper is archived, so presumably unmaintained. We're working on dropping DataMapper from our project.

**Comment by daBee** [comment]
I recently found this out as well.  Sequel is alive and well.  A Google group with the author in there.  It's quite good.  It needs a Dash library though.
