### ISSUE TITLE
Namespaces and Rack-Router don't work as expected

### ISSUE THREAD

**Issue by stereobooster** [sinatra/sinatra#1296]
```
Root = Rack::Builder.new do
  use Sinatra::Router do
     mount SinatraApp1
     mount SinatraApp2
  end
end

class SinatraApp1 < Sinatra::Base
   register Sinatra::Namespace

   namespace "/abc" do
      get "/" { "Hello" }
   end
end
```

**Comment by jkowens** [comment]
Could you elaborate more about what you mean they don't work as expected? If you could provide a complete code sample that would help as well.

**Comment by jkowens** [comment]
Also, what version of Sinatra are you using?

**Comment by stereobooster** [comment]
Sinatra 1.4. Detailed example [here](https://gist.github.com/stereobooster/985cdbd494688e7b50551d2d62aaae1b). Also feel like I miss something simple

**Comment by stereobooster** [comment]
Figured out it

```ruby
Root = Sinatra::Router.new do
  mount NamespaceApp1
  mount NamespaceApp2
  mount Application
end
```
