### ISSUE TITLE
Namespaces and MultiRoute don't play along

### ISSUE THREAD

**Issue by adrianbn** [sinatra/sinatra#1297]
Hi,

I have a Sinatra app that uses namespaces and I was trying to add multiroute, but they don't seem to be compatible. If within a namespace you try to define a multiroute you get the following error:
`TypeError: no implicit conversion of String into Hash`.

```
class MyAPI < Sinatra::Base
  namespace '/parent' do
    get '/this', '/that' do
      "should work"
    end
  end
end
```

If I `extend Sinatra::MultiRoute` within my namespace the error is not thrown, but the second route is not recognized and returns a 404. It feels like both extensions should work well together, am I missing something here?

Thanks!

**Comment by jkowens** [comment]
By doing `extend Sinatra::MultiRoute` you should at least get your basic example to work. Sinatra::Namespace won't handle `route` functionality, but it looks like basic `get` calls work:

```
class MyAPI < Sinatra::Base
  register Sinatra::Namespace
      
  namespace "/api" do
     extend Sinatra::MultiRoute
     get "/foo", "/bar" do
       "foo or bar"
     end
  end
end
```

Another option might be to forget MultiRoute and just use Namespace patterns:

```
class MyAPI < Sinatra::Base
  register Sinatra::Namespace
      
  namespace "/api" do
     get ["/foo", "/bar"] do
       "foo or bar"
     end
  end
end
```

**Comment by adrianbn** [comment]
Hey @jkowens, thanks for the feedback. 

Both of your examples turn out the same; doing `extend Sinatra::MultiRoute` as in your example above results in only the first route (`/foo`) being recognized by Sinatra. The second route throws a 404. The same thing happens when using the `get ['/foo', '/bar']` syntax.

I've also tried using a regex such as `get %r{(/foo|/bar)} do` but that ends up giving 404 for both paths. Funny enough not even the example regex route from the documentation `get %r{/hello/([\w]+)} do` seems to work with namespaces, returning a 404.

Thanks for the help :)

**Comment by jkowens** [comment]
That's odd, I tested both and they worked. Are you using Sinatra 2.0?

**Comment by adrianbn** [comment]
No, I'm on 1.4 mostly for things like sinatra-param.

**Comment by jkowens** [comment]
Oh gotcha, yeah pattern matching is one of the improvements in the latest release.  I would expect most extensions to be compatible with Sinatra 2 with only minor updates. Hopefully they catch up soon!

**Comment by jkowens** [comment]
Here's an example alternative for namespaces suggested by @kytrinyx with MultiRoute supported added:

```
require 'sinatra'
require 'sinatra/multi_route'

class Apples < Sinatra::Base
  register Sinatra::MultiRoute

  get '/eat', '/consume' do
    "yummie"
  end
end

class Bananas < Sinatra::Base
  get '/eat' do
    "eeew"
  end
end

Fruit = Rack::Builder.new do
  map '/apples' do
    run Apples
  end

  map '/bananas' do
    run Bananas
  end
end

gem 'minitest'
require 'minitest/autorun'
require 'rack/test'

class FruitTest < Minitest::Test
  include Rack::Test::Methods

  def app
    Fruit
  end

  def test_apples
    get '/apples/eat'
    assert_equal "yummie", last_response.body

    get '/apples/consume'
    assert_equal "yummie", last_response.body
  end

  def test_bananas
    get '/bananas/eat'
    assert_equal "eeew", last_response.body
  end
end
```

See: https://github.com/sinatra/sinatra-contrib/issues/136#issuecomment-48832850

**Comment by adrianbn** [comment]
That's a good pattern as well, thanks. I'm going to close this and try to get sinatra-param upgraded to use sinatra 2. Thanks!

**Comment by zzak** [comment]
Perhaps we could put this in the docs somewhere? :bow:
