### ISSUE TITLE
revise for GETTING STARTED

### ISSUE THREAD

**Issue by topporo** [sinatra/sinatra#1299]
I've tried running 'sinatra' for the first time.
Try to follow 'README' at the public site, but stopped at 'Getting started'
The instruction of getting started uses the first example, 'myapp.rb'.
But I did not notice it.

Thus I suggest to revise the instruction,
Not only

>And run with:
```
ruby myapp.rb
```
but
>Make myapp.rb as shown above:
>And run with:
```
ruby myapp.rb
```

**Comment by zzak** [comment]
Hello @topporo,

From the README your `myapp.rb` should look like this:

```ruby
# myapp.rb
require 'sinatra'

get '/' do
  'Hello world!'
end
```

**Comment by topporo** [comment]
Hello, zakk.
I understand.
Thank you for responding.
