### ISSUE TITLE
Consider  adding ./VERSION file to gemspec in order to support local unpacking.

### ISSUE THREAD

**Issue by bwad** [sinatra/sinatra#1308]
Ruby Version: 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]

**Procedure to reproduce:**

1. Unpack gem locally:

        gem unpack sinatra

2. Create Gemfile:

        source "https://rubygems.org"
        gem 'sinatra', :path => './sinatra-2.0.0'

3. Run bundler:

        bundle install

    Output: 

        [!] There was an error while loading `sinatra.gemspec`: No such file or 
             directory @ rb_sysopen - <redacted>/sinatra-2.0.0/VERSION. Bundler 
             cannot continue.

        #  from <redacted>/sinatra-2.0.0/sinatra.gemspec:1
       #  -------------------------------------------
       >  version = File.read(File.expand_path("../VERSION", __FILE__)).strip
       #  
       #  -------------------------------------------

**Local Fix:**

  Create local `./sinatra-2.0.0/VERSION`  file with following contents:

      2.0.0

**Comment by b264** [comment]
Do you know why [this one](https://github.com/sinatra/sinatra/blob/a58834812b455101111ef332c7510bc9083c30d0/VERSION) doesn't work?

**Comment by bwad** [comment]
I expect it would.   

The issue is that the gemspec has a dependency on the existence of the '../VERSION' file and running bundle install on the locally unpacked gem trips over the unsatisfied dependency.

I could have copied the one from the project to fix my problem, but the issue is that it would be easier if it came with the unpacked gem in the first place.  I expect that adding "VERSION"  to the s.files section of the gemspec would fix the problem, but I don't really have the experience to say whether it's the best solution or that the issue even warrants the effort.

**Comment by zzak** [comment]
Ahh sorry, this must have been an oversight.

Could you send a patch? :bow:

**Comment by olleolleolle** [comment]
@zzak I made a patch.
