### ISSUE TITLE
NoMethodError: undefined method `join' for #<String:0x00000002c88ca8>

### ISSUE THREAD

**Issue by ijunaid8989** [sinatra/sinatra#1316]
Gemfile

```
source "https://rubygems.org"

gem "sinatra"
gem "mongoid"
gem "rake"
gem "haml"
gem "time_ago_in_words"
gem "shotgun"
gem "pry"
gem "sinatra-flash"
gem "sinatra-partial"

group :test do
  gem "minitest", require: "minitest/autorun"
  gem "rack-test", require: "rack/test"
end
```

and my test file

```
require "test_helper"
require "app"

class AppTest < MiniTest::Test
  include Rack::Test::Methods

  def app
    App
  end

  def test_retrieves_issues
    get "/issues"
    assert_equal last_response.body, "Issue"
  end
end
```

and app file 
```
class App < Sinatra::Base
  get "/" do
    "hello"
  end

  get "/issues" do
    @issues = Issue.all
    @issues
  end
end
```

This as simple as it is but I am getting error.

I have tried to update Sinatra to the master branch directly, But I found the errors for 
```
gem "sinatra-flash"
gem "sinatra-partial"
```

**Comment by rennex** [comment]
You didn't include a stack trace that would pinpoint the source of the exception, but no matter, I recognise the error. Many people have encountered it before, and I think Sinatra could do some sanity checking to produce more useful errors in these cases.

Basically you can return three types of values from a Sinatra route handler:

1. A String that becomes the response body
2. An Integer that becomes the response status code (such as 404)
3. An Array, which is interpreted as a Rack response: `[status, headers, body]`

You're returning `@issues` which is most likely an Array, so Sinatra treats it as a Rack response, and Rack tries to turn it into a HTTP response by joining the strings that the body object is supposed to yield.

You probably want to turn `@issues` into a string containing a JSON representation of the array, or something like that.

**Comment by ijunaid8989** [comment]
Thanks, That was it.
