### ISSUE TITLE
Sinatra 2.0.0 - system overloads on large uploads

### ISSUE THREAD

**Issue by Kanshiroron** [sinatra/sinatra#1327]
Hello,
I have a small web service that basically have a single endpoint to upload large files (docker tar images ~800MB)
However, I just upgraded Sinatra to version 2.0.0 (from 1.4.7), and my uploads now takes forever (over 10min (timed out) from the very same server that hosts the web service -> via loopback), compared to a few seconds before.
Also, the CPU is now at 100% (on a single thread -> 25% on a quad core), compared to 5-10% with the old version.

Here is my webserver:
```ruby
post '/create' do
	# checking if the CSS has been sent
	unless params[:css] && params[:css][:tempfile]
		return [400, "No css file sent"]
	end

	# saving upload file
	tar_file = "#{$docker_dir}/#{UUIDTools::UUID.random_create}.tar"
	File.open(tar_file, "wb") do |f|
		f.write(params[:css][:tempfile].read)
	end
end
```

And here is my upload client (with Gem RestClient):

```ruby
#!/usr/bin/env ruby

require 'rest-client'

# defines
$css_tar = "../../css/css.tar"
$base_url = "http://my-server:8080"
$http_timeout = 600

# checking if the css.tar is there
raise "Couldn't find css tar archive at: #{$css_tar}" unless File.exists? $css_tar

puts "INFO :: uploading css.tar archive"

# creating and sending request to upload archive
answer = RestClient::Request.execute(method: :post, url: "#{$base_url}/create", timeout: $http_timeout, payload: {:css => File.new($css_tar, 'rb')})

raise "ERROR :: Couldn't create infra from css.tar archive: #{answer.body}" unless answer.code == 200
```

Thanks for your help and support,
Best regards

**Comment by Ice-Storm** [comment]
It has nothing to do with Sinatra.
You should studay that how to deal large file in ruby.
 [What are all the common ways to read a file in Ruby?](https://stackoverflow.com/questions/5545068/what-are-all-the-common-ways-to-read-a-file-in-ruby)

**Comment by Kanshiroron** [comment]
Just to make sure we're on the same page, the issue is not the RAM but the CPU, and the issue is definitively on the server side. Also, the only thing that changed between my two tests is the Sinatra version.
Are you basically suggesting me to stream the upload to the file?

To give you more details on the issue with Sinatra 2.0.0: if I add a log on the server side, between the check and the save, this log will never be displayed (time out before (10min)).

Thanks

**Comment by jkowens** [comment]
In the Sinatra app, shouldn't the write mode be binary? Also, you reference params['css'] instead of params[:css].

```
	# saving upload file
	tar_file = "#{$docker_dir}/#{UUIDTools::UUID.random_create}.tar"
	File.open(tar_file, "wb") do |f|
		f.write(params[:css][:tempfile].read)
	end
```

**Comment by Kanshiroron** [comment]
Thanks @jkowens 
For the "param['css']", I had the change on my program but I copy/pasted from another one...
Regarding the binary write mode, I tested with it but this doesn't change anything.

Here is my server side code:
```ruby
#!/usr/bin/env ruby

require 'sinatra'
require 'uuidtools'

post '/create' do
	# checking if the CSS has been sent
	unless params[:css] && params[:css][:tempfile]
		return [400, "No css file sent"]
	end

	puts "WE ARE HERE"

	# saving upload file
	tar_file = "#{$docker_dir}/#{UUIDTools::UUID.random_create}.tar"
	File.open(tar_file, "wb") do |f|
		f.write(params[:css][:tempfile].read)
	end
end
```

The "WE ARE HERE" is never displayed

Best,

**Comment by jkowens** [comment]
Can you try something like this:

```
# saving upload file
tar_file = "#{$docker_dir}/#{UUIDTools::UUID.random_create}.tar"
puts "tar file: #{tar_file}"
tmp_file = params[:css][:tempfile].read
puts "read file"
File.open(tar_file, "w") do |f|
    f.write("this is a test") 
end
puts "wrote file"
````

Does your code work for small files?

**Comment by jkowens** [comment]
Interesting, so I see the same behavior for large files. The issue occurs before even entering the Sinatra route handler. When a large file is sent as param data, it takes a very long time to parse the params. This points to the issue being with Rack v2. I think someone will have to dig around in the [Rack::Multipart::Parser](https://github.com/rack/rack/blob/master/lib/rack/multipart/parser.rb#L59).

**Comment by jkowens** [comment]
Checking the Rack issue tracker confirms that this is a Rack issue.
See: https://github.com/rack/rack/issues/1075 and https://github.com/rack/rack/pull/1179

**Comment by janko-m** [comment]
Do you need this to be a multipart-encoded upload? Can it be an upload where the request body holds only the content of the file? That way you can avoid multipart parser, and on Puma request body is a Tempfile already,

**Comment by Kanshiroron** [comment]
@janko-m Not at all.
To be honest this is a (very) small internal project, and I don't even need Sinatra to be updated (it will probably stay in 1.4.7).
It's just that I noticed the issue after a fresh install (as I didn't fixed my Gem dependencies versions), so I reported it.

**Comment by jeremy** [comment]
Fixed by https://github.com/rack/rack/pull/1179 ✌️

**Comment by Kanshiroron** [comment]
Hi everybody,
I just tested with the master branch of the Rack project, and it fixes this issue.
However, the change hasn't been deployed to the the rubygem repo (https://rubygems.org/gems/rack/versions @jeremy)

Thanks for your help!
