### ISSUE TITLE
adding % to a paramater is not passed to sqlite when using Sinatra and Unicorn

### ISSUE THREAD

**Issue by metrix78** [sinatra/sinatra#1328]
Adding % symbols to a parameter will not get passed to sqlite under Unicorn and Sinatra 2.0, but work just fine running under rackup.  Percent symbols can also be passed to sqlite if they are stored in a string.  Passing % symbols worked just fine with Sinatra 1.4.7 and Unicorn 5.3.0.

Working example:
```Ruby
    get '/good/:string/' do
      test_string = "This search".gsub(' ','%').concat('%') #this works
      rs = @PREPARED_QUERY.execute(test_string)
    end
```

This breaks:
```Ruby
    get '/bad/:string/' do
      wildcard_search_string = params['string'].gsub(' ','%').concat('%')
      rs = @PREPARED_QUERY.execute(test_string)
    end
```

I have attached a test case tar file for testing.

setup: 
untar test case
execute commands in
[test_case.tar.gz](https://github.com/sinatra/sinatra/files/1167575/test_case.tar.gz)
 readme.txt

These tests were run under Debian Stretch.

Brandon

**Comment by dentarg** [comment]
I think we need to accept that Sinatra 1.4 and Sinatra 2.0 works differently. This behaviour may also be defined by Rack? Or where's `%` coming from, not the URL? Not sure I follow the examples. Haven't looked at the zip. Pull request with test case(s) demonstrating the issue are welcome. I'll close this though, it is pretty old now.
