### ISSUE TITLE
CHANGELOG could have a section on v1.4.8

### ISSUE THREAD

**Issue by olleolleolle** [sinatra/sinatra#1335]
Issue: `CHANGELOG.md` does not mention v1.4.8.

## TODO

- [ ] Summarize the changes in this compare view: https://github.com/sinatra/sinatra/compare/v1.4.7...v1.4.8
- [x] Mention release date: January 30, 2017 (source: https://rubygems.org/gems/sinatra/versions/1.4.8)

**Comment by zzak** [comment]
The only real change was fix the deprecation warning from ruby about `Fixnum`, the other commits were fixing the build

**Comment by olleolleolle** [comment]
Right, and soothing the anxious user, nervous ops person, or the perennially detail-oriented about this minor fix would be doable. I can PR, if that helps.

**Comment by zzak** [comment]
@olleolleolle Yep, that was my point :)
