### ISSUE TITLE
v2.0.1

### ISSUE THREAD

**Issue by zzak** [sinatra/sinatra#1339]
Prepare for next patch level release

**Comment by zzak** [comment]
Current list of changes [v2.0.0...master](https://github.com/sinatra/sinatra/compare/v2.0.0...master)

**Comment by olleolleolle** [comment]
Combing the compare list, I find these changes:

- #1322 Bugfix: Repair nested namespaces, by avoiding prefix duplication. Fixes #1310 (@namusyaka)
- _Lots_ of documentation improvements
- #1338 Ship the `VERSION` file with the gem, to allow local unpacking (@olleolleolle)

**Comment by namusyaka** [comment]
@olleolleolle Nice work!

**Comment by foxxx0** [comment]
The nested namespace fix would be great to have sooner rather than later.
For now I have to use the sinatra master branch in my Gemfile in order to work around that, but I would rather like to specify a fixed sinatra gem version.

So +1 for moving this along and thanks for all your work!

**Comment by gudmundur** [comment]
@zzak We've been bumping into the namespace issue recently. Any idea on when this'll go out? Cheers.

**Comment by zzak** [comment]
I'll either cut it this week or next (during thanksgiving break)

**Comment by gudmundur** [comment]
@zzak nudge nudge. :)

**Comment by namusyaka** [comment]
#1333

**Comment by namusyaka** [comment]
I have created a v2.0.1 milestone and marked some issues. 
I'll complete those issues and plan to cut the next release this week and next week.

**Comment by namusyaka** [comment]
Closing. v2.0.1 has been released.

Check it out:
https://rubygems.org/gems/sinatra 
https://rubygems.org/gems/sinatra-contrib
https://rubygems.org/gems/rack-protection

Thank you all for your contribution!
