### ISSUE TITLE
Module Method "Redirect" method not defined

### ISSUE THREAD

**Issue by daBee** [sinatra/sinatra#1352]
I've written a module that's loading fine.  As a test, I've set a method to redirect to a parameter url, which I'm using 'http://www.google.ca' as an easy test.  So I expect the method to completely bounce out of the app to google.  

    def Mymodule.validate_alpha(bounceURL)
        redirect bounceURL
    end

I am getting an error on this method:

    undefined method `redirect' for Mymodule:Module

I'm a little confused between `redirect` and `redirect to` in Sinatra, so maybe that's it, but in the meantime I'm confused that this sort of error would come up as it's still a defined method.  

Any insight appreciated.  Cheers

**Comment by mwpastore** [comment]
I answered your question in the sinatrarb discussion group. You are defining a module method, not an instance method. You just need to change it to this:

```
module Mymodule
  def validate_alpha(bounceURL)
    redirect bounceURL
  end
end
```

And it will work fine.

**Comment by daBee** [comment]
It still doesn't explain what's going on.  Is the Mymodule simply a namespace for the module?  I'm not disagreeing with you, I'm just trying to get my head around this.

**Comment by mwpastore** [comment]
This is not the proper forum to be asking fundamental questions about Ruby. Neither is the discussion group. Sorry if that seems harsh, but it's important to keep project-related communication channels free of non-project-related noise.

Yes, you can think of a module as a namespace for methods. You can also think of it like a mixin. When you use the `helpers` keyword in Sinatra and pass it the name of a module, it includes that module's instance methods as helpers. 

This:

```ruby
def Mymodule.validate_alpha(bounceURL)
  redirect bounceURL
end
```

Is the same as this:

```ruby
module Mymodule
  def self.validate_alpha(bounceURL)
    redirect bounceURL
  end
end
```

Which is not the same as this:

```ruby
module Mymodule
  def validate_alpha(bounceURL)
    redirect bounceURL
  end
end
```
