### ISSUE TITLE
Documentation Page there is an unaccessible link

### ISSUE THREAD

**Issue by superoo7** [sinatra/sinatra#1354]
On [document page](http://www.sinatrarb.com/documentation.html), there is an unaccessible link with title `RubyConf 08: Lightweight Web Services` in `Screencasts and Presentations` sections.

The unaccessible link is [http://rubyconf2008.confreaks.com/lightweight-web-services.html](http://rubyconf2008.confreaks.com/lightweight-web-services.html)

Please update the docs. Thanks

**Comment by burningTyger** [comment]
The slack heroku app is also dead.

**Comment by kgrz** [comment]
The confreaks URLs have changed. That talk is now available at: https://confreaks.tv/videos/rubyconf2008-lightweight-web-services

**Comment by jmyers0022** [comment]
Tossed up a PR for these: https://github.com/sinatra/sinatra.github.com/pull/230

**Comment by zzak** [comment]
The slack app should be fixed: https://sinatra-slack.herokuapp.com/

**Comment by namusyaka** [comment]
This should be fixed now, I think. Closed.
