### ISSUE TITLE
Add label guide to CONTRIBUTING.md

### ISSUE THREAD

**Issue by zzak** [sinatra/sinatra#1357]
We should add the labels mentioned in #1349 to our docs

**Comment by CharlyJazz** [comment]
What part of the documentation?

**Comment by zzak** [comment]
It should go in [this file](https://github.com/sinatra/sinatra/blob/master/CONTRIBUTING.md), named `CONTRIBUTING.md`, under tthe section "Looking for something to do?":

https://github.com/sinatra/sinatra/blob/master/CONTRIBUTING.md#looking-for-something-to-do

/cc @CharlyJazz
