### ISSUE TITLE
Why are route parameters encoded as "ASCII-8BIT"?

### ISSUE THREAD

**Issue by sinclairtarget** [sinatra/sinatra#1362]
Using Ruby 2.4.1 and Sinatra 2.0.0.

Using the following `get` invocation:
```
get '/entries/:slug' do |slug|
  logger.info slug.encoding
end
```

Making a GET request to `/entries/foo` will log the encoding as `ASCII-8BIT`.

Why is the encoding not UTF-8? This plays havoc with sqlite3 at the very least, which [interprets `ASCII-8BIT` strings as `BLOB` data](https://github.com/sparklemotion/sqlite3-ruby/issues/45#issuecomment-1895378) instead of string data.

**Comment by burningTyger** [comment]
I was having the same problem with tons of errors. I just enforced utf-8 on everything that comes via params. Works perfectly yet looks a bit awkward.

**Comment by lvonk** [comment]
@burningTyger how did you enforce this encoding? Is there a setting for this?

**Comment by sinclairtarget** [comment]
@lvonk "hello".force_encoding("utf-8")

That won't change the actual bytes of the string, just how ruby interprets them.

**Comment by lvonk** [comment]
@sinclairtarget Thanks, I was kind of hoping that there was a single setting in sinatra that would apply to all params.

**Comment by sinclairtarget** [comment]
@lvonk You could always just stick something like the following in front of Sinatra in your middleware stack:

```
class UnicodeOrBust
  def initialize(app)
    @app = app
  end

  def call(env)
    @app.call(force_path_encoding(env))
  end

  def force_path_encoding(env)
    env['PATH_INFO'] = env['PATH_INFO'].force_encoding('UTF-8')
    env
  end
end
```
