### ISSUE TITLE
Project website is down

### ISSUE THREAD

**Issue by zerowaitstate** [sinatra/sinatra#1364]
Looks like http://www.sinatrarb.com is down.  Getting infinite 302 redirects.  It sort of looks like the domain is in a parked status (port 80 pointed at secureserver.net), but I can't tell from the WHOIS.

**Comment by J-Vaughan** [comment]
Still experiencing redirects.

**Comment by namusyaka** [comment]
cc @bmizerany @zzak

**Comment by bmizerany** [comment]
Fixed!!! The domain is register for another 9 years. :)

**Comment by zzak** [comment]
Should be fixed now, but DNS resolves always take a little time

Let us know if this persists after a couple days

**Comment by jots** [comment]
it's still down.
```
$ dig +short @NS52.DOMAINCONTROL.COM sinatrarb.com
184.168.221.22
$ dig +short @NS52.DOMAINCONTROL.COM sinatrarb.com
50.63.202.12
```
I tried with both those IPs in my /etc/hosts and still website not answering.
What IP is it supposed to be?
