### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by fullofcaffeine** [sinatra/sinatra#1365]
At the time of this writing, trying to access the docs but can't, seems there's an infinite redirect loop:

http://www.sinatrarb.com/documentation.html

**Comment by Hobinx** [comment]
I have the same problem here, there's an infinite redirect loop between http://www.sinatrarb.com/ and http://sinatra.github.io

**Comment by GrantJamesPowell** [comment]
Is there a workaround or offline docs available?

**Comment by kgrz** [comment]
I’ll push something in a bit.

**Comment by mathemagik** [comment]
@GrantJamesPowell — https://github.com/sinatra/sinatra.github.com :-)

**Comment by kgrz** [comment]
And a temporary mirror at http://sinatra.wtf

**Comment by ckuttruff** [comment]
@kgrz thanks for being on top of things; so appreciate sinatra and yall's work.

**Comment by zzak** [comment]
Aaaaand we're back! http://sinatrarb.com/
