### ISSUE TITLE
question about .html.haml vs .haml

### ISSUE THREAD

**Issue by gartha1** [sinatra/sinatra#1368]
I see that with sinatra, doing  haml :index   it looks for views/index.haml    I know a guy that used sinatra once and thought it was index.html.haml  Has sinatra changed like was it ever index.html.haml?

thanks

**Comment by kgrz** [comment]
As far as I can tell, mapping `haml :index` to `views/index.html.haml` hasn't been the case for a long time. Are you sure the other person didn't use some plugin that augmented the template lookup functionality to be similar to Rails? Or may be [overwriting the default](https://github.com/sinatra/sinatra/blob/ba935c9d885ee811f5e8d12356fce4ad91545cbe/README.md#looking-up-template-files) [template lookup function](https://github.com/sinatra/sinatra/blob/ba935c9d885ee811f5e8d12356fce4ad91545cbe/README.md#using-custom-logic-for-template-lookup)?

**Comment by gartha1** [comment]
Could be.  I notice that http://haml.info/tutorial.html   mentions a .html.haml file  as does http://haml.info/docs/yardoc/file.REFERENCE.html#using_haml      I guess it's a default or common setting in rails for when haml is used within rails and maybe they confused rails with sinatra there.
