### ISSUE TITLE
undefined method `stop' for nil:NilClass when running example code (and other code as well)

### ISSUE THREAD

**Issue by elisaado** [sinatra/sinatra#1374]
Hi,
When I tried running my code, it failed with this error:
```
/home/eli/.gem/ruby/2.4.0/gems/puma-3.11.0/lib/puma/single.rb:18:in `stop': undefined method `stop' for nil:NilClass (NoMethodError)
	from /home/eli/.gem/ruby/2.4.0/gems/puma-3.11.0/lib/puma/launcher.rb:146:in `stop'
	from /home/eli/.gem/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1436:in `quit!'
	from /home/eli/.gem/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1461:in `ensure in run!'
	from /home/eli/.gem/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1461:in `run!'
	from /home/eli/.gem/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/main.rb:26:in `block in <module:Sinatra>'
/home/eli/.gem/ruby/2.4.0/gems/puma-3.11.0/lib/puma/single.rb:18:in `stop': undefined method `stop' for nil:NilClass (NoMethodError)
	from /home/eli/.gem/ruby/2.4.0/gems/puma-3.11.0/lib/puma/launcher.rb:146:in `stop'
	from /home/eli/.gem/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1436:in `quit!'
	from /home/eli/.gem/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1542:in `block in setup_traps'
```
The same error occurs when I run the example code. The sinatra gem and all it's dependencies are installed.

General info:
OS: Arch linux
Ruby version: `ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]`

**Comment by elisaado** [comment]
I also tried re-installing sinatra and all it's dependencies.

**Comment by rennex** [comment]
That error comes from somewhere in Puma. Have you tried if Webrick or Thin runs it any better?

And I'm not sure what example code you mean. Does the following minimal Sinatra app work on your machine?

    require "sinatra"
    get "/" do
      "Hello, world!"
    end

**Comment by elisaado** [comment]
Fixed... `sudo killall ruby`, I had another puma server running on that port without knowing.

**Comment by elisaado** [comment]
Hi @rennex,
Yup, I meant that code.
