### ISSUE TITLE
NoMethodError bad_request? when Rack app mounted along with Sinatra

### ISSUE THREAD

**Issue by jkowens** [sinatra/sinatra#1376]
Sinatra is currently setting the value for constant `Rack::ShowExceptions::TEMPLATE` with the value `Sinatra::ShowExceptions::TEMPLATE`. The problem is that the new template references a method that only exists in `Sinatra::ShowExceptions`. When other Rack based apps like Grape are used alongside Sinatra an error is raised when attempting to display the error page.

lib/sinatra/show_exceptions.rb
```
...

Rack::ShowExceptions.send :remove_const, "TEMPLATE"
Rack::ShowExceptions.const_set "TEMPLATE", Sinatra::ShowExceptions::TEMPLATE
```

In commit https://github.com/sinatra/sinatra/commit/57c2ebb854379fd28def61340ad0b35a8edea792 @kgrz mentioned an alternate solution would be override the `pretty` method. Maybe that would be the right path forward?

See: 

ruby-grape/grape/issues/1669

**Comment by zzak** [comment]
@jkowens Thank you for finding this!

I agree, and this should be considered a regression we should fix in 2.0.1 /cc #1339

**Comment by jkowens** [comment]
I've sent up PR rack/rack/pull/1223. Hopefully if things work out this will be an easy fix on the Sinatra side.

**Comment by jkowens** [comment]
In the meantime, I think overriding the `pretty` method is the best option.
