### ISSUE TITLE
params Hash Contains Persistent 'captures' Key

### ISSUE THREAD

**Issue by daBee** [sinatra/sinatra#1380]
I'm finding with `Sinatra 2.0.0` that a form submission has `params` that contain an obscure key/value pair with the key being `captures`, value being `[]`.  I am trying to take this out in a method using:

    incoming.delete('captures')

This doesn't work.  I continue to get values from the params hash, and is giving me an error:

    App 30407 stderr: 2018-01-17 17:09:15 - NoMethodError - undefined method `values' for []:Array

All of this is confusing as when I test in another test script, it works just fine as expected, just deleting the key/value pair in the hash:

    c = {"u"=>"Alpha", "s"=>"zulu", "captures"=>[]}
    c.delete('captures')
    puts c.class      # => hash

Is there an alternative way of getting rid of this obscure entry in my `params` hash, or can I pass params to a method to take it out somehow?  I need to do things with the normal `params` hash that I am expecting.  Apparently `Sinatra 2.0.0` introduced this new `params` entry.

**Comment by mwpastore** [comment]
I think we need to see more of your code, and more of the stack trace of the error you're seeing in your logs.

**Comment by daBee** [comment]
Upon restarting nginx, loading up my landing page, I have a generic params display in my `layout.erb`.  

    <strong><%= params.size %> Params</strong> <%= params.inspect %><br>

It resolves, upon no submission at all:

    1 Params {"captures"=>[]}

I have not implemented anything close to a parameter on the top landing page `GET` and the params show this in there.  I can't get rid of it.  Here is the `nginx error log` for that request:

    [ N 2018-01-17 22:10:37.7760 40600/T9 age/Cor/CoreMain.cpp:994 ]: Checking whether to disconnect long-running connections for process 40680, application /Library/WebServer/Documents/sourcer/public
    App 40831 stdout: 
    App 40899 stdout: 
    App 40831 stderr: 127.0.0.1 - - [17/Jan/2018:22:10:39 -0500] "GET / HTTP/1.1" 200 4804 0.0183

Here is the normal web log:

    127.0.0.1 - - [17/Jan/2018:22:10:39 -0500] "GET / HTTP/1.1" 200 4804 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7"

I guess I'm expecting this to not even be there.  Am I supposed to work around this being in the params all the time now?  If that is the case, then I'll work around that if I need to.  Other than that, I don't know what to expect from now on.

**Comment by mwpastore** [comment]
> I guess I'm expecting this to not even be there. Am I supposed to work around this being in the params all the time now? If that is the case, then I'll work around that if I need to. 

Yes, Sinatra puts captures and splat into the params hash. Starting with Sinatra 2.0, Mustermann's captures are always put into the params hash (I think). So you should work around it.

Something like this should do the trick:

```ruby
before do
  params.delete(:captures) if params.key?(:captures) && params[:captures].empty?
end
```

If that doesn't work, we need to see more of your Ruby code, and/or more of the Ruby stack trace of the error you're seeing in your logs.

**Comment by daBee** [comment]
OK, just tested the same using `Sinatra 2.0.0` and that pair is not in the params.  So something else is fishy here.  So my current question is: Is this supposed to be there?  I've never seen this before.

**Comment by daBee** [comment]
I cleaned up the params as you demonstrated (just to have some fun in my life), and cleaned up the params upon a get/post method.  Thanks for the notes.  That would have had me twirling for days.
