### ISSUE TITLE
sinatra-reloader fails to reload controller with streaming wrapper

### ISSUE THREAD

**Issue by troex** [sinatra/sinatra#1381]
I have a wrapper method to stream requests like this https://gist.github.com/troex/31790323fb4a8a29c8b8cd84e50ad1e8

the reload works in the sample '/test_stream' method, but if I create another class and inherit it from `MyController` it will not reload any `stream` methods while regular get/post methods reload without issue.

Any ideas if I'm doing something wrong or it's a bug?

**Comment by maryam-b** [comment]
@namusyaka Is this open for taking? is this a bug? would be great to know if we can work on it.

**Comment by dentarg** [comment]
@maryam-b I think it is safe to assume this bug is open for taking (label "help wanted" and no real activity here)

**Comment by namusyaka** [comment]
@maryam-b Sorry for the late.
Yes, this issue is still open.

We need to reproduce this bug as a first step.
If this bug can be reproduced, we shoud write a test and fix it.

I would appreciate if you can work on this issue.

Thanks,

**Comment by maryam-b** [comment]
@namusyaka okay then start working on it.

**Comment by ankitsinghaniyaz** [comment]
My site fails to reload when there's an error. Any idea what could be wrong?

**Comment by dentarg** [comment]
@jkowens https://github.com/sinatra/sinatra/pull/1805 was supposed to close this issue but GitHub does not support "Closes NNN and YYY" syntax that was used :) So please close it :)
