### ISSUE TITLE
When using Sequel gem, information isn't being updated

### ISSUE THREAD

**Issue by maxiedaniels** [sinatra/sinatra#1383]
I'm using Sinatra with Sequel, and my pages with database queries aren't updating. Example code:

```
get '/test' do
  testing = MySequelModel.map(:created_at).uniq
  "#{Time.at(testing.last).strftime("%b %e, %l:%M %p")}"
end
```

The first time I load the page, it will show the latest item in the database's creation time (items are created by a separate script every minute). However, I'll wait a few minutes and refresh the page, and the time is stuck at that initial time. The only way to get the page to actually get the latest time is to restart the Sinatra server.

I've tried disabling caching, and it didn't have an effect. I can only think this may be a weird bug?

**Comment by VMashanov** [comment]
Are you sure that the problem is not in your model?

**Comment by burningTyger** [comment]
This shoulb better be posted on StackOverflow. Doesn't seem to be a Sinatra issue. My guess is that your separate script is not working as expected. Try outputting the model to the console too (i.e. ` p testing.last`  and see if your route returns a cached page.
Apart from that you can get the last Model via Sequel too. You can let your database do the sorting, no need for a map :)

**Comment by maxiedaniels** [comment]
Just verified that this is not a Sinatra problem, my bad. I thought the issue wasn't occurring with non-Sinatra scripts, but it turns out if I run a infinite loop and `puts` that same parameter every 30 seconds, it stays stuck on the first 'version' of that data.

**Comment by burningTyger** [comment]
👍
