### ISSUE TITLE
Before filter adds empty captures to params

### ISSUE THREAD

**Issue by alexedwards** [sinatra/sinatra#1388]
Using a before filter with no pattern adds an empty `captures` attribute to `params`. This is unexpected behaviour when your application doesn't contain any regexp patterns with captures, and can cause problems for applications which are mapping `params` directly to another object.

A minimal case: 

```ruby
require 'sinatra'

before do
end

get '/' do
  params.to_s
end
```

```sh
$ curl -i localhost:9292
HTTP/1.1 200 OK 
Content-Type: text/html;charset=utf-8
Content-Length: 16
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Vary: Accept-Encoding
Server: WEBrick/1.3.1 (Ruby/2.3.3/2016-11-21)
Date: Thu, 15 Feb 2018 10:20:14 GMT
Connection: Keep-Alive

{"captures"=>[]}
```
 I suspect this might also be the cause of issue https://github.com/sinatra/sinatra/issues/1380. 

I think it's happening due to this [line of code](https://github.com/sinatra/sinatra/blob/62fb8ad8c6a42a2e1b755a9cbc419b78ea5f10ea/lib/sinatra/base.rb#L1346), which defaults the before filter pattern to the regexp `/.*/`:

```ruby
def before(path = /.*/, **options, &block)
        add_filter(:before, path, options, &block)
end
```

**Comment by namusyaka** [comment]
@alexedwards Hey, @iguchi1124's patch has been merged into master. If possible, could you confirm thing which has been resolved?
Please let me know if you still have any issues. Thanks for your report!

**Comment by namusyaka** [comment]
Additional notes:

You can confirm the patch by adding the following line into Gemfile.
Check it out:

```ruby
gem 'sinatra', github: 'sinatra/sinatra'
```

**Comment by alexedwards** [comment]
Great, that's sorted it out. Thanks for the speedy fix :+1:
