### ISSUE TITLE
status code 205 allows response body?

### ISSUE THREAD

**Issue by iguchi1124** [sinatra/sinatra#1397]
I referenced this commits https://github.com/rack/rack/commit/bcf2698bcc90f346b145538e53d0d61bcceb2e48

Currently, sinatra drops response body when status code is 205. but, I think it should be able to choice (b).

>b)
indicate a zero-length payload for the response by including a
Transfer-Encoding header field with a value of chunked and a message
body consisting of a single chunk of zero-length

Older RFC 2616 text is published at 1990, RFC7231 is published at 2014, so this implementation references RFC2616 probably, I propose 205 remove from `DROP_BODY_RESPONSES` constants.

what do you think?

**Comment by iguchi1124** [comment]
I'll make pull request regarding to this issue

**Comment by namusyaka** [comment]
@iguchi1124 Thanks.
Your proposal looks reasonable. Go ahead.
