### ISSUE TITLE
expires method overwriting Cache-Control max-age

### ISSUE THREAD

**Issue by iguchi1124** [sinatra/sinatra#1403]
I have a question about `expires` method.
I am reading https://tools.ietf.org/html/rfc7234#section-5.3, 

>   If a response includes a Cache-Control field with the max-age
   directive (Section 5.2.2.8), a recipient MUST ignore the Expires
   field.  Likewise, if a response includes the s-maxage directive
   (Section 5.2.2.9), a shared cache recipient MUST ignore the Expires
   field.  In both these cases, the value in Expires is only intended
   for recipients that have not yet implemented the Cache-Control field.

Sinatra's implementation of `expires` method is overwrite Cache-Control header `max-age` forcibly. for that why, Expires header is ignored by client.

I suggest to stop overwriting Cache-Control header `max-age` at next patch version.

And, I think the `expires` method name is very ambiguous(overwriting `Cache-Control` values, not only `Expires`). At next major version, I propose to rename method or re-design this method.

What do you think?

**Comment by namusyaka** [comment]
@iguchi1124 No. You should work on this after the issue becomes more clearer.
At first, we need to discuss the issue.

**Comment by iguchi1124** [comment]
@namusyaka Ah, it meant that I want to work for next patch version things, to stop overwriting Cache-Control header `max-age` forcibly. Isn't it bugs?

**Comment by namusyaka** [comment]
The behavior has existed for nine years, and then it looks like intentional. Even if the behavior is not valid, we cannot fix it as patch-level release. Maybe minor version release. Thoughts?

**Comment by iguchi1124** [comment]
I checked RFC2616 which is referenced by implementer probably,

https://tools.ietf.org/html/rfc2616#section-14.21
>  Note: if a response includes a Cache-Control field with the max-
      age directive (see section 14.9.3), that directive overrides the
      Expires field.

I think forcibly overwriting is not intentional.

For example, `Expires` specified time and `max-age` duration are able to indicates not equal expires time by network latency.

**Comment by namusyaka** [comment]
What would you do if you are to tackle this problem?
Could you show me the simple patch?

**Comment by namusyaka** [comment]
This issue has two problems.
I think you know about those. Could you separate your issues?

**Comment by jkowens** [comment]
From what I understand it is considered good practice to have the `Expires` header and `max-age` directive contain matching values. If any change is necessary, I think that the `cache_control` method should set the `Expires` header with a matching time value.

**Comment by jkowens** [comment]
Closing because I don't think there is a strong enough case to make any change.
