### ISSUE TITLE
v2.0.2 planning

### ISSUE THREAD

**Issue by namusyaka** [sinatra/sinatra#1407]
We're currently planning on issues to incorporate into v2.0.2 milestones.
I have already marked some problems as v2.0.2, but if you have any problems you would like to address elsewhere, please propose here.
I am planning to confirm them and support them so that they can run smoothly.

see also: https://github.com/sinatra/sinatra/milestone/21

Thanks

**Comment by arpitchauhan** [comment]
Hi,

If this goes into 2.0.2, it'd be much appreciated. :) https://github.com/sinatra/sinatra/pull/1431

**Comment by namusyaka** [comment]
Although v2.0.2 still has many issue and patches, I decided to immediately release v2.0.2 in order to fix critical vulnerability
