### ISSUE TITLE
Around filter

### ISSUE THREAD

**Issue by stefansedich** [sinatra/sinatra#1414]
How does one achieve an `around` filter, I need to add some correlated logging info to an ambient log context that requires wrapping a block around the request.

I could use some Rack middle-ware but I really want to be able to re-use some existing Sinatra helpers to get at the data I need, is there a way or am I out of luck?

**Comment by stefansedich** [comment]
My current hack involves monkey patching `dispatch!` on Sinatra::Base which appears to work but makes me sad inside, is there a hook I am missing somewhere?

**Comment by namusyaka** [comment]
Can you use `before` and `after` filters?
Also consider using sinatra extension mechanism instead of rack-middleware.
See http://sinatrarb.com/extensions.html
