### ISSUE TITLE
Sinatra::IndifferentHash after calling symbolize_keys! is still using strings as keys

### ISSUE THREAD

**Issue by owyongsk** [sinatra/sinatra#1423]
Seems like `symbolize_keys!` is a method from its parent class `Hash`, maybe we should raise an error when symbolize_keys! is called? This is unexpected behavior in my opinion.

Important to note that the underlying storage must still be strings based on https://github.com/rails/rails/issues/14643 and Matz opinion at https://bugs.ruby-lang.org/issues/9731

**Comment by iguchi1124** [comment]
Oh sorry, it was my misread. `Hash#symbolize_keys!`  is ActiveSupport core extension method, so I'm sure now that the changes should not merge into Sinatra::Indifferent::Hash.

**Comment by owyongsk** [comment]
Wow, I screwed this up, didn't check properly on my environment.
