### ISSUE TITLE
change syntax for optional named parameters?

### ISSUE THREAD

**Issue by jaequery** [sinatra/sinatra#1426]
Hi, is there any way we can change the syntax for optional named parameter from:

/user/?:id?

to

/user/(:id) 

?

the reason is that i'm trying to show people just how simple and elegant Sinatra is, and everything is great except that part, which is a bit ugly.

I can switch to Padrino or Rails but I don't want to do that.

Can anyone help me on this? Thank you!

**Comment by nickpelone** [comment]
With Mustermann/Sinatra 2.0 I believe the preferred form is to use a group and then make it optional at the end, eg:

`/user(/:id)?`

where the above would match `/user`, `/user/1` (with `id` as `1`), etc

See https://github.com/sinatra/mustermann/blob/master/mustermann/README.md#-sinatra-pattern for grouping syntax and the suggestion to use groups alongside an optional at the end.

**Comment by jaequery** [comment]
@nickpelone doesn't work for me. i'm on Sinatra 2.0.1

**Comment by nickpelone** [comment]
You're missing the `?` at the end, which tells the pattern matcher that the group is optional:

#### example.rb
```ruby
require 'sinatra'

get '/user(/:id)?' do
  [200, params.to_s]
end
```
- `/user` - will work
- `/user/nick` - will work
- `/user/` - _won't_ work, I'm only just now noticing this (I don't have to support this in my app, so I never noticed)

If you _must_ support the `/user/` case then I imagine `/user/?(:id)?` will work, but I see that ultimately points back to why you opened the issue in the first place (multiple question marks is confusing, i'm presuming. or something.)

**Comment by priscilasolis** [comment]
Taking…

**Comment by priscilasolis** [comment]
I made some changes for this issue [here](https://github.com/sinatra/sinatra/pull/1433). Let me know if you have questions or comments!

**Comment by namusyaka** [comment]
@sizief Go ahead.

**Comment by jkowens** [comment]
@sizief Are you still interested in working on this issue? I would love to see this change get into Sinatra.

**Comment by sirfilip** [comment]
Hello people love sinatra and love to help with something can pick this one up if needed

**Comment by jkowens** [comment]
@sirfilip that would be great 👍

**Comment by dentarg** [comment]
Can we support both syntaxes? Not sure we want to introduce a breaking change in the syntax after all these years?

**Comment by jkowens** [comment]
@dentarg yeah I wouldn't want to break backwards compatibility. Even though I think the "Rails" syntax is nice I don't think it would be worth complicating mustermann over a minor inconvenience.

**Comment by dentarg** [comment]
Close this without action?

**Comment by jkowens** [comment]
Sounds good 👍
