### ISSUE TITLE
Where is the original request body when in error block

### ISSUE THREAD

**Issue by jcavalieri** [sinatra/sinatra#1429]
Hi Sinatra team,

I'm using sinatra (2.0.1) and I have an error block, doing something like this:

```
  error Exception do

    error_response = {
        environment: ENV['RACK_ENV'],
        route: env['sinatra.route'],
        message: env['sinatra.error'].message,
        backtrace: env['sinatra.error'].backtrace,
    }

    [500, {'Content-Type' => 'application/json'}, JSON.pretty_generate(error_response)]
  end
```

I also want to include the original requests JSON POST body if it is there.

Strange thing, when I test using racksh I can find it on several members like the following:
`request.params`, `env['sinatra.error.params']`, or `env['rack.request.form_vars']`

However, when I do an actual POST request (via postman, not racksh) these are always empty or nil.

Any idea what is going on, and how I could access the original POST body or params?

Thanks,
John

**Comment by namusyaka** [comment]
You can get original request body inside error block by using `Rack::Request#body`. It would be something like:

```ruby
error StandardError do
  request.body.read
end

post '/' do
  raise StandardError
end
```

Please reopen if you still have the issue.

**Comment by jcavalieri** [comment]
Thanks Namusyaka for the response. Your example definitely works for me.

However, I think what is going on is that I've already done the request.body.read in the originating POST route:
```
      content_type 'application/xml;charset=utf8'
      body = request.body.read
      args = body.strip.empty? ? {} : JSON.parse(body, symbolize_names: true)
```
And once it gets to the error block it has already been read. I'm assuming that read is a onetime call, like a stream.

Any suggestions where I might stash the original body during the POST request? Session doesn't sound appropriate. Or is there another call to get to the original POST request body?

Thanks,
John

**Comment by jcavalieri** [comment]
Ahhh, nevermind, just found what I need:

`request.body.rewind`

Thanks :-)
