### ISSUE TITLE
Path encoding issue

### ISSUE THREAD

**Issue by tenderlove** [sinatra/sinatra#1443]
Hi,

We're trying to upgrade a Sinatra 1.4.X app to 2.0.X.  It seems like URI paths get unescaped in Sinatra 1.4.X, but stay escaped in 2.0.X.  Here is an example program to demonstrate the issue:

```ruby
spec = eval "lambda { " + File.read("sinatra.gemspec") + "}.call"
spec.dependencies.each { |dep| gem dep.name, dep.requirement }

require "sinatra"
require "net/http"

expected = "foo\xE2\x80\x8Cbar".b

req_thread = Thread.new do
  Thread.current.abort_on_exception = true

  uri = URI.parse 'http://localhost:4567/contents/foo%e2%80%8cbar'
  begin
    actual = Net::HTTP.get_response(uri).body
    if expected == actual
      puts "great, it worked"
    else
      puts "Expected #{expected.dump} actual #{actual.dump}"
    end
    Process.kill 'INT', $$
  rescue Errno::ECONNREFUSED
    retry
  end
end

get %r{/contents/(.+)} do |path|
  path
end
```

If I run this program against the `v1.4.8` tag, then the path value is `"foo\xE2\x80\x8Cbar"`.  But if I run against master (currently c8910e9a7f9537e397f34b9e71e15757ccfbbae3), then the path value is still percent encoded as `"foo%e2%80%8cbar"`.

Is this change intentional?  The old behavior seems correct to me, otherwise I have to manually decode paths everywhere.  If the change is intentional, what's the best way for me to get this behavior back (I'd like to get the behavior back without changing the code for every route).

Thanks for your time!! ❤️🧡💛💚💙💜🖤

**Comment by namusyaka** [comment]
@tenderlove Hey, thanks for your report. 
I guess this is probably a matter of mustermann.
Either way, I will investigate this in the near future.

**Comment by tenderlove** [comment]
Thanks for your response! I can make a report on mustermann too, but I'm
not sure exactly what mustermann is responsible for. Maybe uri should be
unescaped before passing to mustermann?

Thank you!

**Comment by Semigradsky** [comment]
@namusyaka  Would be nice to have new version with this fix soon :smile_cat:

**Comment by namusyaka** [comment]
@Semigradsky Yeah, I'd like to release new version v2.0.4 as soon as possible. However, [there are many issues](https://github.com/sinatra/sinatra/milestone/24) marked as v2.0.4.
If you would help close the issues, we would like to thank you very much.

**Comment by dentarg** [comment]
@namusyaka can the issues be re-marked as v2.0.5 so this fix can be released earlier?

**Comment by namusyaka** [comment]
Frequently releasing the patch version is not good for me.
When releasing, we'll always need to update changelog and write blog posts.

At least I think that it's better to develop along milestones as much as possible unless a very critical problem is found.
On the other hand, it isn't always best to release on milestone street. That leads to stagnation of development.
So it may be a good idea to decide rules like releasing it once a half year, or once every few months like golang.
What do you think?

**Comment by gjtorikian** [comment]
Sorry for the drive by comment, but, if this is the case

> When releasing, we'll always need to update changelog and write blog posts.

it sounds like an opportunity for [automation](https://github.com/github-changelog-generator/github-changelog-generator).

While my projects don't have the history of Sinatra, for bugfixes, after a merge into master I'll almost immediately release a patch version. If one has followed semantic versioning properly, it should be a nice improvement to every dependent user, rather than waiting weeks for a "collection" of bugfixes to go out.

**Comment by namusyaka** [comment]
Indeed, changelog generation can be automated.
Of course, we have also automated to release the new version.

>(Which is to say, I'm happy to help automate the process if there's a list somewhere of the tasks one must follow.)

It's great. If many parts are automated, the cost of releasing will be greatly reduced.
In addition, I won't decide this on my own being, but I would like to lead to a discussion that defines a clear release cycle policy.
