### ISSUE TITLE
sinatra 2.0.3 introduces new `active_support` dependency

### ISSUE THREAD

**Issue by KrauseFx** [sinatra/sinatra#1451]
Hey sinatra contributors,

With sinatra 2.0.3, we now have `active_support` as a dependency, as introduced with https://github.com/sinatra/sinatra/pull/1442. I didn't dive into the code base yet on why this is necessary, so I wanted to check here first:

1. Was this change intentional? 
1. Is there a good alternative to avoid adding a new dependency to the graph? On the first look it seems like we're only using `active_support/core_ext/object/try.rb` and `backports/rails/string`

Context: we're using sinatra for the new [fastlane.ci](https://fastlane.ci) project.

**Comment by jkowens** [comment]
There is some discussion about this subject here: https://github.com/sinatra/sinatra/pull/1448

**Comment by KrauseFx** [comment]
Perfect, thanks @jkowens, I only searched for issues, not for PRs, thanks, will close this now 👍
