### ISSUE TITLE
cannot load such file -- app (LoadError)

### ISSUE THREAD

**Issue by murphygithub** [sinatra/sinatra#1456]
I got below error when I run ./webapp

root@6aa16207f6d3:/opt/webapp/bin# ./webapp
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- app (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./webapp:5:in `<main>'

I have checked my ruby version and don't find any issue. I am lost here.

root@6aa16207f6d3:/opt/webapp/bin# ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
root@6aa16207f6d3:/opt/webapp/bin# gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.3
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.3.0
     - /root/.gem/ruby/2.3.0
     - /usr/lib/x86_64-linux-gnu/rubygems-integration/2.3.0
     - /usr/share/rubygems-integration/2.3.0
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin

**Comment by dentarg** [comment]
Is this related to Sinatra? If so, do you mind explaining how? Maybe share the contents of the file you are trying to run (`webapp`)?

You might have a better time getting answers (if this is related to Sinatra) by posting to the mailing list: https://groups.google.com/forum/#!forum/sinatrarb

**Comment by murphygithub** [comment]
sorry turns out my project missing app moudle
