### ISSUE TITLE
I have just downloaded material-design-components from github but i can't seem to view it on the browser properly

### ISSUE THREAD

**Issue by samwizzy** [sinatra/sinatra#1458]
What do i do next after downloading material design components using "git clone https://github.com/material-components/material-components-web.git"
And i have navigated into the material-component-web directory using "cd material-components-web"

Should i just do this 
npm install to get it working 
Because i realize that inside the demo folder there are html, js and scss file. For example, the button.html file has no styling when opened of the browser
Can't i just compile the .scss file to .css file using sass cli like so:
sass style.scss style.css on my command line
Or is there a way to compile everything once

**Comment by kgrz** [comment]
Hi, not sure why you decided to open an issue in Sinatra repo, but yes, you're right. You'll have to run `npm install`, and to run a dev server, it looks like the authors provided a command:

https://github.com/material-components/material-components-web/blob/78a09fb9fa707a7e2554fbcb0227ce5055f841a4/package.json#L14

That can be invoked by running `npm run dev`.
