### ISSUE TITLE
Load Javascript and CSS Libraries from a gem in a Sinatra app

### ISSUE THREAD

**Issue by Prakriti-nith** [sinatra/sinatra#1465]
I want to load Frontend Javascript and CSS Libraries from a gem in a Sinatra app. To include static (JS and CSS) files, we can move the files into a folder named `public` but I can not find a way to load them from a gem.

**Comment by kgrz** [comment]
You might  have to rely on sprockets to do this. Sinatra directly can’t pick assets from inside of a gem. The recipes website has an example http://recipes.sinatrarb.com/p/asset_management/sprockets#article

**Comment by jkowens** [comment]
I know this is kind of dated, but here is an interesting blog post that might spur some ideas:

https://softwarebrothers.co/blog/using-sinatra-with-asset-pipeline-and-railsassets/
