### ISSUE TITLE
Custom logger

### ISSUE THREAD

**Issue by Arteneko** [sinatra/sinatra#1472]
I've been trying to set up a custom logger to hide some sensitive informations from the WEBrick auto-logging.

My code is the following:

```ruby
# service/log.rb
require 'rack'

module Service
    class RackLogger < Rack::CommonLogger
        def call(env)
            puts env["PATH_INFO"].inspect
            #super
            @app.call env
        end
    end
end

disable :logging
use Service::RackLogger
```

And my application (entrypoint) code is the following:

```ruby
# Require the necessary libraries.
require 'rubygems'
require 'rack'
require 'sinatra'
require 'sinatra/json'

configure do
  root = File.expand_path(File.dirname(__FILE__))
  set :logging, false #both false and nil provokes this behaviour
end

not_found do
  status 404
  json ({ error: "Not found" })
end

# Load the services.
Dir["app/services/*.rb"].each { |file| load file }
# Load the controllers.
Dir["app/controllers/*.rb"].each { |file| load file }
```

After this code, if run, I still get the usual logging alongside my own inspect puts call:

```
::1 - - [28/Aug/2018:21:46:15 +0200] "GET /album/... HTTP/1.1" 200 2205 0.8188
```

My question is: How to either disable the logging completely or change the logger class ?

**Comment by miguelsolano** [comment]
@IvanDelsinne  Can you provide a sample repo of when this is happening? I couldn't recreate it, but would love to try my hand at fixing the issue if it exists.

**Comment by IvanDelsinne** [comment]
[This repo](https://gitlab.com/Artemix/albumr/) containing a quite simple code is producing the error.

If you contact the route, two log lines appear, the first one being my `puts env["PATH_INFO"].inspect`; the second one being the rack logging.

To start the project, you simply have to do `bundle && bundle exec rackup`, which will listen to 9292.

## Example log

```
"/favicon.ico"
::1 - - [13/Oct/2018:13:06:08 +0200] "GET /favicon.ico HTTP/1.1" 404 21 0.0008
```

**Comment by karol-blaszczyk** [comment]
@IvanDelsinne Sinatra and WebRick are both adding CommonLogger. 

See discussion: https://stackoverflow.com/questions/31206060/sinatra-with-puma-gives-twice-the-output-in-the-terminal

What you can do in hacky way is to monkey patch Rack::CommonLogger like : 
```ruby
module Rack
  class CommonLogger
    def call(env)
      # do nothing
      @app.call(env)
    end
  end
end

**Comment by epergo** [comment]
👋 @Arteneko It's been more than 2 years since this issue was opened, did you manage to fix the issue? Did the last suggestion fix the problem?

**Comment by Arteneko** [comment]
I didn't, I ended up going towards some other solutions instead.

**Comment by epergo** [comment]
Ouch, would it be possible to re-upload the sample repository to have a look?

**Comment by Arteneko** [comment]
Since I removed it, no, sorry.

**Comment by epergo** [comment]
You can use the `-q / --quiet` option to silence the rack output, that way only your middleware would take effect.

```ruby
# config.ru
require 'rubygems'
require 'rack'
require 'sinatra'

require './app_base'

module Service
  class RackLogger < Rack::CommonLogger
    def call(env)
      puts env['PATH_INFO'].inspect
      @app.call env
    end
  end
end

use Service::RackLogger
run MyApp
```

```ruby
class MyApp < Sinatra::Base
  get '/' do
    'Hello world from Base'
  end
end
```

```bash
❯ bundle exec rackup --quiet
Puma starting in single mode...
* Puma version: 5.2.1 (ruby 3.0.0-p0) ("Fettisdagsbulle")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 49330
* Listening on http://127.0.0.1:9292
* Listening on http://[::1]:9292
Use Ctrl-C to stop
"/"

############# In another terminal

❯ http :9292/
HTTP/1.1 200 OK
Content-Length: 21
Content-Type: text/html;charset=utf-8
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

Hello world from Base
```

WDYT?
