### ISSUE TITLE
Remove Rack::Protection::ContentSecurityPolicy defaults

### ISSUE THREAD

**Issue by baelter** [sinatra/sinatra#1484]
`Rack::Protection::ContentSecurityPolicy` has `script-src` and `style-src` defaults making it impossible leave them out of the header to have them fallback to `default-src`.

**Comment by jkowens** [comment]
After reading some [docs](https://hacks.mozilla.org/2016/02/implementing-content-security-policy/), I agree that a better default would be to set `default-src: "'self'"` and to remove defaults for `script-src`, `style-src`, `img-src`, `connect-src`.

https://github.com/sinatra/sinatra/blob/e0aa37dce6f25700131ced4a09e10dda67250b36/rack-protection/lib/rack/protection/content_security_policy.rb#L39

If stricter settings needed to be used, those options could be explicitly set when loading this middleware.

**Comment by namusyaka** [comment]
PR is welcome ;)

**Comment by jkowens** [comment]
@namusyaka PR submitted 😃

**Comment by namusyaka** [comment]
@jkowens Good job! I'll take a look later!
