### ISSUE TITLE
Cannot rescue `Server.run!` when using puma

### ISSUE THREAD

**Issue by DannyBen** [sinatra/sinatra#1486]
Since I am using Sinatra as an embedded server in a couple of my command line tools, I would like to avoid showing Ruby traces to the user when sinatra fails to launch.

So - the obvious solution for me, is to simply rescue errors raised by `Server.run!`.

This works without a problem with `thin` as the server, but when using `puma`, there is still backtrace printed to STDERR.

The below code demonstrates it easily - run it once to occupy the port, and run it again in another terminal session to see the error.

### Sample code

```ruby
require 'bundler/inline'

gemfile do
  gem 'sinatra', require: false
  
  # Commenting this line makes it work without printing the backtrace
  gem 'puma',    require: false
end

require 'sinatra/base'

class Server < Sinatra::Application
  get('/') { 'hello' }
end

begin
  Server.run!
rescue => e
  puts "== ERROR: #{e.message}"
  exit 1
end
```

### Output

```
$ ruby sinatra.rb
== Sinatra (v2.0.4) has taken the stage on 4567 for development with backup from Puma
Puma starting in single mode...
* Version 3.12.0 (ruby 2.5.0-p0), codename: Llamas in Pajamas
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:4567
== Someone is already performing on port 4567!
== ERROR: undefined method `stop' for nil:NilClass
Traceback (most recent call last):
        3: from /store/gems/ruby-2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1545:in `block in setup_traps'
        2: from /store/gems/ruby-2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1439:in `quit!'
        1: from /store/gems/ruby-2.5.0/gems/puma-3.12.0/lib/puma/launcher.rb:147:in `stop'
/store/gems/ruby-2.5.0/gems/puma-3.12.0/lib/puma/single.rb:27:in `stop': undefined method `stop' for nil:NilClass (NoMethodError)
```

### Output without puma (as expected, no backtrace)

```
$ ruby sinatra.rb
[2018-10-23 13:33:44] INFO  WEBrick 1.4.2
[2018-10-23 13:33:44] INFO  ruby 2.5.0 (2017-12-25) [x86_64-linux]
== Someone is already performing on port 4567!
== ERROR: Address already in use - bind(2) for 127.0.0.1:4567
```

Is there something that can be done in Sinatra? Or will this require a change in the puma gem itself?

**Comment by dentarg** [comment]
@DannyBen have you tried explicitly rescuing `Exception` in your code?

https://docs.ruby-lang.org/en/2.4.0/syntax/exceptions_rdoc.html

> By default, StandardError and its subclasses are rescued.

**Comment by DannyBen** [comment]
Yes, same result. Try the code, my guess is it will behave the same on your machine as it does on mine (its all self contained in that sample code).

I think this is an issue, with two levels of severity:

1. I think there should be a way for me to rescue errors, no matter what server I use as a backend. Right now, I cannot seem to be able to do so with puma (although I may be wrong, and there *is* a way).
2. I would love it if Sinatra would throw a standardized exception (say `SinatraError::PortAlreadyInUse`) when it encounters an error it already understands (like in this case), making it easier to rescue only what I want to rescue, and leave the other errors in tact.

On top of that - regardless if you accept the statements above or not - it seems like there is a difference in behavior between puma and the other servers, which I am guessing is not intentional, and should probably be addressed one way or the other, for consistency.

Of course, I may be wrong, but it looks like Sinatra is calling `#stop` when it shouldn't.

I have tried debugging it myself, to see if I can be more useful here, but so far without good results.

**Comment by jkowens** [comment]
It looks like there is an open issue for Puma about this. See https://github.com/puma/puma/issues/1523.

**Comment by DannyBen** [comment]
These are good news, thanks for referencing. I see there is a relatively fresh PR that fixes it, so hopefully they merge soon. I am closing this issue then, nothing to do but wait I guess.
