### ISSUE TITLE
Erubi support

### ISSUE THREAD

**Issue by namusyaka** [sinatra/sinatra#1487]
As discussed at #1475 , the [erubi](https://github.com/jeremyevans/erubi) gem has been released and it's adopted in rails.
Of course we can use `erubi` on Sinatra by installing the gem because `tilt` will automatically enable `erubi` as an ERB template engine.

However I think we can support the erubi explicitly like `erubis`. If this issue is reasonable, we will work on the docs, testing, and the sinatra-contrib library.

Please let me know if you're interested in working on the issue.

**Comment by tkmru** [comment]
I'm interested in it, I'll work on this issue.

**Comment by namusyaka** [comment]
@tkmru No worry, go ahead!
