### ISSUE TITLE
URL Parameter question

### ISSUE THREAD

**Issue by resistorsoftware** [sinatra/sinatra#1496]
With old Sinatra, I was used to arrays passed as ?ids=1&ids=2&ids=3 and having a parameter ids which was an array with [1,2,3]

Lately bumping to whole new stack with Sinatra 2, I am seeing problems where someone decided to change sending parameters to the PHP style of ?ids[]=1&ids[]=2&ids[]=3

Now instead of seeing [1,2,3] I am seeing [[1],[2],[3]] which makes me want to scream... I was pretty sure Sinatra was smart enough to convert ids[]=1&ids[]=2 to [1,2] but apparently not... is there something in the configuration I can do to go to a handling more in-line with what I used to see?

**Comment by jkowens** [comment]
I'm fairly certain Sinatra works as you were expecting. A query string of `ids[]=1&ids[]=2&ids[]=3` will result in `['1', '2', '3']` for `params[:ids]`.

Try an example app:

```
require 'sinatra'

get '/test' do
  params[:ids].inspect
end
```

`curl -g 'http://localhost:4567/test?ids[]=1&ids[]=2&ids[]=3'`

**Comment by resistorsoftware** [comment]
Examining my logs.. I extracted this, hence the reason for my issue:

    GET path="/print/addresses?ids%5B%5D%5B%5D=660283686983&ids%5B%5D%5B%5D=660198654023

    params.inspect: { "ids"=>[["660283686983"], ["660198654023"]] }

    params: [["660283686983"], ["660198654023"]]

I notice the sender is wrapping each item in double square brackets... in this case, so ids[][]=1 resulting in [[1]]. The reality from the URL of the sender differs though. What I see there, the origin of the call is:

    /print/addresses?ids%5B%5D=661071364167&ids%5B%5D=661001142343

So that would be a correct parameter ids = [661071364167,661001142343]  from Sinatra. So the challenge is for me to figure out where this doubling of brackets is happening!

**Comment by resistorsoftware** [comment]
The source of the problem lies outside Sinatra.
