### ISSUE TITLE
undefined local variable or method `running_server'

### ISSUE THREAD

**Issue by yegor256** [sinatra/sinatra#1498]
I'm getting this message sometimes, when calling `Front.quit!`:

```
running_server?': undefined local variable or method `running_server' for Front:Class (NameError)
Did you mean?  running_server=
               running_server?
	from /Users/yegor/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1472:in `running?'
	from /Users/yegor/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1437:in `quit!'
	from /Users/yegor/.rvm/gems/ruby-2.3.3/gems/sinatra-2.0.4/lib/sinatra/base.rb:1545:in `block in setup_traps'
```

I'm using Thin. I belive, it's some sort of a bug.

**Comment by namusyaka** [comment]
Couldn't reproduce your issue. Please provide minimal code with Gemfile for reproducing it.

**Comment by jkowens** [comment]
Closing due to age and lack of activity.

**Comment by lukaszlenart** [comment]
I got exactly the same problem on 2.1 and 2.2, it's a bit random behaviour and it's only happen when running with rspec

```
== Sinatra has ended his set (crowd applauds)

Traceback (most recent call last):
	3: from /Users/lukaszlenart/.rvm/gems/ruby-2.6.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1595:in `block in setup_traps'
	2: from /Users/lukaszlenart/.rvm/gems/ruby-2.6.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1487:in `quit!'
	1: from /Users/lukaszlenart/.rvm/gems/ruby-2.6.3/gems/sinatra-2.2.0/lib/sinatra/base.rb:1522:in `running?'
(eval):1:in `running_server?': undefined local variable or method `running_server' for WebhookServer:Class (NameError)
Did you mean?  running_server?
               running_server=
```

```
gem 'rspec', '~> 3.10'
gem 'sinatra', '~> 2.2'
```

**Comment by dentarg** [comment]
`quit!` is called in `at_exit`: https://github.com/sinatra/sinatra/blob/v2.2.0/lib/sinatra/base.rb#L1593-L1606

https://github.com/sinatra/sinatra/blob/44ce685218a29a58ea059b3dfd1a39db8c7dd6d5/lib/sinatra/base.rb#L1593-L1606

I wonder if it would make a difference if `set :running_server, server` was called before `setup_traps` was:

https://github.com/sinatra/sinatra/blob/44ce685218a29a58ea059b3dfd1a39db8c7dd6d5/lib/sinatra/base.rb#L1580-L1581

In any case, it would be helpful @lukaszlenart if you could share a minimal example that reproduces this (even if it only happens sometimes)
