### ISSUE TITLE
Use of @env causes "IndexError: string not matched" while handling an error

### ISSUE THREAD

**Issue by japex** [sinatra/sinatra#1503]
Suppose the following app works fine:

```
require 'sinatra'

get '/' do
  @env = 'development'
  'Hello world!'
end
```

If you change the code as follows, forgetting require 'haml',

```
require 'sinatra'

get '/' do
  @env = 'development'
  haml :index
end
```

you get the folowing error.

IndexError: string not matched
file: gems/sinatra-2.0.4/lib/sinatra/base.rb, location: []=, line: 1114

Looks like @env in base.rb is overwritten with 'development' and causes the error while handling the require error.
Is use of @env is prohibited, or is it a bug?

The execution environment is as follows.

```
$ ruby -v
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
$ bundle list
Gems included by the bundle:
  * bundler (1.16.2)
  * mustermann (1.0.3)
  * rack (2.0.6)
  * rack-protection (2.0.4)
  * shotgun (0.9.2)
  * sinatra (2.0.4)
  * tilt (2.0.9)
```

Thank you in advance.

**Comment by jkowens** [comment]
Yes, it looks like overwriting `@env` is off limits. Along with that instance variable, it appears Sinatra also defines the following in the `Base` class:
```
@current_engine
@default_layout
@preferred_extension
@app
@template_cache
@params
@request
@response
```

**Comment by namusyaka** [comment]
As @jkowens said, you shouldn't overwrite sinatra's original instance variables.
Closing this as not sinatra issue.
