### ISSUE TITLE
Add Crew page

### ISSUE THREAD

**Issue by namusyaka** [sinatra/sinatra#1509]
Currently, our `Crew` link will route to [github contributors page]( https://github.com/sinatra/sinatra/graphs/contributors). However, I think that we can introduce the team that is the core of sinatra we possess.
By doing so, we can clarify who is working on development with ownership in sinatra, and can expect to facilitate to the contribution inside the community.

I would like to hear your opinions.

**Comment by jkowens** [comment]
I really like this idea 💯 

It would be nice to know who is actively involved in maintaining Sinatra and what roles need filled.

**Comment by namusyaka** [comment]
In order to implement this idea, we also need to think about following points:

- Page Design (Is there someone who wants to design this page?)
- Implementation idea (Can we use `AUTHORS.md` as a source?)
  - We need to reduce the cost of the maintenance even if this idea has been approved.
- Confirm that there are no people who do not want to be shown on this page

I'd continue to welcome your opinion on this idea.

**Comment by kgrz** [comment]
I can work on the design next month. But intend to keep that slot open if anyone beginner wants to work on it.

**Comment by namusyaka** [comment]
@kgrz Great!

**Comment by namusyaka** [comment]
@kgrz Any progress on this?
