### ISSUE TITLE
Release Automation

### ISSUE THREAD

**Issue by namusyaka** [sinatra/sinatra#1510]
In order to reduce the cost of maintenance for sinatra and improve contributors experience, we'd like to automate for each patch-level releases.
If a commit is pushed to the master branch, new patch-level release is automatically created.

This feature will be consist of:

- Github Label Management
  - For example, it's strange that new patch version is released only by correcting typos.
  - We need to control it by attaching a label to release the patch version to the PR.
- Requirements
  - automation script will do the following items if feature or bug-fixes are merged:
     - Update CHANGELOG
     - Bump `VERSION` to new version
     - Execute the `rake release` task.
  - the script will be triggered by travis

**Comment by namusyaka** [comment]
Creating...: @sinatra-bot

**Comment by dentarg** [comment]
I think it is more effort to automate the creation/updating of release notes / changelog than it is to do it by hand. It is not that much happening, that need to go into the changelog (most changes relate to tests and CI really).

It would be nice to automate `gem build` and `gem push`, especially as there's 3 gems that should be released at the same time with the same version. Are you open to that idea @zzak @jkowens?

**Comment by jkowens** [comment]
@dentarg yeah I agree. The existing rake release task works pretty well for releasing all three gems.

**Comment by dentarg** [comment]
I guess we could close then. I was thinking publishing from CI but we could pick that up when there's something like https://github.com/github/roadmap/issues/657 but for RubyGems.

**Comment by dentarg** [comment]
> If a commit is pushed to the master branch, new patch-level release is automatically created

We are not going to do this :) It is a bit excessive

**Comment by dentarg** [comment]
Closing in favour of https://github.com/sinatra/sinatra/issues/1920
