### ISSUE TITLE
why specify :locals when passing variables?

### ISSUE THREAD

**Issue by gartha1** [sinatra/sinatra#1525]
This is a question about the design choice behind the signature of the erb method. It seems superfluous to have to say :locals. And it's a bit unintuitive since it doesn't seem necessary.

I notice that one can do

get '/' do
erb :index, {:locals => {:aaa=>"bbabb"}}
end

(I've included the curly braces on the last parameter just for clarity).

and of that hash  {:locals => {:aaa=>"bbabb"}}

I understand that that creates a hash called locals   locals[:aaa] . and locals[:bbb]

accessed in the ERB with lines like 

<%= "#{locals[:aaa]}"  %> . or . <%= locals[:aaa]  %>

The :locals part of the hash passed to the erb method, seems strange to me, because it's not what the programmer chooses the name to be.

If in my .rb file, I were to change :locals to :localsz  then in the ERB file if I say   localsz[:aaa] it doesn't work.   

So why not instead of  erb :index, {:locals => {:aaa=>"bbabb"}}

have

erb :index, {:aaa=>"bbabb"}

the ERB file would still say . <%= locals[:aaa] %> .   or  <%= "#{locals[:aaa]}" %> . 

It seems like the erb method is always making a hash called locals. And not a hash of another name. So it seems there is no choice but to refer to one's variables through the hash called locals. So it seems superfluous to pass the erb method a symbol :locals, denoting the name of the hash it will create.

Maybe i'm making some error, but if I try to get ERB to put a dictionary representing variables and their values, in a hash called anything other than :locals, then I try to refer to that hash in the ERB file, I get an error.

**Comment by jkowens** [comment]
It looks like there are two ways to pass `locals` to your erb template:

```
erb :index, locals:  {aaa: "bbabb"}
```

or

```
erb :index, {},  aaa: "bbabb"
```

The second argument to the `erb` method is an options hash. That is why the `:locals` key is necessary. The third argument is a locals hash. See https://github.com/sinatra/sinatra/blob/6f15fba2790ebdf4d1215cebf425dea2ea3130ea/lib/sinatra/base.rb#L681

https://github.com/sinatra/sinatra/blob/6f15fba2790ebdf4d1215cebf425dea2ea3130ea/lib/sinatra/base.rb#L816

**Comment by gartha1** [comment]
ah I see, thanks, http://sinatrarb.com/intro.html . 

Templates take a second argument, the options hash:

(I think it means the template language's rendering method, when taking two arguments, the second argument is an options hash) 

Then it lists available options, one is locals, and there are others

Available Options:

locals
List of locals passed to the document. Handy with partials. Example: erb "<%= foo %>", :locals => {:foo => "bar"}

default_encoding
String encoding to use if uncertain. Defaults to settings.default_encoding.
....
content_type
Content-Type the template produces. Default depends on template language.
....

So that'd explain it, it's to distinguish it from other options.
