### ISSUE TITLE
[Documentation] Sinatra tricks and tips, contributed by sinatra-users

### ISSUE THREAD

**Issue by rubyFeedback** [sinatra/sinatra#1530]
I would like to propose an addition to:

http://sinatrarb.com/documentation.html

In particular I would be interested in a tricks or tips collection, e. g. useful tidbids.

I am presently learning sinatra and I am already using it. However had, there is a lot I don't know, and I only learn step by step, little by little (I know a lot about ruby though).

For me it would be most helpful if we would have some resource to which we could contribute - and read information. A bit like the wiki at github, but more prominently placed at the official sinatra homepage, and ideally also curated by people who know sinatra, every now and then.

I am not sure how likely this is to add it, but I wanted to mention it nonetheless - please feel free to disregard this issue if it is too much work or would not provide sufficient benefit. (I am aware that there is a LOT of content available in tutorials that I have not yet read, but I really need short snippet-info so that I can learn in small steps; in the long tutorials I often quit after some time due to lack of time or losing focus, which tends to happen for me a lot since I multitask immensely, unfortunately).

**Comment by jkowens** [comment]
This is a nice idea, but based on the current level of interest in contributing to this project, I don’t see this getting off the ground. I’m closing, but if anyone feels strongly about this or is willing to take the lead, let me know.
