### ISSUE TITLE
[Documentation] Sinatra reloader

### ISSUE THREAD

**Issue by rubyFeedback** [sinatra/sinatra#1534]
I am reading this link right now:

http://sinatrarb.com/contrib/reloader

Would it be possible to extend this documentation slightly, e. g. by adding a complete stand-alone example, and explaining how to use it?

Sorry for these newbie questions but I am still only slowly learning sinatra; that takes some time.

I understand that a reloader helps reload/restart the server (I suppose) upon a change, or something like this - but I haven't quite fully understood this yet, which is why I'd like to see this documentation be improved. Thanks!

**Comment by SwagDevOps** [comment]
Should use [rerun](https://github.com/alexch/rerun).

**Comment by dentarg** [comment]
Or deprecated `sinatra/reloader`?
