### ISSUE TITLE
Passing variable between scopes

### ISSUE THREAD

**Issue by gklueh** [sinatra/sinatra#1536]
I am trying to capture the pid (Process ID) from an external ruby script executed from within sinatra, and kill it via a cancel button in my app. I am attempting to do this as follows:

**My "before scope**
before do
    @processPID = 0 
end

**My First "get" scope**
get "/startAll" do
    pipe = IO.popen("ruby content/scripts/api.rb --name=test_suite_full_api 2>&1 &")
    @processPID = pipe.pid
    puts @processPID
    wasGoodAPI = pipe.readlines
    pipe.close
    allGood = wasGoodAPI
end

**My Second "get" scope**
get "/cancelAll" do
    puts @processPID
    if @processPID != 0
        puts @processPID
        wasKilled = `kill -9 #{@processPID}`
    end
end

I have defined my variable in a "before" scope (@processPID = 0). I then update the variable successfully in my first "get" scope ("/startAll") which prints out the expected pid. I then pass this @processPID variable to the second "get" scope ("/cancelAll"), all in the same sinatra file, _**but @processPID seems to revert back to 0**_, the initial variable defined in the "before" scope. I am looking to have the variable set in the first "get" scope passed into the second "get" scope, so I can effectively kill that process only, without killing all of ruby. I have tried all variable types.

**Comment by dentarg** [comment]
You need to store the PID somewhere were it survives the request cycle ([this answer](https://stackoverflow.com/questions/8281645/is-a-new-instance-of-sinatra-started-on-every-request) might help understand this)

https://github.com/steveklabnik/request_store is a useful gem for that

**Comment by gklueh** [comment]
Thanks @dentarg -  I attempted to implement the "request_store" gem however it feels like the request is not being stored correctly in this request_store, as I am still getting 0, or whatever I declare in the "before" block (now -1). It's like its not being stored and the "before" block is resetting it before each new scope. And if I comment out the initial store in the "before" block, it sets RequestStore.store[:PID] in the "cancelALL" block to nil.

**My updated code:**

**I added to top of file**
require 'request_store'

**Added to bottom of file**
use RequestStore::Middleware

**Updated Routes**
before do
 RequestStore.store[:PID] ||= -1
end

get "/startAll" do
    puts RequestStore.store[:PID]
    pipe = IO.popen("ruby content/scripts/api.rb --name=test_suite_full_api 2>&1 &")
    RequestStore.store[:PID] = pipe.pid
    puts pipe.pid
    wasGoodAPI = pipe.readlines
    pipe.close
    allGood = wasGoodAPI
end

get "/cancelAll" do
    puts RequestStore.store[:PID]
    if RequestStore.store[:PID] > 0
        puts RequestStore.store[:PID]
        wasKilled = `kill -9 #{RequestStore.store[:PID]}`
    end
end

**Output:**
-1
13027
-1

**Comment by dentarg** [comment]
Why do you think you need the before block and the code in there?

**Comment by gklueh** [comment]
Initially I thought it would set the variable before anything else ran. And when I remove the before block, and put the code that was in it outside of it (under my require), I also get the same output result.

**Comment by jkowens** [comment]
To share variables between requests, I think you'll need to store the data somewhere (database, filesystem, etc).

For instance you can do the following to store the pid on the filesystem. You will have to add code to manage deleting the pid file when appropriate.

In `/startAll`:
```
File.open(PID_FILE, 'w') { |file| file.write(pipe.pid) }
```
In `/cancelAll`:
```
pid = File.read(PID_FILE)
```

**Comment by dentarg** [comment]
@gklueh sorry, I don't know what I was thinking 🤦‍♂️ forget my advice about request store, that's also just during the request cycle

Listen to @jkowens 

Redis is an easy to use key value store for use cases like this

**Comment by dentarg** [comment]
If it's okay maybe you could use something in memory too (info will get lost when app is shutdown)

**Comment by gklueh** [comment]
Thanks @jkowens & @dentarg !! I am now able to save and retrieve the pid from the file as indicated... it is however not the pid I expect (i.e. not for the process started via `pipe = IO.popen("ruby content/scripts/api.rb --name=test_suite_full_api 2>&1 &")`), its always 1 or 2 numbers before the pid of this actual process - but that is a new problem to solve I guess :)
