### ISSUE TITLE
Current security contact?

### ISSUE THREAD

**Issue by ChaosData** [sinatra/sinatra#1538]
Hi,

I attempted to send an email to `sinatra-security@googlegroups.com`, per <https://github.com/sinatra/sinatra/blob/master/SECURITY.md>, but I got a bounce reply from `mailer-daemon@googlemail.com` with the following:

```
We're writing to let you know that the group you tried to contact (sinatra-security) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

* You might have spelled or formatted the group name incorrectly.
* The owner of the group may have removed this group.
* You may need to join the group before receiving permission to post.
* This group may not be open to posting.
``` 

If this is still the correct contact address, and, if so, can someone grant posting access to `jeff.dileo@nccgroup.com` so I can resend? Alternatively, can someone confirm if an email sent from that address was, in fact, received?

Thanks.

**Comment by namusyaka** [comment]
I'm a maintainer on this project.
Could you send me the details?
namusyaka@gmail.com

**Comment by ChaosData** [comment]
Can you confirm that you received the email?
