### ISSUE TITLE
Call before block before serving

### ISSUE THREAD

**Issue by daveroberts** [sinatra/sinatra#1542]
I have an application with a before block:

```ruby
before do
  halt 401 if !['/ping','/login','/callback'].include?(request.path_info) && user_logged_in()
end
get '/login' do
  File.read('login.html')
end
set(:public_folder,'public')
```

Right now, files which are in the public folder are served without running the before block.  I want to ensure users are logged in to get these files.  How can I do that?

**Comment by dentarg** [comment]
> I want to ensure users are logged in to get these files. How can I do that?

I think you need to not use the `public_folder` functionality then, and instead serve them yourself (define routes for them).

I think the point of the public folder is to serve static files as quick as possible, and therefore not run any before hooks. I assume Sinatra has had this behaviour for a great while, so it is probably not likely to change. 

It doesn't look like you can customize this behaviour:

https://github.com/sinatra/sinatra/blob/1aa64f9858edc3f93cc8d46e26f724c1ae103b1c/lib/sinatra/base.rb#L1090-L1101
https://github.com/sinatra/sinatra/blob/1aa64f9858edc3f93cc8d46e26f724c1ae103b1c/lib/sinatra/base.rb#L1102-L1112

**Comment by daveroberts** [comment]
Thanks for your reply.  If I wanted to serve the files myself by defining routes, how could I do this (short of naming each file individually?)

**Comment by dentarg** [comment]
You can use http://ruby-doc.org/core-2.4.2/Dir.html#method-c-entries to list files in folder

**Comment by namusyaka** [comment]
@daveroberts You can use `send_file` for use in serving static files with sinatra idioms, it would be something like:

```ruby
require 'sinatra'

Dir['public/**'].each do |file|
  get(file) { send_file(file) }
end
```

**Comment by namusyaka** [comment]
@daveroberts If your question can be resolved by our comments, please close this issue.
