### ISSUE TITLE
FAQ update: Migrations

### ISSUE THREAD

**Issue by thesecretmaster** [sinatra/sinatra#1545]
I was just looking into the FAQ, and I read the section on [migrations](http://sinatrarb.com/faq.html#ar-migrations). While it seems like that code works, I think it'd be really useful to at least point users to the [sinatra-activerecord](https://github.com/janko/sinatra-activerecord) gem. I've been using it for a few years now and it's been great, and is more complete then the solution suggested in the FAQ (also includes all the other db:* operations, handles schema, etc.).

**Comment by kgrz** [comment]
Agreed. Can you open a PR with the changes? May be also link the recipes website (http://recipes.sinatrarb.com/p/databases?#article) which has some more (possibly outdated, albeit) examples

**Comment by namusyaka** [comment]
Closed via https://github.com/sinatra/sinatra.github.com/pull/250
