### ISSUE TITLE
Content-Disposition spacing between parameters

### ISSUE THREAD

**Issue by bencoman** [sinatra/sinatra#1546]
Please excuse me if I'm in the wrong place.  I'm following up an issue I logged at https://github.com/exercism/exercism/issues/4357 (since I believe Exercism is using Sinatra https://github.com/exercism/exercism/pull/3775)

I have a client that sends...
```
Content-Disposition: form-data;name="files[]";filename="myfile.txt"
```
which fails with "500 INTERNAL SERVER ERROR".

Another client works with...
```
Content-Disposition: form-data; name="files[]"; filename="myfile.txt"
```
with the difference being the space after the semi-colon between parameters.
Is that space requirement specified in an RFC somewhere that I can refer developers 
of the non-functional client to?
And/or could Sinatra be permissive about the lack of space? (if that is even the source of the problem)

**Comment by namusyaka** [comment]
Could you provide a minimal example for reproducing your issue?

**Comment by janko** [comment]
If this is coming from a `multipart/form-data` POST request, then this parsing happens in Rack, not in Sinatra.

**Comment by bencoman** [comment]
Thanks. That helped.  I've opened https://github.com/rack/rack/issues/1386
