### ISSUE TITLE
Logger option for lifecycle announcement

### ISSUE THREAD

**Issue by relip** [sinatra/sinatra#1551]
We use Logstash for logging solution and it requires their own log formats. However, Sinatra only prints startup/shutdown log to`$stderr` which no alternative options available on formatting and logging target.

https://github.com/sinatra/sinatra/blob/eee711bce740d38a9a91aa6028688c9a6d74b23b/lib/sinatra/base.rb#L1525
https://github.com/sinatra/sinatra/blob/eee711bce740d38a9a91aa6028688c9a6d74b23b/lib/sinatra/base.rb#L1438
https://github.com/sinatra/sinatra/blob/eee711bce740d38a9a91aa6028688c9a6d74b23b/lib/sinatra/base.rb#L1459

I found [an old PR](https://github.com/sinatra/sinatra/pull/1083) with tagged `2.1.0` that adds the ability to disable LC logs, maybe this feature can be added to that?

**Comment by jkowens** [comment]
It looks like there is already a setting to disable these messages:

#1153

https://github.com/sinatra/sinatra#available-settings (quiet option)
