### ISSUE TITLE
Sinatra::Contrib::ConfigFile should allow *.yaml

### ISSUE THREAD

**Issue by namusyaka** [sinatra/sinatra#1563]
Currently it won't accept that, only `.yml` or `.yml.erb`.
Here is an error message:
```
Invalid config file type, use .yml or .yml.erb (Sinatra::ConfigFile::UnsupportedConfigType)
```

However, as you can see in [kubernetes](https://github.com/kubernetes/examples/blob/5207e2a1c513d199b4ff05c9e534678ae8fc905a/cassandra/image/files/cassandra.yaml), `.yaml` is also known as a valid extension.

If you're interested in sending a patch to sinatra, feel free to submit a PR.

**Comment by jkowens** [comment]
Closed by #1564.
