### ISSUE TITLE
@params are reset to pre-filter state if there are parameters in the filter's path pattern

### ISSUE THREAD

**Issue by DannyBen** [sinatra/sinatra#1567]
Hello,

I am fairly sure this is a bug and not an intended behavior. I may be wrong though.

When amending `@params` from `before` blocks, a different behavior is observed when the `before` filter uses parameters in the path.

This was initially discussed in [this StackOverflow question][1].

## Reproduction steps

Create `test.rb`

```ruby
# test.rb
require 'sinatra'
require 'sinatra/reloader'

set :bind, '0.0.0.0'
set :port, 3000

before            { logger.info "before 1" ; @params['before-1'] = 'yes' }
before('/hi')     { logger.info "before 2" ; @params['before-2'] = 'yes' }
before('/:id/hi') { logger.info "before 3" ; @params['before-3'] = 'yes' }

get('/')       { params.to_json }  # pass
get('/hi')     { params.to_json }  # pass
get('/:id/hi') { params.to_json }  # FAIL
```

Run it:
```
$ ruby test.rb
```

Then access it with these three calls:

```
$ curl localhost:3000/
$ curl localhost:3000/hi
$ curl localhost:3000/123/hi
```

## Actual behavior

The before filters append values to the `@params` hash properly, except in the last case:

```
$ curl localhost:3000/
{"before-1":"yes"}

$ curl localhost:3000/hi
{"before-1":"yes","before-2":"yes"}

$ curl localhost:3000/123/hi
{"before-1":"yes","id":"123"}
```

## Expected behavior

Expecting to have the third `before` filter work as well, and set the value for `@params['before-3']`.

```
$ curl localhost:3000/123/hi
{"before-1":"yes","id":"123", "before-3":"yes"}
```

## Additional information

As was pointed out in [Amadan's answer on StackOverflow][2], the two places in the code that play a part in this are:

https://github.com/sinatra/sinatra/blob/b0081892f1ec9f44e9a0bba6fb154f7e9d7bec86/lib/sinatra/base.rb#L1022

and

https://github.com/sinatra/sinatra/blob/b0081892f1ec9f44e9a0bba6fb154f7e9d7bec86/lib/sinatra/base.rb#L1041

[1]: https://stackoverflow.com/questions/57901075/altering-params-in-sinatra-before-blocks/57906972#57906972
[2]: https://stackoverflow.com/a/57906972/413924

**Comment by jkowens** [comment]
I agree, this looks like a bug. We need to remove routing params from the `@params` hash without losing other key/value pairs that could have been added.

**Comment by horaciob** [comment]
Hi there I've added a test for this scenario, @jkowens PR makes test runsuccessfully.
