### ISSUE TITLE
[Installation] Sinatra gem install hangs at ri documentation

### ISSUE THREAD

**Issue by rubyFeedback** [sinatra/sinatra#1578]
Whenever I try to install the sinatra gem, the first install hangs during:

"Installing ri documentation for sinatra-2.0.7"

I manually interrupt it, then do it again, and then it works.

I have no idea what causes it, but all the other gems and their ri
documentation do not have this issue.

I believe that there must be something special for sinatra documentation
done that causes this behaviour since I do not see it at any other gem.

It may be difficult to find out, but I am just reporting here to let you guys
know anyway.

**Comment by horaciob** [comment]
Hi there.

Here are the steps to reproduce it.

```
rvm gemset create sinatra_ri
rvm use ruby-2.6.3@sinatra_ri
gem install sinatra
```
It's something that also happens with version  < 2.0.0 and i've tried with ruby 2.6.3 2.5.4 and 2.3.4

**Comment by ty-shaikh** [comment]
Temporary fix could be to use: `gem install sinatra --no-ri --no-rdoc` or `gem install sinatra --no-document` if Ruby is newer than version 2.5

**Comment by aaronelliotross** [comment]
+1 this bit me too

**Comment by epergo** [comment]
This was already fixed in https://github.com/sinatra/sinatra/pull/1671 however we haven't released any new version recently so you will only notice the improvement if you use master.
