### ISSUE TITLE
Prevent logging access to a route

### ISSUE THREAD

**Issue by scalp42** [sinatra/sinatra#1582]
Hi folks,

We have a simple route `/ping and we'd like to prevent logging access to it.

What is the recommended way to do that?

Thank you in advance

**Comment by jkowens** [comment]
I haven't tested this but take a look at [silencer](https://github.com/stve/silencer). Depending on how you configure your app Rack may be adding logging middleware.

See: https://stackoverflow.com/questions/30471322/disable-sinatra-standard-output

If you make sure CommonLogger is disabled, and then use Silencer I think you might be good.

**Comment by scalp42** [comment]
I think the challenge is to be able to suppress the access logs per route instead of globally.

**Comment by jkowens** [comment]
Per the Silencer readme:

> Silencer is a simple rack-middleware for Rails that can selectively disable logging on per-action basis. It's based on a blog post by Dennis Reimann.

Being Rack middleware, I think it should work with SInatra as well.

This is a Rack example from the readme:

```
require 'silencer/logger'

use Silencer::Logger, :silence => ["/noisy/action.json"]
```

**Comment by jkowens** [comment]
Hm, so that very well might not work for you. You might reach a bigger audience for this question on StackOverflow. I'm guessing someone has come across this before.

**Comment by jkowens** [comment]
@scalp42 we've just merged in a new feature to master. I think you might be able to use this to prevent logging to your ping route. Can you check and let me know if this will work?

https://github.com/sinatra/sinatra/blob/master/sinatra-contrib/lib/sinatra/quiet_logger.rb

See also: https://github.com/sinatra/sinatra/pull/1250

**Comment by scalp42** [comment]
Awesome @jkowens! thanks a lot, I'll give it a try by hopefully end of month but I'm assuming we should be able to close this issue now.

Thanks again.

**Comment by scalp42** [comment]
@jkowens any idea how to use it when not using a modular app?
