### ISSUE TITLE
sinatra/reloader: Warnings with Ruby 2.7

### ISSUE THREAD

**Issue by DannyBen** [sinatra/sinatra#1587]
Testing with Ruby 2.7.0-rc2 (which is the currently latest available with RVM), I am getting some warnings when `sinatra/reloader` is required.

### Code to reproduce

```ruby
# test.rb
require 'sinatra'
require "sinatra/reloader"

set :bind, "0.0.0.0"
set :port, 3000

get '/' do
  'Hello world!'
end
```

### Output

```
$ ruby test.rb
/store/gems/ruby-2.7.0-rc2/gems/sinatra-contrib-2.0.8.1/lib/sinatra/reloader.rb:
308: warning: The last argument is used as keyword parameters; maybe ** should b
e added to the call
/store/gems/ruby-2.7.0-rc2/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1360: warnin
g: The called method `add_filter' is defined here
/store/gems/ruby-2.7.0-rc2/gems/sinatra-contrib-2.0.8.1/lib/sinatra/reloader.rb:275: warning: The last argument is used as keyword parameters; maybe ** should be added to the call
/store/gems/ruby-2.7.0-rc2/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1622: warning: The called method `compile!' is defined here
== Sinatra (v2.0.8.1) has taken the stage on 3000 for development with backup from Puma
Puma starting in single mode...
...
```

### Versions

```
$ gem list sinatra
sinatra (2.0.8.1)
sinatra-contrib (2.0.8.1)

$ ruby -v
ruby 2.7.0rc2 (2019-12-22 master 75acbd5f00) [x86_64-linux]
```

### Offending code

https://github.com/sinatra/sinatra/blob/a4dd24add24f2dd0e7299b9e68e12038138294d3/sinatra-contrib/lib/sinatra/reloader.rb#L272

and

https://github.com/sinatra/sinatra/blob/a4dd24add24f2dd0e7299b9e68e12038138294d3/sinatra-contrib/lib/sinatra/reloader.rb#L305

I can confirm that changing both `options = {}` to `**options` removes the warnings.
I wanted to submit a PR, but running tests (even before the change) triggers tons of warnings and errors.

**Comment by jkowens** [comment]
Fixed by #1586
