### ISSUE TITLE
rake db:migrate not working when using ActiveRecord with Sinatra

### ISSUE THREAD

**Issue by jonathonpday** [sinatra/sinatra#1591]
I am trying to create a very basic Sinatra app which users only Active Record and Sqlite3.

I have created a `Rakefile` which contains the following:

`require "./wadapp.rb"`                                                                                
  `require "sinatra/activerecord/rake"`

my main app file contained the following:

`require 'sinatra'`                                                                                   
`require 'sinatra/activerecord'`
`set :bind, '0.0.0.0'`
   
   `ActiveRecord::Base.establish_connection(`
     `:adapter =>'sqlite3'`
     `:database=>'wiki.db'`
  ` )`
   
  `class User < ActiveRecord::Base`
   ` validates :username, presence: true, uniqueness: true`
    `validates :password, presence: true`
`  end`

when I run `rake db:create_migration NAME=create_users` then a migration file is created in `db/migrate/`, I amend that file to the following:
```
class CreateUsers < ActiveRecord::Migration[6.0]                                                         
  def change
    create_table :users do |t| 
      t.string :username
      t.string :password
      t.boolean :edit
      t.timestamps null: false
    end 
    User.create(username: "Admin", password: "admin", edit: true)
  end 
end
```
However, When I finish and exit this file and run `rake db:migrate` nothing happens. The only output (when within the `migrate` directory) is `(in /Users/username/ruby/wiki/app)`

Whenever I run th application and tru to create a new record I am told the table does not exist. Can anyone advise on how to proceed with this?

**Comment by jkowens** [comment]
Perhaps more help would be available at [sinatra-activerecord](https://github.com/sinatra-activerecord/sinatra-activerecord) or on StackOverflow.
