### ISSUE TITLE
Web-app sometimes hangs during http-request 

### ISSUE THREAD

**Issue by ArtemVarnavskiy** [sinatra/sinatra#1612]
ruby version: 2.5.0
sinatra: 2.0.7
webrick: 3.4.0; puma: 4.3.3
OS: Windows Server 2016
run app with config.ru 

My web-app sometimes hangs during http-request. 
Only helps a key combination "CTRL+C" in CMD.
I tried to start servers Webrick and Puma.
I don't know what the problem is. I need help.

logs in cmd with webrick:
![image](https://user-images.githubusercontent.com/50958354/78276707-17f9c380-751c-11ea-83e9-838e8c111c7a.png)

**Comment by jkowens** [comment]
@ArtemVarnavskiy have you tried a newer Ruby?

**Comment by ArtemVarnavskiy** [comment]
@jkowens Yes. I tried version Ruby 2.6.6-1. Вut it didn't help!

**Comment by jkowens** [comment]
@ArtemVarnavskiy how often do you see this happening?  Can you provide a very basic app that could be used to reproduce this issue? I'd have to see if I can get on a Window server to investigate.

**Comment by dentarg** [comment]
@ArtemVarnavskiy did you look into the issue Nate pointed out in https://github.com/puma/puma/issues/2217#issuecomment-610625207?

**Comment by pynkdy** [comment]
#

**Comment by ArtemVarnavskiy** [comment]
@jkowens I found a solution to the problem. The problem was in cmd.exe. I started web-app using bash and the problem didn't appear again.
Thanks for your help anyway

**Comment by jkowens** [comment]
@ArtemVarnavskiy interesting, thanks for the update. It would be nice to get that issue figured out sometime.

**Comment by ArtemVarnavskiy** [comment]
@jkowens The problem is reproduced only on my work computers (windows 10 and windows server). On my personal computer (windows 10) the problem does not reproduce.

**Comment by dentarg** [comment]
I think this should be closed, doesn't look like a very common problem we need to spend our precious time on
