### ISSUE TITLE
[rack-protection] Consider renaming `origin_whitelist` to something else

### ISSUE THREAD

**Issue by rhymes** [sinatra/sinatra#1620]
Following the example of https://github.com/rails/rails/issues/33677 and https://github.com/thepracticaldev/dev.to/issues/7147 I'm proposing to take into consideration the replacement of the parameter `origin_whitelist` in `Rack::Protection::HttpOrigin` with something else.

Possible alternatives: `allow`, `valid`, `permitted`.

According to a quick search - https://github.com/sinatra/sinatra/search?q=whitelist&unscoped_q=whitelist - in the entire Sinatra code base, that's the only instance.

A possible solution would be to add an alternative parameter and a deprecation notice for the existing one and then remove the latter a couple of releases down the line or something like that.

I can work on the initial PR if agreed.

Thank you!

**Comment by jkowens** [comment]
@rhymes sounds like a good plan. My initial thought is that `permitted` is a good replacement. Your help would be greatly appreciated!

**Comment by rhymes** [comment]
@jkowens thanks for the availability. I sent a PR in https://github.com/sinatra/sinatra/pull/1625 but it failed in most of the builds and I think it's unrelated to the code change but as I'm unfamiliar with sinatra and rack-protection it might be entirely my fault. I tried reading the contributing guide but found nothing that could related. 

Could you take a look? Thank you!
