### ISSUE TITLE
Question: streams as websockets?

### ISSUE THREAD

**Issue by mistergibson** [sinatra/sinatra#1621]
So, I'd like to support websockets, but the closest thing I've found is a 'stream' in contrib. Anyone have tutorial code that lets me use streams for websocket ops?

Now, if I used eventmachine I would have an option - but I don't. My use case calls for, believe it or not, WEBrick under JRuby. There is a webrocket gem, but I didn't want to get into the dark arts just yet -- if a sinatra-baked-in solution existed. Any advice welcome.

Thanks in advance.

**Comment by badger-craftmanship** [comment]
Since sinatra uses rake I really think that, you should be to be able to make it communicate or something like a cast just  to communicate to the web socket
[Rack repo](https://github.com/rack/rack)

**Comment by jkowens** [comment]
@mistergibson sorry no baked in solution. Using persistent connections with Sinatra requires using EventMachine and an app server like Thin or Rainbows.
