### ISSUE TITLE
drop thin support

### ISSUE THREAD

**Issue by namusyaka** [sinatra/sinatra#1624]
As per https://github.com/rack/rack/commit/98d9cf5834d4e27e34bbaa017cdfc68795763b55, it's time to drop the support for thin.
Does anyone want to take this issue?

**Comment by rkmathi** [comment]
@namusyaka Hi
I fixed it to try in #1627.
If I'm wrong, I'd be happy to let you know.

**Comment by matti** [comment]
I *never* managed to get streaming work with puma, only with thin. Worried.

**Comment by namusyaka** [comment]
I guess the rainbows can handle the streaming feature. See #1627

**Comment by esparta** [comment]
May I propose to re-open this issue in order to link the update of documentation on different languages?
once all the docs are done, close it?

**Comment by dentarg** [comment]
@esparta I would suggest creating a new issue about the docs (easier to understand what's need to be done then)

**Comment by namusyaka** [comment]
As I noted in https://github.com/sinatra/sinatra.github.com/pull/274, we'll wait and see what happens around rack/thin for making a decision on what server should be choosed. This indicates there is a possibility of reverting #1627 partially (In any case the integration test with rainbows can be helpful).

**Comment by namusyaka** [comment]
We'll use rainbows in our development environment, but I restored thin support in https://github.com/sinatra/sinatra/pull/1622/commits/342758a67b05a6e2192b7ee133912b10d81bdeec because of https://github.com/macournoyer/thin/commit/b201525f0db7d7e9faf26681b68646e0be9f96ec.
However, in order to use thin with sinatra smoothly, https://github.com/macournoyer/thin/pull/369 should be merged.
