### ISSUE TITLE
Sinatra 2.0.9 release

### ISSUE THREAD

**Issue by mauro-oto** [sinatra/sinatra#1633]
Projects using the latest 2.0.8.1 Sinatra release from January 1st are still showing Ruby 2.7 related warnings (see https://github.com/sinatra/sinatra/pull/1586).

A 2.0.9 release that includes fixes for those would be great to have since we're now more close to Ruby 2.8/3.0 than we are to 2.7. 

Could you please consider cutting a release? Thank you! 🙏

**Comment by namusyaka** [comment]
We're planning to cut v2.1.0 release soon. Stay tuned.

**Comment by namusyaka** [comment]
Released: https://rubygems.org/gems/sinatra/versions/2.1.0
