### ISSUE TITLE
falcon support

### ISSUE THREAD

**Issue by namusyaka** [sinatra/sinatra#1639]
https://github.com/socketry/falcon

**Comment by ceclinux** [comment]
Anyone doing this currently? I am interested in adding falcon support

**Comment by horaciob** [comment]
Hi all,

I've added this [pr](https://github.com/sinatra/sinatra/pull/1677) Not sure if we have to do something else, but it works on local.

**Comment by horaciob** [comment]
Looks like they had some issues related with graceful [restart](https://github.com/socketry/falcon/issues/114) and [shutdown](https://github.com/socketry/falcon/issues/71), but let me some days to see what we can do
