### ISSUE TITLE
[rack-protection] origin_whitelist results in ArgumentError for rack-protection 2.1.0

### ISSUE THREAD

**Issue by takeshi-yashiro** [sinatra/sinatra#1641]
After upgrading rack-protection from 2.0.8 to 2.1.0, the following error is caused:
```
ERROR -- : app error: wrong number of arguments (given 1, expected 2) (ArgumentError) 
ERROR -- : /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:58:in `warn' 
ERROR -- : /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/http_origin.rb:37:in `accepts?'
...
```
when origin_whitelist option is specified.

It seems that this problem is caused by the lack of `env` parameter passed to `warn` method at https://github.com/sinatra/sinatra/blob/master/rack-protection/lib/rack/protection/http_origin.rb#L37 , as `warn` method requires two arguments:  https://github.com/sinatra/sinatra/blob/master/rack-protection/lib/rack/protection/base.rb#L58

**Comment by jkowens** [comment]
Oh goodness, not sure how we missed that 😬 

Would you mind sending up a PR to pass long the `env` as well? I think adding a test to make sure `origin_whitelist` is still working would be beneficial as well.

https://github.com/sinatra/sinatra/blob/166da3084d5532fdc5d9676e2df0f11259b94594/rack-protection/spec/lib/rack/protection/http_origin_spec.rb#L38
