### ISSUE TITLE
Is the current stable version of Sinatra the 1.4 series?

### ISSUE THREAD

**Issue by thibauds** [sinatra/sinatra#1643]
Or should it be the 2.1 series and [this file](https://github.com/sinatra/sinatra/blob/master/MAINTENANCE.md#stable-release) is outdated?

**Comment by dentarg** [comment]
That file looks very outdated, yes

**Comment by thibauds** [comment]
Thank you.

**Comment by jkowens** [comment]
@namusyaka I wasn't aware that there was a [maintenance policy](https://github.com/sinatra/sinatra/blob/master/MAINTENANCE.md). Should we update the `stable` branch and follow that procedure or is it unnecessary?

**Comment by eddietejeda** [comment]
The `stable` branch has not been updated since 2017. https://github.com/sinatra/sinatra/tree/stable

What's required to consider 2.x as the stable branch?

**Comment by jkowens** [comment]
We can probably force push master or the v2.1.0 tag onto stable. We've basically been treating the master branch as stable.

**Comment by froderik** [comment]
I made a shot at updating the docs based on the above. PR [here](https://github.com/sinatra/sinatra/pull/1681)

**Comment by dentarg** [comment]
v2.1.0 should be considered the current stable version :) 

@jkowens can we close this issue?

**Comment by jkowens** [comment]
I think so!
