### ISSUE TITLE
content_type ignored after 2.1.0

### ISSUE THREAD

**Issue by edgarjs** [sinatra/sinatra#1654]
I had this in my 2.0.8 app to set the content type:

```ruby
before do
  content_type :json
end
```

But after updating to 2.1.0, it returns all requests as `text/html`.

I see that there's a new setting `default_content_type` in 2.1 and it's working again after I use that instead of the before filter. But shouldn't the content type be json anyways?

Thanks.

**Comment by jkowens** [comment]
Hi, so that is a regression in 2.1. There is a fix on master, just needs released. See: https://github.com/sinatra/sinatra/issues/1647
