### ISSUE TITLE
ruby Sinatra

### ISSUE THREAD

**Issue by vaishali59** [sinatra/sinatra#1661]
Traceback (most recent call last):
        2: from main.rb:4:in `<main>'
        1: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- Data_mapper (LoadError)
        9: from main.rb:4:in `<main>'
        8: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
        7: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:161:in `rescue in require'
        6: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems.rb:211:in `try_activate'
        5: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/specification.rb:1371:in `activate'
        4: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `activate_dependencies'
        3: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `each'
        2: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/specification.rb:1403:in `block in activate_dependencies'
        1: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/specification.rb:1369:in `activate'
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/specification.rb:2247:in `raise_if_conflicts': Unable to activate dm-serializer-1.2.2, because json-2.3.1 conflicts with json (~> 1.6) (Gem::ConflictError)
        10: from main.rb:4:in `<main>'
         9: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
         8: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:161:in `rescue in require'
         7: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems.rb:210:in `try_activate'
         6: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems.rb:217:in `rescue in try_activate'
         5: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/specification.rb:1371:in `activate'
         4: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `activate_dependencies'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `each'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/specification.rb:1403:in `block in activate_dependencies'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/specification.rb:1369:in `activate'
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/specification.rb:2247:in `raise_if_conflicts': Unable to activate dm-serializer-1.2.2, because json-2.3.1 conflicts with json (~> 1.6) (Gem::ConflictError)

**Comment by namusyaka** [comment]
@vaishali59 Please give us easy-to-understand explanation if you have any problem with Sinatra.
I can't understand what you would like to report.
