### ISSUE TITLE
Wlang 3.0 dropped support for Tilt

### ISSUE THREAD

**Issue by jkowens** [sinatra/sinatra#1674]
What should be done? Should we try to get wlang support baked into Tilt or stop officially supporting wlang templates?

See: https://github.com/blambeau/wlang/blob/master/CHANGELOG.md#300--2020-12-29 and https://github.com/blambeau/wlang/issues/8

cc: @namusyaka

**Comment by blambeau** [comment]
I can revert the change if it's safer for Sinatra users. Or keep branch 2.x alive.
