### ISSUE TITLE
Trying to move access logs to an external logging file, how exactly?

### ISSUE THREAD

**Issue by elico** [sinatra/sinatra#1680]
I have been following couple docs such as:
http://sinatrarb.com/contrib/custom_logger

to try and understand how to make stdout more "quiet".
I am running the sinatra app under systemd as a service and it works great except that the logging making a lot of noise.
The ideal solution would be to use a weekly/else logger but I cannot make it work for some reason.
Any recommendations?

**Comment by froderik** [comment]
How do you run it? With rackup? I use unicorn for an app and then it is part of the config to send stdout and stderr to specific files. Something like that is probably what you want to do. 

It is also possible to pipe the ouput of your command to a file. Here is an [article](https://stackoverflow.com/questions/7526971/how-to-redirect-both-stdout-and-stderr-to-a-file#7526988) about that.
`

**Comment by elico** [comment]
@froderik I am running it it with a simple `ruby app.rb` with a `  run! if app_file == $PROGRAM_NAME # = $0` statement in the class.
I noticed that it uses webrick by default and when I am installing puma it seems to work in a silent/quiet mode.
I want to see the output of the service but not the access_log in stdout, thats the main issue.

I was thinking about using rackup but wasn't sure how to do that.

**Comment by froderik** [comment]
You can send the log to a file as per the link you posted above perhaps? It is just the standard Ruby logger at work there I believe. If you are logging output you may want to send that to a specific file - it is quite possible to have several loggers to different destinations if you'd like.
