### ISSUE TITLE
Disabling protection removes session

### ISSUE THREAD

**Issue by onli** [sinatra/sinatra#1685]
I'm trying to debug why Sinatra/Rack is dropping sessions without notice, and during this investigation stumbled upon what I suspect is a bug or at least undocumented behaviour: When disabling protections no rack.session cookie is set.

This reproduces it for me:

```
configure do
    puts 'configure'
    enable :sessions
    set :session_secret, 'abc'
                                    # 1 year
    set :sessions, :expire_after => 31104000, :same_site => :lax, :secure => true
    
    disable :protection
    puts "protection disabled"
    #set :protection, except: [:remote_token, :http_origin]
end
```

With disabled protection loading localhost (with https enabled) will not show any cookie being set. If I instead  disable the line `disable :protection` and only disable :remote_token and :http_origin, the session cookie gets set (but this triggers the separate bug/incompatibility of the session vanishing later, but I'd open a separate issue for that).

**Comment by dentarg** [comment]
I can see the same thing using Sinatra v2.1.0 and this `config.ru` started using Puma

```ruby
require "sinatra/base"

class App < Sinatra::Base
  configure do
    enable :sessions
    disable :protection
  end
  get "/" do
    body "OK"
  end
end

run App
```

No `Set-Cookie: rack.session=...` in the response with `disable :protection`

**Comment by jkowens** [comment]
Turns out `rack.session` cookie doesn't get set until something is persisted to the session:

```
require 'sinatra'
require 'sinatra/contrib'

enable :sessions
set :session_secret, 'abc'
disable :protection

get '/' do
  message = "Hello World!"
  session = env['rack.session']
  # Set some state:
  session[:message] = message
  message
end

get '/session' do
  session[:message]
end
```

You can see that the cookie is set after loading `/` and then you can see the persisted data by going to `/session`.

**Comment by jkowens** [comment]
It seems like you may have been using https to test, but keep in mind that setting `:secure => true` will prevent cookies being sent over unsecure connections.

**Comment by jkowens** [comment]
It might be worth investigating if `:same_site => :lax` is creating issues with your particular setup and browser. I'm going to close this issue for now, but if more information comes to light please feel free to reopen.
