### ISSUE TITLE
Add my extension to the list at http://sinatrarb.com/extensions-wild.html ?

### ISSUE THREAD

**Issue by jubishop** [sinatra/sinatra#1689]
I've been iterating on my own extension that I find useful in my development with Sinatra apps.  

https://github.com/jubishop/sinatra-static

I'd be very curious and grateful for any feedback, and also would like to know if you'd be  willing to list it alongside the others at http://sinatrarb.com/extensions-wild.html ?

**Comment by jkowens** [comment]
@jubishop you can create a pull request that adds your extension to the markdown in this repo:

https://github.com/sinatra/sinatra.github.com

**Comment by jubishop** [comment]
Ah thanks!
