### ISSUE TITLE
Sinatra on MRuby

### ISSUE THREAD

**Issue by yerlaser** [sinatra/sinatra#1694]
A general question - was supporting MRuby ever considered by the Sinatra team?
I am asking because it would be nice to run a lightweight Sinatra server on Raspberry PI or an even smaller device.
I would be willing to contribute as well.

**Comment by zzak** [comment]
@yerlaser Nothing officially supported, but [if you check github](https://github.com/search?q=mruby+sinatra) a few people have tried and there's even an entire [IoT framework for mruby](https://github.com/mruby-plato/plato-v1) that I've heard has parts inspired by Sinatra.

This is a good question though, and inspired me to [setup our GitHub discussions board](https://github.com/sinatra/sinatra/discussions) so people can ask questions like this and share.

In general though, this library aims to be a RubyGem for CRuby and JRuby specifically, I don't think we're targetting or plan to target any other implementations. In my experience with MRuby, you need to depend on entirely different libraries for things like network calls, etc, so the sinatra gem/library as it stands would depend on too many things specific to the current RubyGems ecosystem. That said though, I could imagine a world where the relevent bits of Sinatra core could be made agnostic to implementation and re-used in either CRuby or MRuby packages. That would be really interesting 🤔

**Comment by yerlaser** [comment]
@zzak Thanks a lot for this comprehensive response. This is good news and I am glad that you're open to this.
Let me explore this a bit in depth. Yes, your suggestion to have an implementation agnostic core is very reasonable.
I'll close this issue.
