### ISSUE TITLE
One sinatra to rule them all, one sinatra to find them, one sinatra to bring them all and in the darkness bind all the routes together! [Alternative title: meta-merge all routes together into FAT SINATRA)

### ISSUE THREAD

**Issue by rubyFeedback** [sinatra/sinatra#1704]
Hey folks.

I'll introduce this suggestion, with some background.

I have been using ruby .cgi files ever since I switched away from PHP in ~2004 into ruby.

Believe it or not, I have used .cgi files for my local knowledge base. I speak of easily 
up to 1000 different .cgi files, most small, but a few being super-huge. The biggest
one has literally 15.000 lines - this is not code, per se, but just documentation for
a project actually. The .cgi is just a way to easily display that via ruby. Anyway.

I have been learning a bit of rails but always hated the monolithic mega-approach. 

I read the old "Sinatra up and running" which is now 10 years old. :(

Sinatra is quite nice. Very simple. I like that.

A few days ago I had the idea to stop using .cgi files directly, in the sense that
I'd just embed the .rb code. My new approach, using a fake-pseudo web-framework
that I wrote (which originated from my ancient PHP code) was to both make use
of ruby's block form, instance_eval, and straight up eval(). Now, everyone is 
scared of such a hack, I get it ... but that way I now have an external text file,
which I read in, which contains a DSL, which in turn is handled by my pseudo
webframework. It renders a string as a result, and the same string is now
usable via .cgi, AND via sinatra. Almost for free! \o/

I have to use a bit of boilerplate code (I use sinatra via the subclassing model
by the way; I hate toplevel manipulations, so I don't use sinatra without 
simply sublcassing) but by and large this is all great. Especially on windows,
sinatra works better than .cgi files.

Anyway. This was just a bit of intro to understand where I am coming from.

My next goal is to write such tiny sinatra-based applications that contain 
individual webpages, both renderable via .cgi and sinatra. But I don't know
how to merge tons of routes together.

I had a look at http://sinatrarb.com/intro.html and while this is ok, it does
not seem to cover my use case.

Say you have 3 small sinatra apps, all subclassed, all just handling one
route. Say: books/ people/ feedback.

I'd love each of these 3 .rb files to remain independent but ALSO be
able to "merge" their routes together into a "master / controller"
sinatra app. Does that make any sense?

So I'd need the controller to have all these routes defined. But I 
am not sure how to define them all via get().

Is there some automatic way to merge such routes together?

If so, could this also be added to the documentation at
http://sinatrarb.com/intro.html ?

**Comment by dentarg** [comment]
Did you see the code snippet with `config.ru` under "Dynamic Application Creation"? Sounds like what you want? You can `map` ("mount") or `use` your Sinatra applications however you like (they are just like any other rack middleware)
