### ISSUE TITLE
Proposal: Offer a public toplevel way to designate different public folders, for example via Sinatra.set() or similar

### ISSUE THREAD

**Issue by rubyFeedback** [sinatra/sinatra#1707]
Hey folks,

Before I describe my proposal, allow me to explain how I came about this.

I have a lot of legacy .cgi scripts. I am still using them.

I also have a crappy custom "webframework" that I wrote many years ago. I still
maintain it.

A few months ago I had the idea to unify the parts that are useful, and make it
available via both .cgi, and sinatra-based applications. For this I actually use
scary eval(). :)

So, one text file describes the logic of a web-app. My custom webframework
loads this text file, and evalutes it, and then presents the string that can be
served via the WWW. Next, the .sinatra file just starts sinatra, then delegates
to the webframework, and then simply presents the generated string to the
user. So I have sinatra support for "almost free".

Now I am aware that eval() is super scary but it works for my basic use cases.
This is not rocket science, I just present a string ultimately.

Ok now to my problem ...

Sinatra defaults to public/ but you can designate other directories via 
set :public_folder. This works fine in a common setting but my stupid
approach is to use eval(). The sinatra-specific code that I use is actually
super-minimal and I don't want to modify the .sinatra files; instead I
would like to automatically let my webframework decide where the
public folder(s) are. (I actually need to use more than one, because
my images are all spread over everywhere. Not sure why sinatra
assumes that everything must be inside of public/).

So here, I would like to add a toplevel way to specify ADDITIONAL
public folders for sinatra, in addition to the current way to use
via set().

I'd love to use this:

    Sinatra.set :public_folder, '/home/fancy/images/'

Perhaps for clean up, some simple toplevel method to restore the default
again, to keep things tidy. That way people can just re-set the default;
and the advice given could be to avoid Sinatra.set() other than when 
people have a good use case to use it. In my case the use case is
that I want to specify some globals, without being tied to any particular
individual class (in my current approach I'd have to add this to every
sinatra instance via set(), but I'd rather specify this globally for all
my sinatra applications, whenever I use it with my webframework. I
don't need it for standalone sinatra applications, only for the dual-use
case scenario I have available via both sinatra-app and oldschool
.cgi).

The above may not be absolutely necessary because I have a few more
ideas how to work around my current limitation, but I'd love to just 
be able to specify this on the toplevel way, globally, rather than have
to add more ad-hoc code to tap onto the sinatra subclass that I use.
(I always subclass ... always found it to be more reliable in the long
run when I do).

**Comment by dentarg** [comment]
Not sure I follow what's being requested here. Feel free to open a pull request demonstrating the change you are asking for.
