### ISSUE TITLE
IndifferentHash#transform_keys not transforming keys

### ISSUE THREAD

**Issue by evanboho** [sinatra/sinatra#1717]
I've encountered a bug that was caused by https://github.com/sinatra/sinatra/pull/1427.

The issue is that calling `transform_keys` on an IndifferentHash with `&:to_sym` is essentially a no-op. 

Using versions Ruby 2.5.9, Sinatra: 2.1.0

Example:
```
> hash = Sinatra::IndifferentHash[:a=>:a]
=> {"a"=>:a}
> hash.keys
=> ["a"]
> hash.transform_keys(&:to_sym).keys
=> ["a"]
```

In Ruby 2.5:
```
> hash = { 'a' => :a }
 => {"a"=>:a}
> hash.keys
 => ["a"]
> hash.transform_keys(&:to_sym).keys
 => [:a]
```

Seems like `transform_keys` should return a Hash instead of an IndifferentHash to allow for this case. This seems to be the same behavior as ActiveSupport and Ruby >2.5.

**Comment by johansenja** [comment]
Same problem here, my current workaround is
```ruby
transformed = hash_w_i_a.to_h { |k, v| [ k.to_sym, v ] }
# instead of hash_w_i_a.transform_keys(&:to_sym)
```

**Comment by jkowens** [comment]
Would you be able to submit a PR to fix?

**Comment by AravindSelvamani** [comment]
Hi @evanboho Can I raise a PR to fix this one? 
cc: @jkowens

**Comment by jkowens** [comment]
@AravindSelvamani it doesn't sound like this was claimed, so go for it!

**Comment by jkowens** [comment]
@evanboho @AravindSelvamani after digging into this more, I'm wondering if this is an issue we can/should fix. 

The `transform_keys` method returns an instance of `Sinatra::IndifferentHash` not a `Hash`. It currently behaves just like `ActiveSupport::HashWithIndifferentAccess#transform_keys`.

As @johansenja pointed out, calling `to_h` seems like the appropriate step to accomplish your goal:

```
> hash = Sinatra::IndifferentHash[:a=>:a]
=> {"a"=>:a}
> hash.keys
=> ["a"]
> hash.to_h.transform_keys(&:to_sym).keys
=> [:a]
```

**Comment by jkowens** [comment]
@AravindSelvamani I'm really sorry, I think I may have led you on a wild goose chase 😞
