### ISSUE TITLE
use middleware prevents from migrating to ruby 3

### ISSUE THREAD

**Issue by EduardoSimon** [sinatra/sinatra#1720]
# Context
Hi folks, I am trying to migrate a sinatra app from ruby 2.7 to ruby 3. My tests are failing when using a sinatra middleware like so when passing a keyword argument:

`use MyMiddleware, keyword_argument: 'foo'`

AFAIK there has been a breaking change regarding keyword arguments, now its mandatory to specify them in the method signature as such: 

```ruby
-- before
def foo(*args, &block)
  target(*args, &block)
end

-- after
def foo(*args, **kwargs, &block)
  target(*args, **kwargs, &block)
end
```

# Possible solution
After reviewing the code it seems like the use method needs a simple signature [change](https://github.com/sinatra/sinatra/blob/master/lib/sinatra/base.rb#L1477), but I don't know how this could impact the library. If the change is that simple and backwards-compatible, are you accepting PRs?

Thanks in advance.

**Comment by epergo** [comment]
That should work after https://github.com/sinatra/sinatra/pull/1701, that change is still unreleased so, could you try installing Sinatra from the `master` branch?

**Comment by epergo** [comment]
👋 @EduardoSimon did you try to use Sinatra from `master`? Did it work?

**Comment by olofheurgren** [comment]
> That should work after #1701 but that change is still unreleased so could you try installing Sinatra from the `master` branch?

I had the same issue and can confirm that this solution works!

Tested with

```
use Rack::JSONBodyParser, verbs: ['POST', 'PATCH'], media: ['application/json', 'application/vnd.api+json']
``` 

where `Rack::JSONBodyParser` is from the [rack-contrib](https://github.com/rack/rack-contrib) gem.
