### ISSUE TITLE
can't modify rbtree during iteration (TypeError)

### ISSUE THREAD

**Issue by kurukuruk** [sinatra/sinatra#1722]
Hello. I start a new project on Sinatra. I haven't used it in a long time and I meet an error when I'm starting a basic test script.

```
# app.rb
require 'sinatra'

get '/hello' do
  'Hello world !'
end
```

In first time, i met a error from the SortedSet gem. I've installed it but i'm meeting this now :

> == Sinatra (v2.1.0) has taken the stage on 4567 for development with backup from Thin
> 2021-09-14 12:16:58 +0200 Thin web server (v1.8.1 codename Infinite Smoothie)
> 2021-09-14 12:16:58 +0200 Maximum connections set to 1024
> 2021-09-14 12:16:58 +0200 Listening on localhost:4567, CTRL+C to stop
> 2021-09-14 12:16:58 +0200 Stopping ...
> == Sinatra has ended his set (crowd applauds)
> C:/Ruby30/lib/ruby/3.0.0/set.rb:373:in `delete': can't modify rbtree during iteration (TypeError)
>         from C:/Ruby30/lib/ruby/3.0.0/set.rb:373:in `delete'
>         from C:/Ruby30/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:570:in `block in run_timers'
>         from C:/Ruby30/lib/ruby/3.0.0/set.rb:344:in `each_key'
>         from C:/Ruby30/lib/ruby/3.0.0/set.rb:344:in `each'
>         from C:/Ruby30/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:568:in `run_timers'
>         from C:/Ruby30/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:551:in `block in run'
>         from C:/Ruby30/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:547:in `loop'
>         from C:/Ruby30/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:547:in `run'
>         from C:/Ruby30/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:144:in `run_machine'
>         from C:/Ruby30/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:195:in `run'
>         from C:/Ruby30/lib/ruby/gems/3.0.0/gems/thin-1.8.1/lib/thin/backends/base.rb:75:in `start'
>         from C:/Ruby30/lib/ruby/gems/3.0.0/gems/thin-1.8.1/lib/thin/server.rb:162:in `start'
>         from C:/Ruby30/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/handler/thin.rb:22:in `run'
>         from C:/Ruby30/lib/ruby/gems/3.0.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1565:in `start_server'
>         from C:/Ruby30/lib/ruby/gems/3.0.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1499:in `run!'
>         from C:/Ruby30/lib/ruby/gems/3.0.0/gems/sinatra-2.1.0/lib/sinatra/main.rb:45:in `block in <module:Sinatra>'

**Comment by dentarg** [comment]
This is not an issue with Sinatra but with eventmachine, an dependency of Thin, the web server that is being used.

Try using an other server (like Puma): https://github.com/sinatra/sinatra#available-settings

(I think one should avoid both eventmachine and thin these days (unless you have very special needs) as they aren't maintained they way they used to be.)

**Comment by kurukuruk** [comment]
Thanks ! I use puma and it work now.

**Comment by dentarg** [comment]
@kurukuruk Great! Can you close this issue? (I'm not a maintainer so I can't do that)

**Comment by dentarg** [comment]
@jkowens can you close this issue?
