### ISSUE TITLE
CI: experiment with turning .actions.sh into individual GitHub Action Jobs

### ISSUE THREAD

**Issue by olleolleolle** [sinatra/sinatra#1724]
It seems like there are two individual Jobs hidden in this .actions.sh shell script.

We _could_ reformulate as Job elements with their own setup, caching, etc.

Perhaps there are CI time gains to be made this way!

https://github.com/sinatra/sinatra/blob/master/.actions.sh

**Comment by epergo** [comment]
Didn't see this issue :man_facepalming: I have created individual steps for each gem [here](https://github.com/sinatra/sinatra/pull/1745) WDYT?

**Comment by dentarg** [comment]
I think this can be closed

**Comment by olleolleolle** [comment]
Thanks! Closing, duplicate.
