### ISSUE TITLE
The difference in .new and .new! for accessing instance methods during testing

### ISSUE THREAD

**Issue by jmt-gh** [sinatra/sinatra#1734]
Hello! I'm writing some rspec specs for a small sinatra app for the first time, and found something odd that I don't understand. In the spec, if see different behavior defining my app as:

`let(:app) { App.new }` vs `let(:app) { App.new! }`

In the former, I don't seem to have any access to any of the instance methods I've defined on the class, but in the latter, I do (and subsequently can make "expect / respond_to" specs works).

_app.rb_
```
require 'sinatra/base'

class App < Sinatra::Base
  get '/' do
    running_jobs
  end

  def running_jobs
    # do stuff
  end
end
```

_In irb with an instance method called `running_jobs`_
```
$ irb -r ./app.rb 
irb(main):001:0> x = App.new
=> #<App app_file="/home/j/git/d/app.rb">
irb(main):002:0> x.running_jobs
Traceback (most recent call last):
        4: from /usr/bin/irb:23:in `<main>'
        3: from /usr/bin/irb:23:in `load'
        2: from /usr/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        1: from (irb):2
NoMethodError (undefined method `running_jobs' for #<App app_file="/home/j/git/d/app.rb">)
irb(main):003:0> x = App.new!
=> #<App:0x0000563e6ec4a1a0 @default_layout=:layout, @preferred_extension=nil, @app=nil, @template_cache=#<Tilt::Cache:0x0000563e6ec4a150 @cache={}>, @pinned_response=nil>
irb(main):004:0> x.running_jobs
=> []
```

**My question**: Can someone help explain this behavior / point me to documentation on it? Is it safe to use? Are there any other effects I would want to worry about?

**Comment by jmt-gh** [comment]
I found documentation of the methods themselves here:

https://rubydoc.info/gems/sinatra/Sinatra/Base#new-class_method
https://rubydoc.info/gems/sinatra/Sinatra/Base#new!-instance_method

But I don't think I fully grasp the implications of this, especially in the context of writing a spec test, so any help would be great.

Is the idea that I can use `.new` to test the "application" itself (as a controller), but I can use `.new!` to test an instance of the literal class (i.e write specs/tests against helpers)? If this is the case, is this the intent of them, or is there another use as well?

**Comment by dentarg** [comment]
> Is the idea that I can use `.new` to test the "application" itself (as a controller), but I can use `.new!` to test an instance of the literal class (i.e write specs/tests against helpers)?

I think so :) 

To be clear, `new!` is the original `new`

https://github.com/sinatra/sinatra/blob/e69b6b9dee7165d3a583fc8a6af10ceee1ea687d/lib/sinatra/base.rb#L1528-L1537

**Comment by dentarg** [comment]
Some old commits that may provide more context:

* https://github.com/sinatra/sinatra/commit/f9b1c60ae4686ea2991f4644f92733d271d61072
* https://github.com/sinatra/sinatra/commit/d7eabb9739ae53d0795ad462bcd6a3e1284a5684
* https://github.com/sinatra/sinatra/commit/26f4c216c41ffd384e8e2f9886308981e5cd2160 (talks about testing)

**Comment by jmt-gh** [comment]
Thanks @dentarg ! This makes sense. One issue I'm running in to now is around testing if a method defined in my app was called when one of the routes was hit... I'm able to get this to work if a Class method on a different class is called when the route is hit, but I can't figure out how to get the spec to work for a local method.

I've got a spec_helper set up using `Rack::Test::Methods` per the documentation.

Toy app:

```  
class App < Sinatra::Base
get '/hello' do
  hello
end 

def hello
  "hello"
end 
```

Toy spec:
```
 context 'get /hello' do
    def app 
      App.new!
    end 

    it 'responds to hello' do
      expect(app).to respond_to :hello
    end

    it 'calls hello' do
      expect(app).to receive(:hello)
      get '/hello'
    end 

    it 'returns hello' do
      let(:response) { get '/hello' }

      expect(response.status).to eq 200
      expect(response.body).to eq "hello"
    end
  end 
  ```

In those specs, the first spec passes, the third spec passes, but the last one fails. The first one and the third one are clearly showing that it's working.. but the second one continues to fail (I've tried various combinations of using .new, .new!, let statements, etc).

Any thoughts? :D

**Comment by dentarg** [comment]
Have you tried with `def app; App; end` instead of `let(:app) { App.new! }`? That's how both rack-test (https://github.com/rack/rack-test#examples) and Sinatra (https://github.com/sinatra/sinatra#testing) examples says how to do it. Also, you can use the `last_response` helper method, no need for `let(:response)`.

**Comment by dentarg** [comment]
@jmt-gh can you close this issue?
