### ISSUE TITLE
Official website SSL certificate appears to be expired (sinatrarb.com)

### ISSUE THREAD

**Issue by DragonStuff** [sinatra/sinatra#1735]
https://www.sinatrarb.com/ appears to have a certificate error now.

https://www.ssllabs.com/ssltest/analyze.html?d=sinatrarb.com

> We were able to retrieve a certificate for this site, but the domain names listed in it do not match the domain name you requested us to inspect. It's possible that:
> 
> - The web site does not use SSL, but shares an IP address with some other site that does.
> - The web site no longer exists, yet the domain name still points to the old IP address, where some other site is now hosted.
> - The web site uses a content delivery network (CDN) that does not support SSL.
> - The domain name is an alias for a web site whose main name is different, but the alias was not included in the certificate by mistake.

Let me know if you need any assistance! Happy to help.

**Comment by zzak** [comment]
Ugh, I don’t have the GoDaddy creds anymore, we may have to ask Blake

**Comment by dentarg** [comment]
Yeah looks like the DNS is pointing at old GitHub IPs?

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain says to use

```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

DNS says

```
$ host www.sinatrarb.com
www.sinatrarb.com is an alias for sinatrarb.com.
sinatrarb.com has address 192.30.252.154
sinatrarb.com has address 192.30.252.153
```

**Comment by jkowens** [comment]
@zzak is there any way to move forward on this?

**Comment by zzak** [comment]
@jkowens I seemed to have lost the creds, so it's best to reach out to blake and hope he still has them 🙏

**Comment by dentarg** [comment]
Who is Blake? @blake? @blakewilliams (sorry for the random pings, but I think it is important to resolve this)

**Comment by jkowens** [comment]
That would be @bmizerany. Hi Blake, any chance you could help us out 😅

**Comment by BlakeWilliams** [comment]
Not the correct Blake, but hope y'all get it sorted! ❤️

**Comment by bmizerany** [comment]
@jkowens I sent you an email. I still have access to the GoDaddy account and can grant you access.

**Comment by jkowens** [comment]
We should be good now 🎉
