### ISSUE TITLE
Retrieving the matching route pattern

### ISSUE THREAD

**Issue by erez-rabih** [sinatra/sinatra#1737]
Hi,

given a route definition:

```ruby
get '/users/:username' do
  # some logic here
end
```

is there a way I can retrieve the string `"/users/:username"` inside the route block?
in other words - does the route matching component inject the matching pattern somewhere in the ENV map in the middleware chain for users to use?
If not - how complicate would it be to add such an ability? I would be happy to contribute if needed.

The use case is for reporting metrics per route pattern to prometheus (see [this issue](https://github.com/prometheus/client_ruby/issues/233))

**Comment by bnadlerjr** [comment]
I think `env['sinatra.route']` is what you're looking for.

**Comment by erez-rabih** [comment]
thanks @bnadlerjr that works!
appreciate the help.
