### ISSUE TITLE
Update changelog for v3.0.0

### ISSUE THREAD

**Issue by jkowens** [sinatra/sinatra#1744]
I went ahead and dispensed with the unstable branch because it was causing confusion. I tagged v2.2.0 and moved on to master being for v3.0. Time to start moving forward 😅 

If someone can help update the changelog with details about 3.0 that would be appreciated.

Hopefully we can get a core team member that can cut releases to do that for 2.2.0 and then 3.0 at some point.

If anyone needs to pin their Gemfile to v2.2.0 they can do:

```
gem 'sinatra', git: 'https://github.com/sinatra/sinatra.git', tag: 'v2.2.0'
```

cc: @sinatra/sinatras-helpers @sinatra/team-sinatra

**Comment by dentarg** [comment]
Hmm... @namusyaka seems to be working on [v2.1.1](https://github.com/sinatra/sinatra/milestone/28) and https://github.com/sinatra/sinatra/pull/1676 was just merged to master.

@namusyaka did you see this issue? I think it would be good if you can do what @jkowens suggest and release v2.2.0 from https://github.com/sinatra/sinatra/releases/tag/v2.2.0 to avoid any further confusion.

**Comment by namusyaka** [comment]
Oops I overlooked this. Thanks for letting me know.
