### ISSUE TITLE
2.2.0 regression in JRuby handling of inherited Sinatra::Base keyword args

### ISSUE THREAD

**Issue by yaauie** [sinatra/sinatra#1749]
#1670 provides a fix to move forward with Ruby 3.0's Keyword arguments, but it comes at the expense of breaking Sinatra when run under JRuby.

~~~
ArgumentError: wrong number of arguments (given 3, expected 1..2)
~~~

With backtrace
~~~
/usr/share/logstash/logstash-core/lib/logstash/api/modules/base.rb:43:in `initialize'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1537:in `new'
/usr/share/logstash/logstash-core/lib/logstash/api/rack_app.rb:113:in `block in app'
...
~~~

I have filed a separate bug upstream with jruby (https://github.com/jruby/jruby/issues/7102), but am hoping we can find a path foward here in Sinatra while we wait for JRuby to come up with a fix.

**Comment by dentarg** [comment]
@yaauie can you try #1750?

**Comment by yaauie** [comment]
I answered over on #1750 that it resolves the situation for Logstash.
