### ISSUE TITLE
Documentation is wrong

### ISSUE THREAD

**Issue by 0000marcell** [sinatra/sinatra#1754]
You not only need sinatra, but you also need one of the servers thin, puma, reel, HTTP, webrick, so the getting started documentation should be 
```
gem install sinatra
gem install thin # or any other server
```

**Comment by dentarg** [comment]
Yeah now that Ruby doesn't ship with webrick anymore 

can you send a PR?

**Comment by epergo** [comment]
Another alternative is adding webrick as a dependency to sinatra, that way the gem has everything it needs to work, wdyt?

**Comment by dentarg** [comment]
I don't think we should add webrick as a dependency of sinatra. People not using webrick don't want webrick in their dependency tree.

**Comment by epergo** [comment]
Right, there is no need to pollute user's gemfile with dependencies if they are not mandatory. 👍
