### ISSUE TITLE
Review all template languages supported

### ISSUE THREAD

**Issue by epergo** [sinatra/sinatra#1759]
Following what I wrote [here](https://github.com/sinatra/sinatra/issues/1531#issuecomment-787875203)

Here it is a list of all template languages that we support, I've added a:
- :heavy_check_mark: for those I think are in a good shape and we should continue support them
- :negative_squared_cross_mark: for those that are not maintained anymore and we could drop support
- :interrobang: Are they really unmaintained? are maintained but could we drop support? Don't know, give me your opinion

Templates:
- :heavy_check_mark:  Haml
- ERB
  - :heavy_check_mark:  `erb` itself from Ruby
  - [x] :negative_squared_cross_mark:  [`erubis`](https://github.com/kwatch/erubis) Last commit from 2011, **done in** https://github.com/sinatra/sinatra/pull/1761
  - :heavy_check_mark: [`erubi`](https://github.com/jeremyevans/erubi)
- :heavy_check_mark:[Builder](https://github.com/jimweirich/builder) ~~Last commit from 2013~~ **Update** Moved to https://github.com/tenderlove/builder, it is maintained
- :heavy_check_mark: Nokogiri
-  [x] :interrobang: SASS and SCSS, they both need to install [ruby-sass](https://github.com/sass/ruby-sass) gem which is not maintained anymore, however there is a recommended [alternative](https://github.com/sass/sassc-ruby), maybe we should do the transition. Don't know if folks use this though **Done in** https://github.com/sinatra/sinatra/pull/1768
- :heavy_check_mark: Liquid
- Markdown, it needs one of the following gems to work, not all of them are maintained:
  - :heavy_check_mark: [RDiscount](https://github.com/davidfstr/rdiscount)
  - :heavy_check_mark: [RedCarpet](https://github.com/vmg/redcarpet)
  - [x] :negative_squared_cross_mark: [BlueCloth](https://github.com/ged/bluecloth). **Done in** https://github.com/sinatra/sinatra/pull/1762
  - :heavy_check_mark: [kramdown](https://kramdown.gettalong.org/)
  - [x] :interrobang: [maruku](https://github.com/bhollis/maruku) , last commit from 2017. **Done in** https://github.com/sinatra/sinatra/pull/1762
  - :heavy_check_mark: [commonmarker](https://github.com/gjtorikian/commonmarker)
  - :heavy_check_mark: [pandoc](https://github.com/alphabetum/pandoc-ruby)
- [x] :interrobang: [Redcloth](https://github.com/jgarber/redcloth), not actively maintained according to comments [here](https://github.com/jgarber/redcloth/issues/58). **Done in** https://github.com/sinatra/sinatra/pull/1766
- :heavy_check_mark: RDoc
- :heavy_check_mark: [Asciidoctor](https://github.com/asciidoctor/asciidoctor)
- [x] :interrobang: [Radius](https://github.com/jlong/radius), it is maintained but is it used by Sinatra users? **Done in https://github.com/sinatra/sinatra/pull/1793**
- :heavy_check_mark: [Markaby](https://github.com/markaby/markaby)
- :heavy_check_mark: [Rabl](https://github.com/nesquena/rabl)
- :heavy_check_mark: [Slim](https://github.com/slim-template/slim)
- [x] :interrobang: [Creole](https://github.com/minad/creole), it is maintained but is it used by Sinatra users? **Done in https://github.com/sinatra/sinatra/pull/1792**
- [x] :interrobang: MediaWiki which requires [Wikicloth](https://github.com/nricciar/wikicloth), it is maintained but is it used by Sinatra users? **Done in https://github.com/sinatra/sinatra/pull/1791**
- [x] :interrobang: [CoffeeScript](https://github.com/rails/ruby-coffee-script), it is maintained but is it used by Sinatra users? **Done in https://github.com/sinatra/sinatra/pull/1790**
- :heavy_check_mark: [Yajl](https://github.com/brianmario/yajl-ruby)
- [x] :interrobang: [WLang](https://github.com/enspirit/wlang), it is maintained but is it used by Sinatra users? **Done in** https://github.com/sinatra/sinatra/pull/1780

WDYT? Do you agree on dropping support for those marked with :negative_squared_cross_mark:? What's your opinion on the rest?

---

Edits:

2022-02-28
- Keep `markaby` and `asciidoctor`
- Update `builder`, it was forked by `@tenderlove` and is maintained

**Comment by dentarg** [comment]
😱 that list

👍🏻 On dropping all ❎ and ⁉️

While I haven't used https://github.com/asciidoctor/asciidoctor it sounds cool and that project is very active which is fun, so maybe that could be the exception

**Comment by epergo** [comment]
> While I haven't used https://github.com/asciidoctor/asciidoctor it sounds cool and that project is very active which is fun, so maybe that could be the exception

Sure! We can keep whatever we think is interesting, and in this case it is even in a healthy state.

---

Before continuing removing stuff @olleolleolle @jkowens @namusyaka , what's your opinion? Anything in particular that you would keep?

**Comment by jkowens** [comment]
I'm not entirely sure what all to keep, but I think I'd be good dropping Builder, Sass/SCSS, RedCloth, and Coffeescript.

**Comment by epergo** [comment]
We have finished removing all the engines we wanted to drop so... closing!

**Comment by jkowens** [comment]
Great job @epergo, thanks!
