### ISSUE TITLE
Byebug errors

### ISSUE THREAD

**Issue by arbesulo** [sinatra/sinatra#1767]
I'm not sure if this is a problem in Sinatra or in byebug, so please let me know if you think is an issue in byebug.

When debugging an application, exceptions are raised when issuing some commands like `frame` or `backtrace`

```
(byebug) frame
*** undefined method `GET /' for class `Sinatra::Application'
Did you mean?  get
               gets
(byebug) 
```

Evaluating expressions, viewing variables or moving `up` and `down` work normally.

I have created a [demo repository](https://github.com/arbesulo/sinatra-byebug) with a minimal setup that demonstrates the problem.

The environment:
-  Ruby v2.7.5
- Sinatra v2.2.0
- byebug v11.1.3

Any help to have these commands working would be appreciated.

Thanks in advance!

**Comment by dentarg** [comment]
I think you should dig some more to see what's going and possibly report to byebug. This can't be a bug in Sinatra, but maybe some integration with byebug is needed? You have to research this

**Comment by arbesulo** [comment]
Thanks for the answer, I have open an [issue](https://github.com/deivid-rodriguez/byebug/issues/833) in byebug gem
