### ISSUE TITLE
Sinatra currently includes CWE-444

### ISSUE THREAD

**Issue by blakegearin** [sinatra/sinatra#1770]
[Snyk](https://snyk.io) notified me that the latest version of Rack ([2.2.3](https://github.com/rack/rack/tree/2.2.3)) has [CWE-444](https://cwe.mitre.org/data/definitions/444.html). According to the [Snyk website](https://security.snyk.io/vuln/SNYK-RUBY-RACK-1061917), this was fixed on their main branch via [this PR](https://github.com/rack/rack/pull/1733) ([commit](https://github.com/rack/rack/commit/ef1fc0c44e6a4b77c8fcf9b4f3bfa09f04ae8482)).

As indicated on a [PR comment](https://github.com/rack/rack/pull/1733#issuecomment-1064754882), version `3.x` of Rack doesn't have an estimated release period/schedule yet. It is at least worth considering making Sinatra be compatible with this commit/change before `3.x` is released to remove the presence of CWE-444.

In the meantime, I believe this can be patched at the project level by adding Rack as a dependency in a Gemfile specifying the fixing commit:

```gemfile
gem 'rack', github: 'rack/rack', ref: 'ef1fc0c'
```

However, there are other changes included when upgrading to this commit that may break things.

**Comment by jkowens** [comment]
Thanks for the heads up.
