### ISSUE TITLE
Weird 404 response by default on Ruby 3.1 and Sinatra <= 2.2.0 due to `error_highlight`

### ISSUE THREAD

**Issue by dentarg** [sinatra/sinatra#1772]
https://github.com/sinatra/sinatra/pull/1519 actually solves this, but seeing we don't have a release with that change, I thought I would report it for visibility (and maybe gather some more understanding on what's happening)

If you have an app without a `not_found` handler

```ruby
$ cat config.ru
require "sinatra/base"
class App < Sinatra::Base; end
run App
```

And are using Ruby 3.1.1 and Sinatra 2.2.0 (or 2.1.0 or 2.0.8.1), start the app like `bundle exec puma -p 5000 -e production`, the response body includes [parts of the `route_missing` method](https://github.com/sinatra/sinatra/blob/v2.2.0/lib/sinatra/base.rb#L1090)

````
$ curl -s -v localhost:5000/foo
*   Trying 127.0.0.1:5000...
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /foo HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< X-Cascade: pass
< Content-Type: text/html;charset=utf-8
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Content-Length: 111
<
GET &#x2F;foo

        raise NotFound, &quot;#{request.request_method} #{request.path_info}&quot;
* Connection #0 to host localhost left intact
        ^^^^^
````

On 2.1.0 (and 2.0.8.1) the quotes are not encoded in the response:

```
$ curl -s -v localhost:5000/foo
*   Trying 127.0.0.1:5000...
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /foo HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< X-Cascade: pass
< Content-Type: text/html;charset=utf-8
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Content-Length: 96
<
GET /foo

        raise NotFound, "#{request.request_method} #{request.path_info}"
* Connection #0 to host localhost left intact
        ^^^^^
```

The weird response doesn't occur on Ruby 3.0.3

````
$ curl -s -v localhost:5000/foo
*   Trying 127.0.0.1:5000...
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /foo HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< X-Cascade: pass
< Content-Type: text/html;charset=utf-8
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Content-Length: 8
<
* Connection #0 to host localhost left intact
GET /foo
````

**Comment by walro** [comment]
I think that you only see this in Ruby 3.1 is due to the addition of [ErrorHighlight](https://github.com/ruby/error_highlight), mentioned at https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/

Previously, prior to the fix in #1519, `NotFound` would inherit from `NameError` and from the the 3.1 release news:

> Currently, only NameError is supported.

**Comment by dentarg** [comment]
Thanks @walro 

I'm indeed not seeing it if I start my app with `error_highlight ` disabled: `RUBYOPT=--disable-error_highlight bundle exec puma -p 5000 -e production`

Looks like we are not the only ones to be confused by this

* https://github.com/ruby/error_highlight/issues/20
* https://github.com/rspec/rspec-expectations/pull/1339
* https://github.com/seattlerb/minitest/issues/894

**Comment by dentarg** [comment]
Sinatra 3.0.0 that includes https://github.com/sinatra/sinatra/pull/1519 (that addresses this) has been released, closing.
