### ISSUE TITLE
Unable to Join the Sinatra Slack Channel

### ISSUE THREAD

**Issue by michaeleisel** [sinatra/sinatra#1786]
When I try, I get `Channel not found "sinatrarb"`

<img width="449" alt="Screen Shot 2022-06-13 at 11 18 52 AM" src="https://user-images.githubusercontent.com/718607/173387325-c9ea13e6-c68a-47f1-9b15-77b49077d01a.png">

**Comment by jkowens** [comment]
@zzak are you able to investigate?

**Comment by zzak** [comment]
@jkowens Sorry I can't right now, I wonder if the token simply expired or the API we were using changed.

TBH I have no idea how it's even setup just that I thought it was running on Heroku, Konstantin may have created it 🤔

**Comment by jkowens** [comment]
Hey @rkh do you have admin access to the Sinatra Slack?

**Comment by rkh** [comment]
I'll check. I might.

**Comment by leesheppard** [comment]
Still not working 😔

**Comment by carlastabile-okta** [comment]
Can anyone invite me to Slack? I'm also unable to join :(

**Comment by dentarg** [comment]
Is anyone even there? Are you in there @jkowens?

**Comment by zzak** [comment]
For now we can use this link:
https://join.slack.com/t/sinatrarb/shared_invite/zt-1mtmzka43-xw6JED8Hb3M9Ha~1VgZxjQ

It "never expires" but Slack says it's only good for up to 400 people.

I think we may want to consider an alternative, like Discord. /cc @jkowens

**Comment by zzak** [comment]
Moving to discord instead, I've got it all set up.

Here's the link:
https://discord.gg/ncjsfsNHh7
