### ISSUE TITLE
Get tests to pass on `truffleruby-head`

### ISSUE THREAD

**Issue by dentarg** [sinatra/sinatra#1799]
Tracking issue to get CI green for truffleruby-head (continuing https://github.com/sinatra/sinatra/pull/1751)

Current status: https://github.com/sinatra/sinatra/runs/7419039740?check_suite_focus=true#step:5:17

* sinatra tests FAIL
* sinatra-contrib tests PASS
* rack-protection tests PASS

The problem here seems to be the same mentioned in https://github.com/sinatra/sinatra/pull/1751#issuecomment-1059844225 `Couldn't find handler for: rainbows. (LoadError)`

**Comment by dentarg** [comment]
@eregon / @bjfish re: https://github.com/sinatra/sinatra/pull/1751#issuecomment-1059941896, did you get a chance to look at this?

**Comment by eregon** [comment]
BTW the reason the Bundler issue (https://github.com/sinatra/sinatra/issues/1798#issuecomment-1190013828) isn't seen here is the CI job uses the Bundler shipped with truffleruby-dev, not the latest Bundler release

**Comment by eregon** [comment]
The reason of that error is very simple: https://github.com/sinatra/sinatra/blob/98e50067626db9eb6c6215a815057da031202230/test/integration/app.rb#L4
Changing that to `RUBY_ENGINE != 'jruby'` reveals another issue:
```
...
[ruby] WARNING StackOverflowError
Exception `SystemStackError' at <internal:core> core/truffle/io_operations.rb:102:in `create_pipe' - stack level too deep
	from com.oracle.svm.core.graal.snippets.StackOverflowCheckImpl.newStackOverflowError0(StackOverflowCheckImpl.java:333)
<internal:core> core/truffle/io_operations.rb:102:in `create_pipe': stack level too deep (SystemStackError)
	from com.oracle.svm.core.graal.snippets.StackOverflowCheckImpl.newStackOverflowError0(StackOverflowCheckImpl.java:333)
	from <internal:core> core/io.rb:681:in `pipe'
	from <internal:core> core/truffle/io_operations.rb:109:in `create_pipe'
	from <internal:core> core/io.rb:681:in `pipe'
	from <internal:core> core/truffle/io_operations.rb:109:in `create_pipe'
	from <internal:core> core/io.rb:681:in `pipe'
...
```
We'll fix that, but I suspect rainbows won't work on TruffleRuby anyway, so I think we better exclude those tests on TruffleRuby and use `platforms: :mri` in the Gemfile for `rainbows`.
