### ISSUE TITLE
IPSpoofing Thread Check

### ISSUE THREAD

**Issue by damlagul** [sinatra/sinatra#1812]
We have been getting IPSpoofing error while sending requests from our Azure self-hosted build agent to the pact broker app. 

I opened a ticket in the [pact-broker](https://github.com/pact-foundation/pact_broker/issues/571) but this issue is related to how the IPSpoofing check is done in the [ip_spoofing.rb](https://github.com/sinatra/sinatra/blob/master/rack-protection/lib/rack/protection/ip_spoofing.rb).

We found out that since the deployed pact broker app and the build agent's VMSS are in the same region and the Microsoft.Web endpoint is **enabled** in build agent's subnet, they are using private IP addresses (IPV4) while communicating with each other.  Below, you can find what inputs are being sent to Rack from the pact-broker app:

When Microsoft.Web service endpoint is:

- enabled:

```
HTTP_X_FORWARDED_FOR= IPV4
HTTP_X_CLIENT_IP=IPV4
HTTP_CLIENT_IP= [IPV6]:PORT
```

- disabled:

```
HTTP_X_FORWARDED_FOR=[IPV4]:PORT
HTTP_X_CLIENT_IP=IPV4
HTTP_CLIENT_IP= [IPV4]:PORT
```

When it is disabled, HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP have the same values; therefore I am able to get 200 from the app. When it is enabled, HTTP_X_FORWARDED_FOR has the same value as HTTP_X_CLIENT_IP; but a different value and format (IPV4) than HTTP_CLIENT_IP.

Is there a chance from your side to change the way you do checks for the IP Spoofing thread? It seems that instead of using HTTP_CLIENT_IP, HTTP_X_CLIENT_IP will help us here (but we should check only the IP part, not the ports)

**Comment by jkowens** [comment]
My initial suggestion is to disable the ip spoofing check in rack protection. It can be disabled without disabling rack protection entirely.

```
set :protection, except: :ip_spoofing
```
It looks like pact broker already does this for some protections: https://github.com/pact-foundation/pact_broker/blob/941371ec7e0db39ab31066e63ac1db7652966c20/lib/pact_broker/app.rb#L122

I would ask them to make that list configurable or just disable the ip spoofing check as well.
