### ISSUE TITLE
Sinatra::Capture is not compatible with Haml 6

### ISSUE THREAD

**Issue by jkowens** [sinatra/sinatra#1816]
Haml::Buffer was removed.

See: https://github.com/haml/haml/pull/1058, https://github.com/haml/haml/pull/1057

Hi @k0kubun any suggestions on how to handle this code below?

https://github.com/sinatra/sinatra/blob/8ae87a87f38d3c7589ae0d456bc7ea598d5861c2/sinatra-contrib/lib/sinatra/capture.rb#L90-L92

**Comment by k0kubun** [comment]
As to capturing a block, when `disable_capture` is false (default except for Rails), you can capture a block content by just calling a block. You don't need to rely on `Haml::Buffer` for capturing purposes.
