### ISSUE TITLE
Changing `session_store` to `Rack::Protection::EncryptedCookie` was a breaking change

### ISSUE THREAD

**Issue by rickselby** [sinatra/sinatra#1821]
I've just come to update some apps to Sinatra 3, and found that #1324 changes the default cookie handler.

The old cookie read the secret from `session_secret`, i.e.

```ruby
configure do
  set :session_secret, ENV.fetch('SESSION_SECRET') { SecureRandom.hex(64) }
end
```

The new class reads from `secret` instead.

I don't know if this change was intentional, but I think it should be noted in the changelog as a breaking change.

**Comment by rickselby** [comment]
Oh, no, I got that all wrong, sorry. My dev secret just wasn't strong enough.

**Comment by dentarg** [comment]
The change to `Rack::Protection::EncryptedCookie` was indeed a breaking one. 

The old default, `Rack::Session::Cookie`, inherits from [`Rack::Session::Abstract::PersistedSecure`](https://github.com/rack/rack/blob/2.2.4/lib/rack/session/cookie.rb#L49). `Rack::Protection::EncryptedCookie` inherits from [`Rack::Session::Abstract::Persisted`](https://github.com/rack/rack/blob/2.2.4/lib/rack/session/abstract/id.rb#L233).

With `Rack::Session::Cookie`, `session.id` returns an object that can respond to `private_id` but with `Rack::Protection::EncryptedCookie` `session.id` is a String.
