### ISSUE TITLE
Sinatra contrib config file breaks when zeitwerk is used

### ISSUE THREAD

**Issue by DawidJanczak** [sinatra/sinatra#1826]
Hello,

I'm not entirely sure if this is an issue with Sinatra or Zeitwerk itself, but the config file extension https://sinatrarb.com/contrib/config_file breaks when zeitwerk is required in the app. A simple reproduction repository can be found here: https://github.com/DawidJanczak/dry-configurable-sinatra If you check that repo out, run `bundle` and then `APP_ENV=test bundle exec rspec` you'll see it crashing on `settings.foo`. Oddly if you change `APP_ENV` to development it won't crash, but it still won't print the value of `settings.foo`. Only when you remove the `require 'zeitwerk'` line things start to work.

**Comment by fxn** [comment]
Also, if you change the order of requires in `lib/app.rb` to load Zeitwerk after Sinatra, it works too.

**Comment by fxn** [comment]
I think I have it.

Sinatra has a way to compute callers that takes into account a hard-coded list of exceptions:

```ruby
CALLERS_TO_IGNORE = [ # :nodoc:
  %r{/sinatra(/(base|main|show_exceptions))?\.rb$},   # all sinatra code
  %r{lib/tilt.*\.rb$},                                # all tilt code
  /^\(.*\)$/,                                         # generated code
  %r{rubygems/(custom|core_ext/kernel)_require\.rb$}, # rubygems require hacks
  /active_support/,                                   # active_support require hacks
  %r{bundler(/(?:runtime|inline))?\.rb},              # bundler require hacks
  /<internal:/                                        # internal in ruby >= 1.9.2
].freeze
```

Zeitwerk decorates `Kernel#require` too ([here](https://github.com/fxn/zeitwerk/blob/main/lib/zeitwerk/kernel.rb)).

**Comment by dentarg** [comment]
Does something need to change in Sinatra in order to make it work with Zeitwerk? 

Is it only an issue when using [`sinatra/config_file`](https://github.com/sinatra/sinatra/blob/v3.0.2/sinatra-contrib/lib/sinatra/config_file.rb)?

**Comment by fxn** [comment]
@dentarg yes, Sinatra needs to be updated.

`Sinatra::Base.cleaned_caller` filters out _known_ decorated requires taking `CALLERS_TO_IGNORE` into account. Of course, this is brittle, the decorations performed by the client application or its dependencies are out of the control of Sinatra.

Currently, this is broken. For example, Sinatra is not even able to correctly find the application file:

```ruby
require 'zeitwerk'
require 'sinatra'

p Sinatra::Application.app_file # Points to kernel.rb in Zeitwerk
```

The quick fix is to add Zeitwerk to that array. Solving the fundamental brittleness of this logic is up to the project.

**Comment by fxn** [comment]
I guess you want to exclude `zeitwerk` like you exclude `active_support`. But project maintainers should know for certain.

**Comment by dentarg** [comment]
> project maintainers should know for certain

I'm not so sure, [that code](https://github.com/sinatra/sinatra/blame/6ad41b1a75bea6a0916f87264bf9d92c755f85d4/lib/sinatra/base.rb#L1205) hasn't been [meaningful updated in 10+ years](https://github.com/sinatra/sinatra/blame/62b6e1f871319089a4b09e172a8add2dbae44bd8/lib/sinatra/base.rb#L1710) and those people aren't really active here anymore.

**Comment by fxn** [comment]
I believe logic seems straightforward if you look at usage, and understand what are the array elements for.

**Comment by DawidJanczak** [comment]
@fxn I opened a PR for this, but I'm having problems testing the functionality: https://github.com/sinatra/sinatra/pull/1831#issuecomment-1290618453 Can you think of any way to make Zeitwerk appear on subsequent calls stack trace?
