### ISSUE TITLE
Weird params behavior

### ISSUE THREAD

**Issue by nolyoi** [sinatra/sinatra#1828]
I was trying to modify the params I was receiving and I was struggling to convert the keys to symbols. I eventually had to settle on `params.to_h.transform_keys(&:to_sym)` to get it to work. Now, I could've sworn I've never had to do this in the past, so potentially I screwed something up, I just have no idea what. If it isn't an error on my end though, here's some of my output:

```ruby
#567354) params.is_a? Hash
true
(ruby@puma: cluster worker 1: 567080 [backend]#567354) params.transform_keys(&:to_sym)
{"name"=>"Device 1",
 "device_id"=>"D1234",
 "scheduled_at"=>"2022-10-19 18:30:08 +0000",
 "location"=>"office1",
 "first_name"=>"dsf",
 "last_name"=>"zdsfgdf",
 "password"=>"dsgdf",
 "email"=>"dsfgsd@sdfs.com"}

(ruby@puma: cluster worker 1: 567080 [backend]#567354) params.transform_keys!(&:to_sym)
{"name"=>"Device 1",
 "device_id"=>"D1234",
 "scheduled_at"=>"2022-10-19 18:30:08 +0000",
 "location"=>"office1",
 "first_name"=>"dsf",
 "last_name"=>"zdsfgdf",
 "email"=>"dsfgsd@sdfs.com"}

(ruby@puma: cluster worker 1: 567080 [backend]#567354) params.symbolize_keys(&:to_sym)
{"name"=>"Device 1",
 "device_id"=>"D1234",
 "scheduled_at"=>"2022-10-19 18:30:08 +0000",
 "first_name"=>"dsf",
 "last_name"=>"zdsfgdf",
 "password"=>"dsgdf",
 "email"=>"dsfgsd@sdfs.com"}

(ruby@puma: cluster worker 0: 567080 [backend]#567813) params.to_h.transform_keys(&:to_sym)
{:name=>"Device 1",
 :device_id=>"D1234",
 :scheduled_at=>"2022-10-19 18:30:08 +0000",
 :location=>"office1",
 :first_name=>"dsf",
 :last_name=>"zdsfgdf",
 :password=>"dsgdf",
 :email=>"dsfgsd@sdfs.com"}
```

**Comment by dentarg** [comment]
`params` is not a real hash, see https://github.com/sinatra/sinatra/blob/v3.0.2/lib/sinatra/indifferent_hash.rb

some more info in https://github.com/sinatra/sinatra/issues/1592

**Comment by nolyoi** [comment]
> `params` is not a real hash, see https://github.com/sinatra/sinatra/blob/v3.0.2/lib/sinatra/indifferent_hash.rb
> 
> some more info in #1592

Okay I see now. I'm still confused as to why `params.transform_keys(&:to_sym)` doesn't work though since this IndifferentHash seems to have transform_keys methods?

**Comment by dentarg** [comment]
`convert_key` always converts keys to strings

**Comment by nolyoi** [comment]
> `convert_key` always converts keys to strings

ah gotcha okay thanks for clearing that up.

**Comment by NobodysNightmare** [comment]
> Now, I could've sworn I've never had to do this in the past, so potentially I screwed something up

Looking at the timing you brought this up, did your code include a `select` or `reject` call before using `transform_keys` in the past?

I was wondering the same (some code broke after an upgrade) and it turns out that these methods did return regular hashes before the upgrade (and thus `transform_keys` worked) but return an indifferent hash after the upgrade. See https://github.com/sinatra/sinatra/pull/1711

**Comment by nolyoi** [comment]
> Looking at the timing you brought this up, did your code include a `select` or `reject` call before using `transform_keys` in the past?

I don't recall using `select` or `reject` previously. So, if you used one of those before it returned a regular ruby hash?

**Comment by NobodysNightmare** [comment]
Exactly

Nolan Mayersky ***@***.***> schrieb am Di., 22. Nov. 2022,
18:53:
