### ISSUE TITLE
Invalid behaviour according to RFC.

### ISSUE THREAD

**Issue by ioquatix** [sinatra/sinatra#1844]
https://github.com/sinatra/sinatra/blob/4162502937722cdb0351f025142bf6ed9307c5e4/test/request_test.rb#L20-L27

This test is invalid according to <https://www.rfc-editor.org/rfc/rfc2046#section-5.1>.

I'm assuming this is because of <https://github.com/golang/go/issues/52519>?

**Comment by dentarg** [comment]
It was added in https://github.com/sinatra/sinatra/pull/1743 to address https://github.com/sinatra/sinatra/issues/1739

As stated in that issue it was really easy to make any rack app blow up

I'm running my apps with the middleware at https://github.com/sinatra/sinatra/issues/1739#issuecomment-1024115052 to avoid that happening

**Comment by dentarg** [comment]
Grape has a similar test I think? https://github.com/ruby-grape/grape/pull/2161/files#diff-ec432e9828fcad2ca5ef8aa6ac13454b84782708f4d2a5a8c23de9342d329d1a

**Comment by ioquatix** [comment]
@dentarg maybe you can give your opinion on https://github.com/rack/rack/issues/1994#issuecomment-1352117937 and the related issues.

**Comment by dentarg** [comment]
Sure

**Comment by dentarg** [comment]
Or well, my opinion is that we can not expect everyone on the internet to be following RFCs :-) We need to guard our apps against non-standard behaviour. I think that's what Sinatra is doing here? Sure, it would be better to address in directly in Rack.

**Comment by dentarg** [comment]
I think we have an understanding why this test case exist in Sinatra, can we close this issue @ioquatix?

It was needed after https://github.com/rack/rack/pull/1572 that closed https://github.com/rack/rack/issues/761.

**Comment by ioquatix** [comment]
You can close it, but if we adopt some mechanism to indicate "bad request" you may want to change the behaviour.

**Comment by ioquatix** [comment]
In Rack 3.1, this will exist: https://github.com/rack/rack/pull/2019
