### ISSUE TITLE
Template layout with yield does not parse nested template

### ISSUE THREAD

**Issue by whitehorsesoft** [sinatra/sinatra#1856]
# Description
When calling `yield` in a layout, the nested template is not parsed properly. Instead, the raw content of the nested template is used.

# Steps to Reproduce
1. Gemfile with haml, sinatra, and webrick
2. ruby file with following content:
```ruby
# frozen_string_literal: true

require 'rubygems'
require 'bundler'
Bundler.setup(:default)
require 'sinatra'

get '/' do
  haml :test
end
```
3. ~/views/layout.haml with following content:
```haml
!!!
%html
  %body
    %h1 A Header
    =yield
```
4. ~/views/test.haml with following content:
```haml
%p hello there
```

# Expected
When navigating to localhost:4567, the content should be a header, followed by a paragraph with the content "hello there".

# Versions
Ruby v 3.1.3
Sinatra v 3.0.5
Bundler v 2.3.36
Haml v 6.1.1
Webrick v 1.7.0

**Comment by whitehorsesoft** [comment]
This screenshot shows the problem:
![image](https://user-images.githubusercontent.com/24835884/209818500-806372c2-a594-4277-a405-bc0104ef5b75.png)

**Comment by dentarg** [comment]
It is due to Haml 6, use `!= yield` (https://github.com/sinatra/sinatra/pull/1825), please close this issue

**Comment by whitehorsesoft** [comment]
Confirmed, ty
