### ISSUE TITLE
Sinatra 3.0.5 on Rubygems has wrong version in `version.rb`

### ISSUE THREAD

**Issue by ghiculescu** [sinatra/sinatra#1882]
```
gem uninstall sinatra # uninstall all versions
gem install sinatra
gem contents sinatra
cat /PATH_TO_GEMS/sinatra-3.0.5/lib/sinatra/version.rb
```

Actual:

```ruby
# frozen_string_literal: true

module Sinatra
  VERSION = '3.0.4'
end
```

Expected:

```ruby
# frozen_string_literal: true

module Sinatra
  VERSION = '3.0.5'
end
```

As a result, when you start a Sinatra server it shows the wrong version number. Note that the [VERSION](https://github.com/sinatra/sinatra/blob/master/VERSION) file is correct. I'm not sure why both exist.

I think it's probably worth releasing a new version at some point to fix this (very minor) confusion.

**Comment by jkowens** [comment]
Oof how did I mess that up 🤦‍♂️

**Comment by ghiculescu** [comment]
I checked, and the last commit before the "release" commit (https://github.com/sinatra/sinatra/commit/0b2c3a7c5a55ceb208a24843c1315c06da638a15) *is* in the gem. So it's a very minor issue.

**Comment by dentarg** [comment]
Ah so the gem was built from the commit before the code was changed to say 3.0.5 in  https://github.com/sinatra/sinatra/commit/186106d153d08c77e4add922e93b6c4a9d9315f6

I guess this is impossible to correct as we can't release 3.0.5 again.

Close without action? Or close when next release is out?

(It is good that it is logged as an issue)

**Comment by jkowens** [comment]
Yeah, I'm not sure how that happened. I better look at the rake release task and figure out how to use it correctly. My best guess is I released a 2x version and had to jump thru some hoops and forgot to revert before releasing 3.0.5.

**Comment by jkowens** [comment]
@dentarg I'm good with closing with next release. It's a nice reminder 😅
