### ISSUE TITLE
Remove `Tilt::Cache` usage (needed for Tilt 3)

### ISSUE THREAD

**Issue by jeremyevans** [sinatra/sinatra#1884]
I'm [planning on deprecating `Tilt::Cache`](https://github.com/jeremyevans/tilt/commit/2a021538630138569532f1eb0fe62aec8edd0416) in the next release of tilt (2.2.0), as it isn't used internally, isn't thread safe, and doesn't add any real value (faster to use a plain hash).  Sinatra should either copy the Tilt::Cache implementation to somewhere internal to Sinatra, or (my recommendation) switch to using a plain hash, or if you really need API compatibility for the `#fetch` method:

```ruby
class Cache < Hash
  def fetch(*args)
    super(args) do
      self[args] = yield
    end
  end
end
```

**Comment by dentarg** [comment]
Thanks for the heads-up! 

@jeremyevans Just to be clear, Tilt is not following https://semver.org/ and there will continue to be breaking changes in the 2.x series?

Looks like Sinatra (sinatra-contrib) isn't fully compatible with Tilt 2.1.0 that was just released: https://github.com/sinatra/sinatra/actions/runs/4235438155/jobs/7359051065#step:6:124 (any help you can contribute on this would be appreciated)

**Comment by jeremyevans** [comment]
AFAIK, Tilt doesn't advertise semver support and has never (intentionally) followed it.  Going forward, as with all libraries I maintain, significant backwards incompatible changes will result in major version bumps.  Minor backwards incompatible changes may happen with minor version bumps.  As the saying goes, all bug fixes are incompatibilities.  While `Tilt::Cache` will be deprecated in the next release of tilt, it will not be removed until tilt 3.

The failure in the job you linked to appears unrelated to tilt.  You are installing slim 0.6.1, when the current version of slim is 5.0.0: https://github.com/sinatra/sinatra/actions/runs/4235438155/jobs/7359051065#step:6:64

**Comment by dentarg** [comment]
Thanks for clarifying. 

> The failure in the job you linked to appears unrelated to tilt. You are installing slim 0.6.1, when the current version of slim is 5.0.0: https://github.com/sinatra/sinatra/actions/runs/4235438155/jobs/7359051065#step:6:64

Ah yes, I did look at this. It happens because the current version of Slim does not allow Tilt 2.1.0: https://rubygems.org/gems/slim So Bundler finds a very old version that didn't specify any requirements for Tilt
