### ISSUE TITLE
Release 3.1.0

### ISSUE THREAD

**Issue by dentarg** [sinatra/sinatra#1929]
Looks like a new minor version could be released with the following changes

* https://github.com/sinatra/sinatra/pull/1922 (allows use of Tilt 2.2.0 without deprecation warning)
* https://github.com/sinatra/sinatra/pull/1924
* https://github.com/sinatra/sinatra/pull/1911
* https://github.com/sinatra/sinatra/pull/1913
* https://github.com/sinatra/sinatra/pull/1900
* https://github.com/sinatra/sinatra/pull/1932

**Comment by mikevoets** [comment]
This would be great!
