### ISSUE TITLE
Disable `session_hijacking` by default

### ISSUE THREAD

**Issue by dentarg** [sinatra/sinatra#1930]
Does it still make sense to use `Rack::Protection::SessionHijacking` now that TLS transport is very wide-spread? 

I've found it a bit annoying as browser updates happens quite frequently these days.

https://github.com/sinatra/sinatra/blob/3fe6297a4bec04e279df7842fe50fb7526dea65a/rack-protection/lib/rack/protection.rb#L55

Ping @sinatra/sinatras-helpers

**Comment by jkowens** [comment]
@dentarg you're right, I think this could be switched to an optional protection.

**Comment by dentarg** [comment]
We could do that move with Sinatra 4.0
