### ISSUE TITLE
Add `base64` dependency

### ISSUE THREAD

**Issue by dentarg** [sinatra/sinatra#1937]
`base64` needs to be a explicit dependency in Ruby 3.4.0

Similar PRs are https://github.com/rails/rails/pull/48907 and https://github.com/rack/rack/pull/2109

It is possible to get away with `pack`/`unpack` methods: https://github.com/rack/rack/pull/2110 but Sinatra (authenticity_token middleware in rack-protection) do use the two urlsafe methods: https://github.com/sinatra/sinatra/blob/35bc85b18a4154a5bf94044460c992b58d65c964/rack-protection/lib/rack/protection/authenticity_token.rb#L227-L233

**Comment by zzak** [comment]
Why not just add it as a dependency like any other gem we need?

**Comment by dentarg** [comment]
I didn't say we shouldn't, just pointed out it was a possibility – in the case of Rack (https://github.com/rack/rack/pull/2110) it was very simple.

I do not advocate for Sinatra to maintain this code: https://github.com/ruby/ruby/blob/efd611ceb661a230f121797079376cdb4e831951/lib/base64.rb#L80-L113

**Comment by jkowens** [comment]
I suspect some may be using rack-protection in applications that try to be interoperable with Rails csrf protection (mounted apps). Staying in-line with Rails may not be something we want to aim for, but just wanted to throw that out there. That's the only reason I can think of for sticking with Base64.
