### ISSUE TITLE
Sinatra::IndifferentHash does not support initialization with any hash or key-value pair list

### ISSUE THREAD

**Issue by nelsnelson** [sinatra/sinatra#1948]
In short, the following snippet from https://api.rubyonrails.org/classes/ActiveSupport/HashWithIndifferentAccess.html does not work:

```rb
hash = ActiveSupport::HashWithIndifferentAccess.new(a: 1) # => {"a"=>1}
hash.keys # => ["a"]
```

Instead, this is what happens with `Sinatra::IndifferentHash`:

```rb
hash = Sinatra::IndifferentHash.new(a: 1) # => {}
hash.keys # => []
```

**Comment by dentarg** [comment]
This looks like an intentional omission by https://github.com/sinatra/sinatra/commit/44c3cb89b7c9e26ce66e0e9bfe5a481fbef6fc22 (https://github.com/sinatra/sinatra/pull/1279) (6 years ago),  as this was possible with `ActiveSupport::HashWithIndifferentAccess` 14 years ago: https://github.com/rails/rails/commit/0bd668fd8867b01c15f943613707b3c7eb59afff

Also:

```shell
$ irb
irb(main):001:0> Hash.new(a: 1)
=> {}
```

Maybe @mwpastore or @jkowens want to weigh in

**Comment by dentarg** [comment]
Though the documentation comments should probably be updated: https://github.com/sinatra/sinatra/blob/e130771db80acc380f05323fc7d7c0fa258b7d42/lib/sinatra/indifferent_hash.rb#L22-L32

Looks like they were just copied and some search-and-replace was done

**Comment by nelsnelson** [comment]
Interesting that it was an intentional omission.  Thanks for the information, @dentarg .  🙇 

Is there a known explanation for why [the current `active_support` version's support for initializing with a constructor hash](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/hash_with_indifferent_access.rb#L75) might not have been ported?

I guess if its not a bug, do you think a feature addition proposal has a chance of acceptance?

**Comment by dentarg** [comment]
I leaning towards that we shouldn't add that to Sinatra, as less code is less code to maintain, and the Sinatra project is very short on maintainers and maintainers time. Sinatra is not Rails/ActiveSupport so we shouldn't need to mimic every aspect of it.

I'm open to hear thoughts from the rest of @sinatra/sinatras-helpers though

**Comment by dentarg** [comment]
Instead, time could be better spent on allowing users of Sinatra to use `ActiveSupport::HashWithIndifferentAccess` over `Sinatra::IndifferentHash` if they want (the user would need to add `active_support` as a dependency to their project). I don't know the feasibility of this idea though.

**Comment by jkowens** [comment]
Currently `Sinatra::IndifferentHash.new` behaves more like a real `Hash` where the object passed to `new` becomes the default value for missing keys.

ex:

```
 h = Sinatra::IndifferentHash.new(a: 1)
 h #=> {}
 h[:b] #=> {"a"=>1}
 ```
 
 The documentation definitely should be updated to make that clear.

**Comment by nelsnelson** [comment]
I see.  Well, I suppose I'll close this issue, then.  Thanks for the discussion, everyone.

**Comment by dentarg** [comment]
Let's keep it open until the documentation has been updated, so we don't forget.
