### ISSUE TITLE
Failing tests with ruby-head

### ISSUE THREAD

**Issue by dentarg** [sinatra/sinatra#1988]
CI passed just a few days ago at https://github.com/dentarg/sinatra/actions/runs/7423722745/job/20201775664#step:3:23
`ruby 3.4.0dev (2024-01-04T16:25:31Z :detached: 6c252912af) [x86_64-linux]`

but now fails https://github.com/dentarg/sinatra/actions/runs/7423722745/job/20201775664
`ruby 3.4.0dev (2024-01-09T19:02:26Z :detached: 80da9b1547) [x86_64-linux]`

on this test https://github.com/sinatra/sinatra/blob/main/rack-protection/spec/lib/rack/protection/encrypted_cookie_spec.rb#L500-L504

I wonder why it started happening now? Changes in Ruby: https://github.com/ruby/ruby/compare/6c252912af...80da9b1547

**Comment by dentarg** [comment]
So https://github.com/sinatra/sinatra/commit/d6294df43bdca531d04a5ab5bc3fcc58f2ce99bc didn't help, that's interesting

**Comment by dentarg** [comment]
We have more fails, sinatra tests too: https://github.com/sinatra/sinatra/actions/runs/7476448903/job/20346834173#step:5:25

Maybe this one https://github.com/sinatra/sinatra/blob/fa5a1399b6b63bcca2df81db284ff64a89a2b599/test/routing_test.rb#L763-L766

**Comment by dentarg** [comment]
From @byroot on Slack

> Clearly a bug IMO. That line doesn’t mutate that interpolated string.

So it should be reported to https://bugs.ruby-lang.org/, but it would be good to have a smaller reproducer for that. 

I don't have ruby-head built locally and `rubylang/ruby:master-nightly-bionic` (docker image) isn't up-to-date

```
root@12277fb5a008:/app# ruby -v
ruby 3.3.0dev (2022-12-26T15:28:38Z master a968d783a3) [x86_64-linux]
```

I guess I could try to build that image myself though, not sure when I get to it though.

**Comment by byroot** [comment]
`master-nightly-jammy` doesn't cut it? It was last built 3 hours ago: https://hub.docker.com/layers/rubylang/ruby/master-nightly-jammy/images/sha256-629a6b60bceb263049c8b6b6e48dbd637356794f481da90f7abfcd1574a57dac?context=explore

**Comment by dentarg** [comment]
@byroot Oops, of course 🤦 didn't think that through. Thanks.

**Comment by dentarg** [comment]
ruby-head no longer has any failing tests (example: https://github.com/sinatra/sinatra/actions/runs/8448241782)
