### ISSUE TITLE
Upgrading to 4.0.0 required me to do a new request.body.rewind before a request.body.read

### ISSUE THREAD

**Issue by JonJagger** [sinatra/sinatra#2000]
Hi
I use sinatra in https://cyber-dojo.org an open-source web app for practising TDD with all £$ proceeds going to charity.
Sinatra is great :-) So first off - a big thank you.

The cyber-dojo creator repo is one of cyber-dojo's dockerized microservices.
I was previously using a sinatra 3.2.0 base-image and in one place I do a `request.body.read` 
https://gitlab.com/cyber-dojo/creator/-/blob/762ba5d23423a4646330626497167668ca58da6e/app/app_base.rb#L73

I upgraded to a new sinatra 4.0.0 base-image (to fix a snyk vulnerability) and I found that the
call to `request.body.read` always gave me an empty body. And so naturally things stopped working.
On a hunch I added a call to `request.body.rewind` before that call, and all is now working again.
https://gitlab.com/cyber-dojo/creator/-/blob/0c3181dfe6c95354531131e76c038bf75ba26baf/app/app_base.rb#L73

So I speculate that somewhere in the new 4.0.0 code there is one (or more) calls that previously did
a rewind after a read but that are no longer doing the rewind. Or a new call to read without a following rewind.

Two Gemfile.lock's, one for the 3.2.0 image and one for the 4.0.0 image are here:
https://gitlab.com/cyber-dojo/creator/-/tree/0c3181dfe6c95354531131e76c038bf75ba26baf/docs/debug

Apologies if this report should be going to a different repo, eg rack.

Thanks again

**Comment by JonJagger** [comment]
On reflection, this should be posted to the rack repo. 
So closing.

**Comment by dentarg** [comment]
The fact that you should call `#rewind` has been in the README since 2010 (df0e53498bce859c0aad136e639f83a20bc962f4, almost 14 years now).

https://github.com/sinatra/sinatra?tab=readme-ov-file#accessing-the-request-object
