### ISSUE TITLE
paradise lost, also, stability (GETTING STARTED does NOT)

### ISSUE THREAD

**Issue by costa** [sinatra/sinatra#2003]
Try the very essence of sinatra — running a simple web app with minimal effort:
`docker run --rm ruby bash -ec 'gem install sinatra; gem install puma; ruby -e "require %[sinatra]; get(%[/]){%[Hello stability!]}"'`
and FAIL miserably — sinatra is too advanced for such nonsense now:
`Sinatra could not start, the "rackup" gem was not found!`

Thank you for maintainers for maintaining — and advancing— this complex beast of a system.

**Comment by dentarg** [comment]
We had consensus around not making `rackup` a hard dependency in the Rack 3 pull request, see the discussion from https://github.com/sinatra/sinatra/pull/1857#issuecomment-1871025365

I've made https://github.com/sinatra/sinatra/pull/2009 to update the README to reflect this, thanks for bringing attention to it
