### ISSUE TITLE
sinatra-contrib tests fails on truffleruby 24.0.0

### ISSUE THREAD

**Issue by dentarg** [sinatra/sinatra#2007]
We had [passing tests](https://github.com/sinatra/sinatra/actions/runs/7583324414/job/20654722950#step:6:95) with `truffleruby 23.1.2, like ruby 3.2.2, Oracle GraalVM Native [x86_64-linux]` on Jan 19.

We now have [failing tests](https://github.com/sinatra/sinatra/actions/runs/8432253102/job/23092338345#step:6:70) with `truffleruby 24.0.0, like ruby 3.2.2, Oracle GraalVM Native [x86_64-linux]`.

Saving the log here

```
Failures:

  1) Sinatra::Capture hamlit behaves like a template language allows nested captures
     Failure/Error: expect(render(engine, "nested_#{lang}")).to eq("Say Hello World!")

       expected: "Say Hello World!"
            got: "Say Hello \#{::Hamlit::Utils.escape_html((a.strip))}"

       (compared using ==)
     Shared Example Group: "a template language" called from ./spec/capture_spec.rb:41
     # ./spec/capture_spec.rb:36:in `block (3 levels) in <top (required)>'

  2) Sinatra::Capture hamlit behaves like a template language captures content
     Failure/Error: expect(render(engine, "simple_#{lang}")).to eq("Say Hello World!")

       expected: "Say Hello World!"
            got: "Say Hello \#{::Hamlit::Utils.escape_html((a.strip))}!"

       (compared using ==)
     Shared Example Group: "a template language" called from ./spec/capture_spec.rb:41
     # ./spec/capture_spec.rb:32:in `block (3 levels) in <top (required)>'

  3) Sinatra::Capture haml behaves like a template language allows nested captures
     Failure/Error: expect(render(engine, "nested_#{lang}")).to eq("Say Hello World!")

       expected: "Say Hello World!"
            got: "Say Hello \#{(::Haml::Util.escape_html((a.strip))).to_s}"

       (compared using ==)
     Shared Example Group: "a template language" called from ./spec/capture_spec.rb:40
     # ./spec/capture_spec.rb:36:in `block (3 levels) in <top (required)>'

  4) Sinatra::Capture haml behaves like a template language captures content
     Failure/Error: expect(render(engine, "simple_#{lang}")).to eq("Say Hello World!")

       expected: "Say Hello World!"
            got: "Say Hello \#{(::Haml::Util.escape_html((a.strip))).to_s}!"

       (compared using ==)
     Shared Example Group: "a template language" called from ./spec/capture_spec.rb:40
     # ./spec/capture_spec.rb:32:in `block (3 levels) in <top (required)>'
```

cc @eregon

**Comment by eregon** [comment]
@andrykonchin Could you investigate?
From the output it looks like `#{}` interpolation is not done, but that surely works fine in regular Ruby code.
Maybe some Regexp issue or so since this is likely interpolation in some template or so?

**Comment by dentarg** [comment]
Still fails on truffleruby 24.0.1 (but I guess it will be fixed eventually when truffleruby vendors the fixed prism?)

**Comment by eregon** [comment]
@dentarg What about truffleruby-head? Does it work there? We update Prism frequently on master, but we don't update it for patch releases.

**Comment by dentarg** [comment]
Yeah head works! https://github.com/sinatra/sinatra/actions/runs/9313939939/job/25637217253

**Comment by eregon** [comment]
Nice, then that fix will be in 24.1.0, and in the meantime I guess either allow to fail for that job or pin to 23.1 or only test `truffleruby-head`.

**Comment by dentarg** [comment]
It is allowed to fail. This was just me checking in and making a note after seeing the failure in the CI summary :-)

Thanks for the info about 24.1.0. I will leave this open until we have that.

**Comment by dentarg** [comment]
There is https://github.com/oracle/truffleruby/releases/tag/graal-24.1.0 now and even https://github.com/oracle/truffleruby/releases/tag/graal-24.1.1
