### ISSUE TITLE
`StaticTest#test_handles_valid_byte_ranges_correctly_0` fails with Rack 3.1

### ISSUE THREAD

**Issue by dentarg** [sinatra/sinatra#2019]
From https://github.com/sinatra/sinatra/actions/runs/9565078027/job/26367226933#step:5:52

```
  4) Failure:
StaticTest#test_handles_valid_byte_ranges_correctly_0 [test/static_test.rb:147]:
Incorrect Content-Length for bytes=0-0.
--- expected
+++ actual
@@ -1,3 +1 @@
-# encoding: US-ASCII
-#    valid: true
-"1"
+nil
```

**Comment by dentarg** [comment]
This test does not fail with rack head (3.2) https://github.com/sinatra/sinatra/actions/runs/9565078027/job/26367227454

**Comment by dentarg** [comment]
Update on this from @ioquatix at https://github.com/rack/rack/pull/2219#issuecomment-2219715571

This code is linked https://github.com/sinatra/sinatra/blob/5640495babcb4cfd69ba650b293660b7446402da/lib/sinatra/base.rb#L298

The full method https://github.com/sinatra/sinatra/blob/5640495babcb4cfd69ba650b293660b7446402da/lib/sinatra/base.rb#L290-L304

The original `headers.delete 'Content-Length'` was added in https://github.com/sinatra/sinatra/commit/a1f4fa9cee4114354631cefb6316035bfbef372d

The condition has then been extended several times

* https://github.com/sinatra/sinatra/commit/ff39bd2bcc707c746fe3797f142ea8c07c8988d3
* https://github.com/sinatra/sinatra/commit/56848e4ef544c0e20f134be68887f59a553a3c54
* https://github.com/sinatra/sinatra/commit/1dfae3d87e236785cade93b7b2d1adbd4b450eaa

**Comment by ioquatix** [comment]
This looks like a good summary.

I think it's odd to delete a header like `content-length` if it was specified for a given body, unless that body has also been changed.

It's true for enumerable bodies (& streaming bodies) that `content-length` may not make sense. In that case, why was it added in the first place.

The invariant should be (1) for a given body (2) a content-length may be specified.

Both should change together, or neither should, IMHO.

**Comment by dentarg** [comment]
https://github.com/sinatra/sinatra/commit/9a01e3d4920c675219cf45d01532497c4af5dfbf added the test case that now fails (the `0..0` scenario)

https://github.com/sinatra/sinatra/blob/5640495babcb4cfd69ba650b293660b7446402da/test/static_test.rb#L139-L164

**Comment by dentarg** [comment]
`0..0` is just the first case that fails, removing it, other cases fail too

**Comment by dentarg** [comment]
If we stop doing `headers.delete 'content-length'` ([src](https://github.com/sinatra/sinatra/blob/5640495babcb4cfd69ba650b293660b7446402da/lib/sinatra/base.rb#L298)) this test (from https://github.com/sinatra/sinatra/commit/b4126e4c972f8547d04de09c18a9543a1442ba8e) starts to fail:

https://github.com/sinatra/sinatra/blob/5640495babcb4cfd69ba650b293660b7446402da/test/routing_test.rb#L164-L175

**Comment by dentarg** [comment]
It is this change all over again: https://github.com/sinatra/sinatra/commit/1dfae3d87e236785cade93b7b2d1adbd4b450eaa

If I change `value.is_a?(Rack::Files::Iterator)` to `value.is_a?(Rack::Files::BaseIterator)` the tests passes.

`Rack::Files::BaseIterator` was introduced a while ago, in rack 2.2.0, in https://github.com/rack/rack/commit/3936b90697fcaf02751e596bd9dfd0e24add9b29.

**Comment by dentarg** [comment]
https://github.com/sinatra/sinatra/commit/a1f4fa9cee4114354631cefb6316035bfbef372d aimed to fix https://github.com/sinatra/sinatra/issues/608, that issues says this commit https://github.com/sinatra/sinatra/commit/00b63ec5a5497aa2fa9777a3e899134718a13fd6 broke things; there was some discussion on that commit.

**Comment by ioquatix** [comment]
> If we stop doing `headers.delete 'content-length'`

```
     get '/' do 
       @response["Content-Length"] = "30" 
       raise Sinatra::NotFound 
     end 
```

Looks wrong to me... like why are you testing that? The application is generating an invalid response. I guess you could argue it's up to Sinatra to fix it but I'd say, it's up to the application.
