### ISSUE TITLE
Mustermann CPU spike & performance issues

### ISSUE THREAD

**Issue by dshorthouse** [sinatra/sinatra#2041]
fwiw, I noticed a significant performance degradation with sinatra/namespace and traced it to the dependent Mustermann 3.0.2 release. My Sinatra app went from a 3-4s warmup to 30-40s. See https://github.com/sinatra/mustermann/issues/140. It looks like there's work being done to resolve the issue, but if that's a longtime coming or fails, you may wish to lock it down to mustermann 3.0.1 in the meantime.

ruby 3.2.1, sinatra + sinatra-contrib 4.0.0

**Comment by dentarg** [comment]
The mustermann release will (most likely) happen before any new sinatra release.

**Comment by dentarg** [comment]
mustermann v3.0.3 is out now
