### ISSUE TITLE
Problem with Zeitwerk 2.7.0+

### ISSUE THREAD

**Issue by dentarg** [sinatra/sinatra#2047]
Using Zeitwerk 2.6.18 (last version before 2.7.0), we could start this app

https://github.com/sinatra/sinatra/blob/973c936319af9132d7ab2f60985e359d0c75c93e/test/integration/zeitwerk_app.rb#L1-L8

Like this

```
root@9bfe2a21d749:/app# ruby ./test/integration/zeitwerk_app.rb -p 0 -s puma
/usr/local/lib/ruby/3.3.0/bundled_gems.rb:75: warning: Rack::Logger is deprecated and will be removed in Rack 3.2.
== Sinatra (v4.0.0) has taken the stage on 0 for development with backup from Puma
Puma starting in single mode...
* Puma version: 6.4.3 (ruby 3.3.5-p100) ("The Eagle of Durango")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 2315
* Listening on http://127.0.0.1:38635
Use Ctrl-C to stop
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2024-10-20 22:27:28 +0000 ===
- Goodbye!
== Sinatra has ended his set (crowd applauds)
```

Since Zeitwerk 2.7.0, nothing happens:

```
root@9bfe2a21d749:/app# bundle show | grep zeitwerk
  * zeitwerk (2.7.0)
root@9bfe2a21d749:/app# ruby ./test/integration/zeitwerk_app.rb -p 0 -s puma
root@9bfe2a21d749:/app# echo $?
0
```

**Comment by dentarg** [comment]
I guess the issue is https://github.com/fxn/zeitwerk/commit/8f37a65ee5c18f0fa3e1bf28283e8ee4b1b9b39e

**Comment by DawidJanczak** [comment]
Not sure if it's related, but for us `config_file` seems to be broken with Zeitwerk 2.7.0. Accessing settings like `settings.foo` raises ```undefined method `foo' for class Sinatra::Application```

**Comment by dentarg** [comment]
@DawidJanczak Yes it is broken, @fxn changed the path in 2.7.0, the one you added earlier, we need to account for the new location too. I haven't gotten to it. Feel free to submit a PR :)

**Comment by DawidJanczak** [comment]
Hope this will work https://github.com/sinatra/sinatra/pull/2050 :)
