### ISSUE TITLE
"403 Forbidden" after upgrading to Sinatra 4.1.0

### ISSUE THREAD

**Issue by fullstackplus** [sinatra/sinatra#2070]
Hi, I would appreciate some help here. After upgrading to Sinatra 4.1.0, my app started replying with the `403 Forbidden` response code. I suspect this might be an issue with `Rack::Protection`, since other users have reported a similar issue in the past. 

Anyone experienced this issue? Thanks!

Here’s some partial output of `curl` inspecting the `Host` header:
```
❯ curl -v https://fullstackplus.tech/
* Host fullstackplus.tech:443 was resolved.
*
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://fullstackplus.tech/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: fullstackplus.tech]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.7.1]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: fullstackplus.tech
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/2 403
< content-type: text/plain
< x-content-type-options: nosniff
*
* Connection #0 to host fullstackplus.tech left intact
Host not permitted%

```

**Comment by dentarg** [comment]
Are you running it in development mode?

**Comment by dentarg** [comment]
See the section about `host_authorization` at https://github.com/sinatra/sinatra?tab=readme-ov-file#available-settings

**Comment by dentarg** [comment]
And see example at https://github.com/sinatra/sinatra/issues/2065#issuecomment-2484285707

**Comment by fullstackplus** [comment]
I don't have development or production environments configured for this app — it's running in default mode. Also, the problem went away after I locked my Sinatra version down to 4.0.0.

**Comment by fullstackplus** [comment]
> Are you running it in development mode?

I don't have development or production environments configured for this app — it's running in default mode. Also, the problem went away after I locked my Sinatra version down to 4.0.0.

**Comment by fullstackplus** [comment]
> And see example at [#2065 (comment)](https://github.com/sinatra/sinatra/issues/2065#issuecomment-2484285707)

"It is implemented as a Rack middleware, bundled with rack-protection, but not exposed as a default nor opt-in protection. "

OK, so it's exposed when your app stops accepting HTTP requests like it used to. Super effective way of letting you know it's there.

**Comment by felixonmars** [comment]
Hitting this suddenly as well. I run a very simple one-file app for my own use and it's nice to have stack trace in development mode. All my deployment suddenly stopped working when visiting from a domain after updating Sinatra to 4.1.

IMHO there should be a grace period (with warnings?) or maybe this should land in a new major release.

**Comment by dentarg** [comment]
You can also run your production apps in non-development mode, just saying.

This change was a security fix.
