### ISSUE TITLE
Parsing of paths with adjacent slashes was regressed in 1.3.0

### ISSUE THREAD

**Issue by philc** [sinatra/sinatra#403]
When parsing the request path, Sinatra is dropping a slash if the path contains two adjacent slashes. This is a regression.

In 1.2.6 from request.env:

```
"REQUEST_URI" =>"/v2//parent/child", 
"REQUEST_PATH"=>"/v2//parent/child"
```

In 1.3.0 and 1.3.1 from request.env:

```
"REQUEST_URI" =>"/v2//parent/child", 
"REQUEST_PATH"=>"/v2/parent/child"
```

For reference URI.parse maintains the double slash as expected:

```
URI.parse("http://google.com/1//23").path
=> "/1//23"
```

**Comment by habibalamin** [comment]
>Why does the double slash in there matter?

This is not as important as security, but SEO is one reason. Not sure how much of a practical effect it really has, though.
