### ISSUE TITLE
no error handling when using stream

### ISSUE THREAD

**Issue by vjoel** [sinatra/sinatra#426]
The usual sinatra error handling seems to be bypassed when using stream.

``` ruby
get "/fail-stream" do
  stream do |out|
    out << "starting to fail..."
    sleep 0.2
    raise "Failed!"
  end
end

get "/fail-nostream" do
  out = ""
  out << "starting to fail..."
  sleep 0.2
  raise "Failed!"
  out
end
```

The 'fail-nostream' get fails as expected, with backtrace in the log and response, and sinatra keeps running.

The 'fail-stream' get exits sinatra (!), and doesn't send the backtrace in the response.

**Comment by ccyrille** [comment]
I known this is an old issue but if somebody encounter the same problem, maybe this kind of implementation could solve it.

Define a helper
````
def supervised_stream(*args, &block)
  stream(*args) do |out|
    begin
      yield(out)
    rescue => e
      ...
    end
  end
end
`````
Use it
```
supervised_stream do
  ...
end
```
