### ISSUE TITLE
Plus (+) symbols are no longer being decoded into spaces when part of a URL capture

### ISSUE THREAD

**Issue by boucher** [sinatra/sinatra#463]
A route defined like so:

    get '/foo/:bar' do
        body "Hey #{params[:bar]}\n"
    end

Used to behave like this in 1.2.6:

    boucher ~ $ curl http://localhost:4567/foo/b+ar
    Hey b ar

But in 1.3.2 it behaves like this:

    boucher ~ $ curl http://localhost:4567/foo/b+ar
    Hey b+ar

This does not, however, affect params sent in the post body. Plus symbols are still converted into spaces there.

**Comment by zzak** [comment]
> :+1:  on leaving "+" => " "
