### ISSUE TITLE
Sinatra requires CTRL+C twice to shutdown

### ISSUE THREAD

**Issue by shreeve** [sinatra/sinatra#5]
When I ran a small sinatra app, I have to press CTRL+C twice to get it to shutdown.

<pre>
== Sinatra/1.0.b has taken the stage on 4567 for development with backup from Thin
>> Thin web server (v1.2.7 codename No Hup)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:4567, CTRL+C to stop
^C>> Stopping ...

== Sinatra has ended his set (crowd applauds)
== Sinatra/1.0.b has taken the stage on 4567 for development with backup from Thin
>> Thin web server (v1.2.7 codename No Hup)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:4567, CTRL+C to stop
^C>> Stopping ...

== Sinatra has ended his set (crowd applauds)
</pre>

I'm currently running:

ubuntu 9.10 (karmic)
rubygems 1.3.6
ruby 1.9.1p376 (2009-12-07 revision 26041) [i486-linux]
sinatra 1.0.b
thin 1.2.7

**Comment by ProjectDent** [comment]
I'm getting this issue. My code can be simplified down to this, and still produces the issue:

```
require 'sinatra'

class MyServer < Sinatra::Base
  get '/test' do
    'Hello world!'
  end

  run! if app_file == $0
end
```

I'm running in the terminal with `ruby my_server.rb`. If I remove the `run` line, then it only requires ctrl+c once to shutdown, but the endpoint doesn't get called, instead displaying this error:

> [28/May/2016:20:37:15 +0100] "GET /test HTTP/1.1" 404 466 0.0005

**Comment by ProjectDent** [comment]
It's because I imported `sinatra`, instead of `sinatra/base`
