### ISSUE TITLE
Conditions for filters?

### ISSUE THREAD

**Issue by rkh** [sinatra/sinatra#58]
I'm not sure if this is wanted, but it would sure be pretty easy to implement (as routes and filters already share a lot of code):

```
before '/:name', :agent => /Songbird/ do
  # ...
end

before :host => /^mobile\./ do
  # ...
end
```

What do you guys think about it? Would that be useful?

**Comment by ensirius** [comment]
Is it implemented atm?

**Comment by basex** [comment]
Here you can see some examples: http://www.sinatrarb.com/intro.html

```ruby
before :agent => /Songbird/ do
  # ...
end

after '/blog/*', :host_name => 'example.com' do
  # ...
end
```

**Comment by ensirius** [comment]
How about :except?
