### ISSUE TITLE
Add example how to access raw body request and e.g. parse JSON from it

### ISSUE THREAD

**Issue by mfn** [sinatra/sinatra#60]
Hi,

in my environment I needed to process a PUT request which has a JSON payload in its body (but it's not POST request, so I can't access that payload easily).

I found the solution at http://mini.softwareas.com/posting-json-to-a-sinatra-mongodb-service in which the guy also describes that it wasn't easy to find out; especially it's not obvious that there's a `request` object available (it may be by skimming through the tutorial, but what I mean is that it's not explicitly told albeit still very useful).

Anyway, it boils down to that with the following code

```
put '/test' do
  data = JSON.parse( request.body.read.to_s )
end
```

Only is able to easily access it (once you find out). It would be nice to document this inside the tutorial!

thx

**Comment by mathieujobin** [comment]
I have a weird issue where `request.body.read` returns an empty string, but `request.POST` contains a weird hash, there the single key is a truncated part of the json body string, and the value is another single k/v hash where the key is the continuity of the json string, and the value is yet another hash, with the last bit ...

**Comment by mathieujobin** [comment]
```
part1 = request.POST.keys.first
part2 = request.POST.values.first.keys.first
part3 = request.POST.values.first.values.first.keys.first
JSON.parse(part1+part2+part3) # VALID !
```
