### ISSUE TITLE
Unable to pass instance variables into ERB templates

### ISSUE THREAD

**Issue by era86** [sinatra/sinatra#618]
drive.rb:

``` ruby
require 'sinatra'

get "/" do
  @name = "foo"
  erb :index
end
```

index.erb:

``` erb
<h3>
  <%= @name %>
</h3>
```

Could not get this to work. However, the HAML alternative works.

**Comment by asad-awadia** [comment]
Will @name be available to use in the Layout.erb file? Or will it be only available in Index.erb?

**Comment by kgrz** [comment]
@asad-awadia It should be available in `layout.erb` as well.
