### ISSUE TITLE
Route matching fails when there are periods in last parameter

### ISSUE THREAD

**Issue by papile** [sinatra/sinatra#688]
Hello,
   I noticed with the upgrade to 1.4.1 that the route will not match if there are periods in the request.

get '/articles/10.1103/:doi' used to match for request /articles/10.1103/PhysRevLett.110.026401 in 1.3.6 and versions prior.

/articles/10.1103/PhysRevLett will match but it will fail to match with any dots after that.  Could this be related to the new functionality added for file format matching?

**Comment by ice799** [comment]
I believe I've reproduced a slightly different version of this same issue.

Here's a test case:

```
require 'rubygems'
require 'sinatra'

get "/hi/:one-:two-:three.ext" do
  puts "ok 3 params"
  puts params[:one]
  puts params[:two]
  puts params[:three]
  "ok 3 params #{params[:one]} - #{params[:two]} - #{params[:three]}\n"
end

get "/hi/:one-:two.ext" do
  puts "ok 2 params"
  puts params[:one]
  puts params[:two]
  "ok 2 params: #{params[:one]} - #{params[:two]}\n"
end
```

If you try curling with: `curl -v http://localhost:4567/hi/one-1.1.1-go.ext` you match against the second route "ok 2 params" instead of the first route, as you would expect:

```
curl -v http://localhost:4567/hi/one-1.1.1-go.ext
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4567 (#0)
> GET /hi/one-1.1.1-go.ext HTTP/1.1
> Host: localhost:4567
> User-Agent: curl/7.49.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/html;charset=utf-8
< Content-Length: 28
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Connection: keep-alive
< Server: thin 1.6.1 codename Death Proof
<
ok 2 params: one - 1.1.1-go
```

If you remove the `.ext` from the end of the route (and the test CURL request), the request matches "ok 3 params" as expected.

LMK if I should open a new issue for this @floere / @rkh

**Comment by rkh** [comment]
@ice799 could you try against master or the latest pre-release? We've completely redone the pattern parser.

**Comment by ice799** [comment]
@rkh ah, yea my test seems to work on master. i am guessing that the change which introduced mustermann fixed this bug. sorry for the noise on this issue.

i'll look around for a PR or something for this change as i think i'll need to backport this change to sinatra 1.4.x if at all possible.

**Comment by rkh** [comment]
@ice799 it's also possible to use Mustermann with 1.4 if that does the trick for you: https://github.com/sinatra/mustermann/blob/master/mustermann/README.md#-sinatra-integration
