### ISSUE TITLE
Custom logger

### ISSUE THREAD

**Issue by renholm** [sinatra/sinatra#715]
Hi,

Thanks everyone for a great framework. One question however that I think need clarification: how does one do proper application logging. I want to have CommonLogger turned off but still use the logging property to write custom logging messages from the application. 

How could this be achieved? I'm happy to update the documentation if we can come up with some best practice here. Maybe it is very simple but hard to find?

Thanks!

**Comment by zzak** [comment]
This issue seems to be resolved.
