### ISSUE TITLE
send_file with :status fails with exception

### ISSUE THREAD

**Issue by blakewatters** [sinatra/sinatra#749]
I have been trying to use `send_file` with the `:status` option to specify an alternate HTTP status code when the static fixture is rendered. This is failing with an exception in the `finish` method when Sinatra attempts to calculate the `Content-Length` header:

```
test_renders_static_assets_with_custom_status_via_options_0(StaticTest):
NoMethodError: undefined method `bytesize' for #<Rack::File:0x007fb52c6325c0>
    /usr/local/var/rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/utils.rb:335:in `bytesize'
    /Users/blake/Projects/sinatra/lib/sinatra/base.rb:149:in `block in finish'
    /Users/blake/Projects/sinatra/lib/sinatra/base.rb:149:in `each'
    /Users/blake/Projects/sinatra/lib/sinatra/base.rb:149:in `inject'
    /Users/blake/Projects/sinatra/lib/sinatra/base.rb:149:in `finish'
    /Users/blake/Projects/sinatra/lib/sinatra/base.rb:895:in `call!'
    /Users/blake/Projects/sinatra/lib/sinatra/base.rb:872:in `call'
```

It looks like what's happening is a `Rack::File` instance is being erroneously passed in to `Rack::Utils#bytesize` instead of a string. This is happening because `calculate_content_length?` is evaluating positively when you provide a `:status` option to `send_file`, but not otherwise because the `body` is an Array instead of vanilla `Rack::File` instance.

By-passing the `calculate_content_length?` block results in a `Rack::Lint` error:

```
Rack::Lint::LintError: Body yielded non-string value #<Rack::File:0x007ff6f462e498 @root=nil, @headers={}, @default_mime="text/plain", @path="/Users/blake/Projects/sinatra/test/static_test.rb", @range=0..7712>
```

Altogether this means that `send_file` is currently broken for use with any status code other than 200.

I have a test case I will push up on my fork in reference to this momentarily.

**Comment by lzap** [comment]
The `bytesize` error handling still causes issues when working with webmock and in several other scenarios. We will work on a stable reproducer.
