### ISSUE TITLE
Cannot define global before filter

### ISSUE THREAD

**Issue by sco11morgan** [sinatra/sinatra#750]
We have a nested modular Sinatra app.  I'm trying to define a before filter that runs once per request.  If I define a before filter only on the base class (GroundFloor in the example below) then it fires for requests served by the GroundFloor.  If I add it to all  (Ground, First, Second) then the filter will be executed as many times at it takes before the route is matched.  Any ideas?  Thanks

``` ruby
require 'sinatra/base'

class SecondFloor < Sinatra::Base
  get '/second' do
    "Second floor"
  end
end

class FirstFloor < Sinatra::Base
  use SecondFloor

  get '/first' do
    "First floor"
  end
end

class GroundFloor < Sinatra::Base
  before do
    puts "running before filter, params: #{params}"
  end

  use FirstFloor

  get '/' do
    "Ground floor"
  end

  run! if app_file == $0
end
```

**Comment by gsprenger** [comment]
https://github.com/brandur/sinatra-router -> this gem fixes the issue with repeated before filters.

(This issue is old and closed but it comes up at the top of results when researching the topic so maybe this can help someone else?)
