### ISSUE TITLE
Add a new filter: after_everything

### ISSUE THREAD

**Issue by multimulti** [sinatra/sinatra#762]
Hi, I want to do some heavy_processing which will not influence the response sent. So I imagined I could first send the response, close the connection etc. and then do the processing.

Could you provide a filter for executing code after the connection was shut? Or how would I do that?

**Comment by mfdavid** [comment]
patriciomacadden is right, use something else to process it. Don't mix things. Sinatra is not a batch processing tool and shouldn't try to be one. 

What you are asking for is possible, but I really think it's a bad idea in terms of design.

**Comment by zzak** [comment]
This is something that would be handler specific, as rkh mentioned, somewhat exists in puma. But this isn't something we can really do inside the boundaries of Sinatra so I'm giving this a close.
