### ISSUE TITLE
partial content request truncates response rack.session cookie

### ISSUE THREAD

**Issue by thinkOfaNumber** [sinatra/sinatra#819]
Running:
* Sinatra 1.4.3
* Windows 8.1 Pro 64bit
* Thin v1.5.1 Straight Razor
* Ruby 1.9.3p448 (2013-06-27) [i386-mingw32]
* Chrome 31.0.1650.57 m (all extensions disabled)

If I supply some audio tags in an erb:
```
<audio id="comms_alarm_sound" loop="true" src="audio/gong.wav" preload="auto"></audio>
<audio id="schedule_sound" loop="true" src="audio/theetone.wav" preload="auto"></audio>
```
Chrome does normal GETs for all the usual contect, but decides to fetch partial content for the audio with the following header:
```
Range: bytes=0-
```
Note that up until and including this point, the rack.session cookie is being sent with every request header:
```
Cookie: rack.session=BAh7CUkiD3Nlc3Npb25faWQGOgZFRiJFMDMwNmU4ZDg1NjliNGE4ODM2ZjY0%0AMDc2YWU0ZTI3ZWNhNzYwNDM1MTIxNjFlZTAxNGVmMmYyZjIwYWUzNTRhOUki%0ADXRyYWNraW5nBjsARnsISSIUSFRUUF9VU0VSX0FHRU5UBjsARiItYjhhZjFh%0ANDY2NTZiYTNkYjI3NjVmZjA2NGJjM2E4ZjhkODcxZWM5NEkiGUhUVFBfQUND%0ARVBUX0VOQ09ESU5HBjsARiItZWQyYjNjYTkwYTRlNzIzNDAyMzY3YTFkMTdj%0AOGIyODM5Mjg0MjM5OEkiGUhUVFBfQUNDRVBUX0xBTkdVQUdFBjsARiItZDU1%0ANTljYjg3NGEwOGY4NGRmNDk0MzA4MmNkYzkyNzU5N2U0ZGIyYkkiEFJtY01l%0Ac3NhZ2VzBjsARlsASSIPbWV0YUxvYWRlZAY7AEZU%0A--cbda4c1ab76d0ecfb5aa404c1e978de1996c87b2
```

The response from the server for the first partial-content audio file has the following response header (among others):
```
Set-Cookie: rack.session=BAh7BkkiD3Nlc3Npb25faWQGOgZFRiJFMDMwNmU4ZDg1NjliNGE4ODM2ZjY0%0AMDc2YWU0ZTI3ZWNhNzYwNDM1MTIxNjFlZTAxNGVmMmYyZjIwYWUzNTRhOQ%3D%3D%0A--27bdefb49980ea333fa08acf08b85ffa6ca8d96d; path=/; HttpOnly
...
Content-Range: bytes 0-191291/191292
```

Note how the session cookie is identical up until character 120 or so, and then it differs.  Chrome sees this as a new value for the session cookie, and so responds with this value on subsequent requests.

The next non-partial request has the truncated cookie in the request header, but then Sinatra responds with the original correct cookie (identical to the first I posted).

The upshot of this is that the session is destroyed when Chrome requests partial content audio and the user is logged out.

I couldn't find any mention of bugs within the last year or so.  I did find that the partial content spec is vague, and Chrome makes more use of it than other browsers.  Firefox doesn't show this behaviour as it ignores the audio completely (until later); and IE doesn't do any partial headers, so it also works.

Hope that is enough information to look into it.

**Comment by zzak** [comment]
We need to verify this was fixed by rkh/rack-protection@913a0dda055b206fca695e6750b94b9eaf8d6596

**Comment by thinkOfaNumber** [comment]
Is that feedback label for me? I've moved to a different project now, so please give me a bit of time to get back to ruby if you can.

**Comment by zzak** [comment]
I believe this was resolved, so if anyone can reproduce, please re-open the ticket or submit a new one.
