### ISSUE TITLE
Sinatra completely incompatible with HTTP gem.

### ISSUE THREAD

**Issue by krainboltgreene** [sinatra/sinatra#881]
The http.gem defines a top level `HTTP` constant, a module.

Sinatra looks for a top level `HTTP` constant and calls `run` on it, regardless of if you want it to do that.

This is pretty weird and I'm going to say, since top level constants (in my opinion) should be reserved for namespaces that the http.gem wins.

Why is Sinatra doing this possibly dangerous thing on a global constant? What if there's an HTTP constant *with* a `.run` method that does something the user doesn't want to do?

**Comment by zzak** [comment]
Not sure this is something we can fix in Sinatra, giving it a close.

Please feel free to discuss this issue on Rack.
