### ISSUE TITLE
Convert symbols into strings in documentation wherever params hash is used

### ISSUE THREAD

**Issue by kgrz** [sinatra/sinatra#903]
Reference: https://github.com/sinatra/sinatra/pull/902

The English version is done. But the rest of the languages are yet to do this. I'm adding an issue to track the progress for the authors:

- [x] .en
- [x] .de
- [x] .es
- [x] .fr (see #904)
- [x] .hu
- [x] .ja
- [x] .ko
- [x] .pt-br
- [x] .pt-pt
- [x] .ru
- [x] .zh

**Comment by davydovanton** [comment]
@kgrz I think that you can close this issue because i completed  last 4 readme files :tada: :star2: :tada:

**Comment by zzak** [comment]
Thanks for all the help! <3 <3 <3

**Comment by kgrz** [comment]
👏
