### ISSUE TITLE
Route matching with regular expressions

### ISSUE THREAD

**Issue by white-monkey** [sinatra/sinatra#917]
Hi,

The README gives two examples of regular expressions, but I think it would make things clearer to add the beginning and end of string characters ('^' and '$') to at least one example to make it clear that it is not automatically done by Sinatra. E.g. `%r{/hello/([\w]+)}` will match `/meta/hello/world` and that could go against user expectation.

**Comment by mykola-kyryk** [comment]
I believe it is better to use '\A' and '\Z' as they are safer forms of '^' and '$'.

**Comment by kytrinyx** [comment]
This is true, however it's fairly unlikely that people will use multi-line regexen for their routes.

**Comment by davydovanton** [comment]
i think that we can close this issue :tada:
