### ISSUE TITLE
Response body being set on 404 errors outside of error handler

### ISSUE THREAD

**Issue by brettbuddin** [sinatra/sinatra#922]
Within our application I'm defining the `#http_status` method for each error to control HTTP status codes:

```ruby
class RecordNotFoundError < StandardError
  def http_status; 404 end
end
```

When this exception is raised in production I receive a 404 response as I expect. However, Sinatra appears to be setting `<h1>Not Found</h1>` as the response body. I tried working around this by clearing Sinatra's defaults (error handlers included) using `Sinatra::Base.reset!` without any luck.

After looking further into it I've discovered that Sinatra is setting the response body of these 404 responses outside of the context of an error handler: https://github.com/sinatra/sinatra/blob/1f9629b1b0cf5912ca1c3ac2870d97401b07e435/lib/sinatra/base.rb#L1117

This behavior seems like it belongs within a default error handler rather than absolutely set. Perhaps somewhat along the lines of how 500 errors function by default: https://github.com/sinatra/sinatra/blob/1f9629b1b0cf5912ca1c3ac2870d97401b07e435/lib/sinatra/base.rb#L1902-L1906. As a default error handler we'd have the ability to clear it if necessary.

**Comment by zzak** [comment]
What this code really needs is a refactor, to help expose this api so you can adapt it to your needs.

**Comment by dmarcoux** [comment]
I am thinking about contributing to Sinatra and I wonder, would this issue be still relevant?

**Comment by jkowens** [comment]
Is there a reason why using the `not_found` error handler wouldn't work to customize the response?

```
not_found do
  "This page was not found."
end
```

**Comment by zzak** [comment]
Ahh, sorry I originally misunderstood the question here.

I think can use the `error {}` block to rescue the intended exception and customize the response.

In the case of 404, you can use `not_found {}`; so I'm not sure there is anything more we can do?
