### ISSUE TITLE
Incorrect request params parsing edge case

### ISSUE THREAD

**Issue by caldwecr** [sinatra/sinatra#933]
After running into this issue twice at the office I thought I'd report same.

When a sinatra route matches a post request it will improperly parse the params if they are of the form ...

 `   @params = {
        packs: [
          {
              dogs: ['Spot', 'Fido', 'Rover'],
              location: 'San Francisco',
          },
          {
              dogs: ['Doggie', 'Lassie'],
              location: 'Canada',
          },
      ],
    } `

When this scenario occurs, Sinatra will provide the route with the params hash that (incorrectly) looks like this ...
`{:packs=>[{"dogs"=>["Spot", "Fido", "Rover", "Doggie", "Lassie"], "location"=>"San Francisco"}, {"location"=>"Canada"}]}`

Each set of dogs should be a separate pack. Note also that this issue _ONLY_ occurs if the innermost array is the _FIRST_ item in the immediately surrounding hash.

In order to be thorough I've created a repo with a very lame application and test set that demonstrates the issue.

https://github.com/caldwecr/sinatra_params_issue

I hope this helps.

**Comment by zzak** [comment]
I think this is not an issue we can fix in Sinatra.

You should serialize this data in the request body and deserialize when you need it.

This could be a discussion for Rack, instead perhaps..
