### ISSUE TITLE
properly running sinatra with miltithreading support

### ISSUE THREAD

**Issue by celesteking** [sinatra/sinatra#937]
I've got a problem. Your docs don't specify on how to run Sinatra properly in 2014. 
I'd like it to support multithreading.

Currently, I have:

```
require 'sinatra'

module LongNamespace
  class App < Sinatra::Application
     .... all that
  end
end
```

Now, where do I place `LongNamespace::App.run! if LongNamespace::App.app_file == $0`? I tried placing it at the bottom of file, which led to running the server twice on Ctrl+C. 

I've tried a rackup with config.ru:

```
require './app'
LongNamespace::App.run! port: 1234
```

This works perfectly (multithread), but outputs on Ctrl+C:

```
== Sinatra has ended his set (crowd applauds)
.../rack-1.5.2/lib/rack/builder.rb:133:in `to_app': missing run or map statement (RuntimeError)
        from .../config.ru:2:in `block in <main>'
  ....
```

I tried `LongNamespace::App.run if LongNamespace::App.app_file == $0`, this doesn't pick up any routes, server is running like an empty one.

And I'm yet to actually start coding.

**Comment by virtualfunction** [comment]
thin shouldn't need to be threaded. It's driven by Event machine so should be able to handle a multiple requests from one thread / process provided your code isn't performing any long blocking operations

**Comment by rkh** [comment]
This is not entirely true. Unless you use some mechanism to give back
control to the event loop (say by using the stream helper), you basically
fall back to a single request being handled at a time.

**Comment by Edwardzyc** [comment]
According to what was mentioned, there are 3 methods of starting sinatra:

* rackup
* ruby app.rb
* handler start (thin start/puma)

Should this be condensed somehow?

**Comment by rkh** [comment]
You can also start Sinatra from a custom Ruby script, by invoking `Sinatra::Application.run!` or `Rack::Server.start` or similar, but that's probably not relevant for most users.
