### ISSUE TITLE
Is there a reason the server_settings option is not documented anywhere?

### ISSUE THREAD

**Issue by vais** [sinatra/sinatra#940]
Digging through the code I found that there is a `set :server_settings` option that does not seem to be documented anywhere (even Google search for this option and sinatra comes up with nothing). Is there a reason this is undocumented? I.e. is it ok to use this option moving forward, or will it be removed?

It makes it easy to pass options to the underlying server in a classic style app. For example:

``` ruby
require 'sinatra'
require 'webrick/https'

set :server, 'webrick'

set :server_settings,
  :DoNotReverseLookup => true,
  :SSLEnable          => true,
  :SSLVerifyClient    => ::OpenSSL::SSL::VERIFY_NONE,
  :SSLCertName        => [['CN', 'Sinatra']]

get '/' do
  Time.now.to_s
end
```

**Comment by kgrz** [comment]
I tried testing out this option and these were the results (after the `__END__` line): https://gist.github.com/kgrz/c777b851a13d425698d3 Pretty inconsistent I feel.

May be the reason for the absence of docs is the inconsistency in the options that the underlying rack handler expects. Would be a nice addition though.

**Comment by rkh** [comment]
In that particular example it's due to Sinatra overriding Port with
settings.port (and Host with settings.bind), which can be set via command
line arguments. Not that I'm saying it's not an inconsistency, that's just
why it s.

**Comment by vais** [comment]
@kgrz every server that I tried implements options differently, and only WEBrick lets you pass in a hash of configuration options (thin and puma do not). That's why `server_settings` is not documented - it is dead on arrival given how most ruby servers currently implement configuration. For what it's worth, I think WEBrick's way makes the most sense, but that's not how thin and puma choose to do things.

**Comment by kgrz** [comment]
Yes, sorry about the ambiguity in my comment, that is what I had in mind while writing it :)

**Comment by zzak** [comment]
Would welcome some documentation to clarify this between (most) of the major server handlers in Rack.

**Comment by danrice92** [comment]
Hello all, I'm a bit new to open source but I would be interested in taking on this issue!

**Comment by zzak** [comment]
@danrice92 Hey! That would be great :)

Sorry there isn't much documentation on contributing, let me know if you have any questions!

**Comment by danrice92** [comment]
@zzak Happy to help. I submitted a second PR since the last one was closed to add the samples of using `server_settings`.
