### ISSUE TITLE
Mention how to start various servers in threaded mode

### ISSUE THREAD

**Issue by kytrinyx** [sinatra/sinatra#941]
e.g. `thin --threaded start`

From discussion here: https://github.com/sinatra/sinatra/issues/937

**Comment by kgrz** [comment]
Adding checklist:



- [ ] .en  (PR: https://github.com/sinatra/sinatra/pull/993)
- [ ] .de
- [ ] .es
- [ ] .fr
- [ ] .hu
- [ ] .ja
- [ ] .ko
- [ ] .pt-br
- [ ] .pt-pt
- [ ] .ru
- [ ] .zh

**Comment by davydovanton** [comment]
Russian version #995

**Comment by DyegoCosta** [comment]
Pt-br version #996

**Comment by kytrinyx** [comment]
French version #997

**Comment by nzwsch** [comment]
Japanese version #1014

**Comment by porras** [comment]
I wrote a Spanish version in #1017

**Comment by kennym** [comment]
German version #1051

**Comment by fighterleslie** [comment]
Chinese version #1069

**Comment by zzak** [comment]
Still need `hu`, `ko` and `pt-pt`

**Comment by z2s8** [comment]
I wrote it in Hungarian: #1196

**Comment by olleolleolle** [comment]
@kgrz Can you tick the `hu` checkbox above?

**Comment by patrickgramatowski** [comment]
Polish version: #1708

**Comment by kgrz** [comment]
@patrickgramatowski Yes!

**Comment by dentarg** [comment]
Looks done to me 

(yeah we can't always get all the languages all the time 😅)
