### ISSUE TITLE
Misconfigured home page sinatrarb.com

### ISSUE THREAD

**Issue by dramforever** [sinatra/sinatra#945]
http://sinatrarb.com gives this:

> This page has been temporarily disabled due to a misconfigured custom domain.

See these two pages for information on how to configure it correctly

https://github.com/blog/1917-github-pages-legacy-ip-deprecation
https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by jhwist** [comment]
Looking at http://sinatrarb.com right now, I think this issue can be closed.

**Comment by kytrinyx** [comment]
I think you're right. Thanks!

**Comment by christhomson** [comment]
FYI — http://sinatrarb.com/ doesn't work for me. http://www.sinatrarb.com does, though.

**Comment by kytrinyx** [comment]
I'm seeing the same issue. It appears to have broken again.

**Comment by dramforever** [comment]
according to `dig`, `sinatrarb.com` still points to `207.97.227.245`,which is a "deprecated IP address" according to https://github.com/blog/1917-github-pages-legacy-ip-deprecation.

`www.sinatrarb.com` is a `CNAME`  to `sinatra.github.com` and is working correctly...But why not `sinatra.github.io`?

**Comment by rkh** [comment]
Got in touch with @bmizerany again about this.

**Comment by bmizerany** [comment]
This should be fixed. Please let me know if the changes don't propogate in a reasonable amount of time.

**Comment by christhomson** [comment]
Works great for me! :+1:

**Comment by dramforever** [comment]
It's working now. I'm closing it.
