### ISSUE TITLE
NoMethodError: undefined method `join' for #<String:0x007f62c3e6fb90> - Rack 1.6.0

### ISSUE THREAD

**Issue by celsoMartins** [sinatra/sinatra#951]
Hi all. I hope you had a really great Christmas.

After a update of Rack for the 1.6.0 version, I'm getting the issue specified on this gist and issue on rack.

https://github.com/rack/rack/issues/769
https://gist.github.com/celsoMartins/9b9935c07eaaa334d346

The best answer I had was about a problem on Sinatra. So they told me if I use the github repo of Sinatra as source, I could have the issue solved. But is not.

Because I have my issue closed on Rack ( =( ), I'm not getting more clarifying answers. I hope that here you close when it is actually resolved.

Thank you.

I'm getting exactly the same error when I run my specs, even after all the changes they asked me to do.

I really appreciate your time spent to see this. It's not a blocking issue, because I fixed my Rack on 1.5.2 version. But I don't like that. =)

Please let me know if you need more informations.

Thanks!

**My Gemfile**

source 'http://rubygems.org'

ruby '2.1.3'

gem 'json'

gem 'sinatra', :git => 'git@github.com:sinatra/sinatra.git'
gem 'sinatra-base'
gem 'rack'
gem 'tilt', '1.3.4'

gem 'mongoid'
gem 'bson_ext'

gem 'rspec'
gem 'rack-test'
gem 'simplecov'
gem 'database_cleaner'
gem 'json_spec'

gem 'thin'

**My bundle list**
- activemodel (3.2.21)
- activesupport (3.2.21)
- bson (1.11.1)
- bson_ext (1.11.1)
- builder (3.0.4)
- bundler (1.7.9)
- daemons (1.1.9)
- database_cleaner (1.3.0)
- diff-lcs (1.2.5)
- docile (1.1.5)
- eventmachine (1.0.4)
- i18n (0.7.0)
- json (1.8.1)
- json_spec (1.1.4)
- mongoid (3.1.6)
- moped (1.5.2)
- multi_json (1.10.1)
- origin (1.1.0)
- rack (1.6.0)
- rack-protection (1.5.3)
- rack-test (0.6.2)
- rspec (3.1.0)
- rspec-core (3.1.7)
- rspec-expectations (3.1.2)
- rspec-mocks (3.1.3)
- rspec-support (3.1.2)
- simplecov (0.9.1)
- simplecov-html (0.8.0)
- sinatra (1.4.5 6ce8a94)
- sinatra-base (1.4.0)
- thin (1.6.3)
- tilt (1.3.4)
- tzinfo (0.3.42)

**Comment by konklone** [comment]
Seems like it's time for another release of Sinatra to Rubygems then, right? Sinatra's latest gem version, released in April, just doesn't work right with the latest version of Rack in Rubygems. That seems like a problem.

**Comment by JoshCheek** [comment]
Looks like it's a type issue [here](https://github.com/sinatra/sinatra/blob/v1.4.5/lib/sinatra/show_exceptions.rb#L20-39).

```ruby
if prefers_plain_text?(env)
  content_type = "text/plain"
  body = [dump_exception(e)]
else
  content_type = "text/html"
  body = pretty(env, e)
end
```

If it takes the top path, `body` is an `Array`, if it takes takes the bottom path, `body` is a `String`. The type error is due to [this](https://github.com/rack/rack/commit/893a2c50#diff-c1564964c4e14dfdc91f72a068cfc3a0L86) change in Rack, where the return type of `#pretty` changed.

It was fixed on master back in July with [this](https://github.com/sinatra/sinatra/commit/b39d72d2) commit, by normalizing the value to an `Array` with `body = Array(exception_string)`, which is why pointing the Gemfile at the github repo works.

**Comment by PabloBorda** [comment]
I have exactly the SAME ISSUE, I posted the following https://github.com/sinatra/sinatra/issues/976

In ruby 1.9.3 I get  "o _dump_data is defined for class Mutex #976"


In ruby 2.2.0 I get the same error as you : 



Unexpected error while processing request: undefined method `join' for #<String:0x000000030a1380>
        /home/pborda/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in `rescue in call'
        /home/pborda/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
        /home/pborda/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
        /home/pborda/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
        /home/pborda/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
        /home/pborda/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
        /home/pborda/.rvm/gems/ruby-2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
        /home/pborda/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
        /home/pborda/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
        /home/pborda/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
        /home/pborda/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1054:in `call'
        /home/pborda/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1054:in `block in spawn_threadpool'

Any clues on that??I tried tracing the code.. removing the .join call to the string.. I dunno what else to do... I don't want to put my code into garbage.. ive been stuck with this for a week and a half

**Comment by JoshCheek** [comment]
If you have the same error, then the same solution will work (read the second comment).

**Comment by konklone** [comment]
Or Sinatra could finally publish a gem update - the last update is still April 2014. This would make people's problems go away.

**Comment by martin-svk** [comment]
+1 for gem update

What exactly blocks you guys from doing that ?

**Comment by PabloBorda** [comment]
If somebody still gets this error or similar.. 

https://github.com/sinatra/sinatra/issues/976

**Comment by maccman** [comment]
Please release a new gem - it's fairly crazy this is broken.

**Comment by nightpool** [comment]
@PabloBorda this issue pops up on any error handling path with an affected sinatra version. your issue is independent.

**Comment by shlima** [comment]
+1

**Comment by PabloBorda** [comment]
Hello,  I fix this  by just creating my own session containner object, on
RAM . Seems like replicating functionality , but all session stuff is on
ram. Anyway I don't understand the rack session need to marshal an object,
that is not so complex. By doing to_json  i can get my own string version
of the object, and is a simple string, that doesn't have any cycles,  and
it was returning the same error by storing that in the session. Another
alternative was to save session  in a database,  but I think that should be
marshaled too in the same same way, so if in both ways is marshaled and the
rack session keeps crashing and the database and the normal RAM object
works. .. why could that be. .

+1

—
Reply to this email directly or view it on GitHub
<https://github.com/sinatra/sinatra/issues/951#issuecomment-81200296>.

**Comment by nightpool** [comment]
@PabloBorda again, that's an entirely different issue. this issue only has to do with the updates to rack that broke Sinatra's fancy error page.

**Comment by epitron** [comment]
+1! Please -- just push a hotfix or something! No need for a full-on release!

**Comment by apsoto** [comment]
pointing to github repo works for now, but not a great solution

A release would be great.

**Comment by JoshCheek** [comment]
Here. I made a gem that fixes the type error by adding a method between Sinatra and Rack to normalize the result to an Array. I ran it against all of Sinatra's tests on each of the versions in its `.travis.yml`

* Gem: https://rubygems.org/gems/sinatra-fix_951
* Source: https://github.com/JoshCheek/sinatra-fix_951

**To install:**

If you're using Bundler, then add this to your Gemfile:

```ruby
gem 'sinatra-fix_951', require: 'sinatra/fix_951'
```

If you aren't using Bundler, then install it from the command-line:

```sh
$ gem install sinatra-fix_951
```

And then require it wherever you're currently requiring Sinatra:

```ruby
require 'sinatra/fix_951'
```

**Comment by epitron** [comment]
Great! Now someone just has to make this a dependency of Sinatra and push a point release! :D

**Comment by konklone** [comment]
Or just a point release, since the fix is already present on master.

Is Sinatra an abandoned project?

**Comment by kytrinyx** [comment]
Sinatra is actively maintained, however there is an unrelated issue that we'd like to fix before cutting the next release.

**Comment by JoshCheek** [comment]
Just put it in your Gemfile until the next release. Everyone keeps asking for a release to fix this. Well, here. Now you add this, when the next release is out, you'll [have to](https://github.com/JoshCheek/sinatra-fix_951/blob/5a20d6c65878e0e07177525950e961718faa89c8/sinatra-fix_951.gemspec#L13) delete it to upgrade. Problem solved.

A lot of y'all need to quit being so fkn helpless. It would be appreciated if the release cycles were shorter, but come on. The world isn't ending, and y'all can code, so you're not actually dependent on a release to fix this issue.

**Comment by parkr** [comment]
> Sinatra is actively maintained, however there is an unrelated issue that we'd like to fix before cutting the next release.

@kytrinyx What is that issue?

**Comment by kytrinyx** [comment]
The issue is this one: https://github.com/sinatra/sinatra/issues/721

**Comment by konklone** [comment]
@JoshCheek Not acting helpless -- I've fixed it in my Gemfile for months now -- my question was a serious one and not intended to introduce negativity. Lack of response on issue threads or gem updates over long periods of time is a metric I use all over GitHub when evaluating how active and healthy a project is.

@kytrinyx, thanks for the update here, and for wrangling the release process!

**Comment by epitron** [comment]
It's not helplessness, it's efficiency. Sinatra has been installed millons of times! If each of these users has to patch their Gemfile, that's thousands of wasted man-hours! :)

A hotfix is way cleaner -- nobody's Gemfiles have to change, sinatra noobs don't have to cry when they make a typo and the app cryptically blows up...

What's the issue releasing a hotfix? Are the people who can push gems not around?

**Comment by konklone** [comment]
@epitron The Sinatra team has explained what they're up to [earlier in the thread](https://github.com/sinatra/sinatra/issues/951#issuecomment-84666441): #721.

**Comment by kytrinyx** [comment]
@epitron by hotfix do you mean changing the existing release? Or adding a new point release with just that one fix in it?

**Comment by nurettin** [comment]
Because of this, currently we have to `require 'bundler/setup'` on embedded systems which isn't ideal for startup times, or we are forced to create our own gem from master branch.

**Comment by epitron** [comment]
@kytrinyx just a point release with that one fix.

**Comment by kytrinyx** [comment]
@epitron you're right, there are only upsides to cutting a point release.

We've gone ahead and released almost everything that was on master as v1.4.6: https://rubygems.org/gems/sinatra/versions/1.4.6

If you're waiting for the changes from https://github.com/sinatra/sinatra/pull/898, we're holding those back until we release 1.5.0.

**Comment by JoshCheek** [comment]
> @epitron you're right, there are only upsides to cutting a point release.
>
> We've gone ahead and released almost everything that was on master as v1.4.6: https://rubygems.org/gems/sinatra/versions/1.4.6
>
> If you're waiting for the changes from #898, we're holding those back until we release 1.5.0.

Nice nice! ^_^

**Comment by JoshCheek** [comment]
Cool, I updated my bugfix gem to inform users that they don't need it anymore since its fixed in the current Sinatra release. Also told my students. Their transition into web development should be a lot smoother now (good error messages go a long way).

Hopefully this issue can now be closed for good :)

**Comment by kytrinyx** [comment]
> good error messages go a long way

Yes!

> Hopefully this issue can now be closed for good :)

Hopefully :)

**Comment by epitron** [comment]
@kytrinyx Christmas has come early!

Thanks! :)

**Comment by spurious-mysql-80** [comment]
i gathered the solution eR6WQOJlsQQ9
