### ISSUE TITLE
Sinatra Error page will not display

### ISSUE THREAD

**Issue by burlesona** [sinatra/sinatra#961]
See example app here:
https://github.com/burlesona/sinatrabug

No matter what the exception, I'm getting `undefined method join for string` from Sinatra when `show exceptions` is enabled. If I disable `show exceptions` then I get the rack error page showing the actual exception. No combination of settings will show me the sinatra error page.

I'm not sure when or why this started happening. I ran into this issue previously and found it was related to a specific version of slim/temple (see: https://github.com/slim-template/slim/issues/552), but this time I'm getting the same error using erb and no templating.

Any insight into this?

**Comment by burlesona** [comment]
After further research I see that on master this issue appears to have been addressed:

https://github.com/sinatra/sinatra/blob/5f6168bfc92280892e819df524d4508cf9032f6d/lib/sinatra/show_exceptions.rb#L35-L37

Is there a Sinatra 1.4.6 release coming soon that will include this, and/or is Sinatra master considered production-ready in the meantime?

**Comment by zzak** [comment]
Stay tuned, for now just use `master`.
