### ISSUE TITLE
NoMethodError on show_exception.rb

### ISSUE THREAD

**Issue by gfx** [sinatra/sinatra#979]
Do you know what happens?

```
undefined method `join' for #<String:0x007f89d4f0ce08>

Extracted source (around line #37):
      [500,
       {"Content-Type" => content_type,
        "Content-Length" => Rack::Utils.bytesize(body.join).to_s},
       body]
    end

Rails.root: /path/to/app
```

https://github.com/sinatra/sinatra/blob/v1.4.5/lib/sinatra/show_exceptions.rb#L37

**Comment by namusyaka** [comment]
This was already fixed in master branch. see https://github.com/sinatra/sinatra/commit/b39d72d2a5b824b5f607b7825c4b076f527461a1
Also, you can avoid the exception by locking rack version. ref https://github.com/padrino/padrino-framework/commit/b4da2381e06e507cf79e41393bc237003c5790c4

**Comment by gfx** [comment]
I see. Thanks. Looking forward to a new version!
