### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by gfx** [sinatra/sinatra#980]
Is there any plan to release a next version? I'd like to use it via rubygems.org.

**Comment by gshutler** [comment]
Last update on this was in #973

**Comment by gfx** [comment]
I'm looking forward to the next version!

**Comment by gfx** [comment]
cc: @zzak

**Comment by zzak** [comment]
There's one ticket I've been meaning to look into further before we release.

Please use master for now, thank you!

**Comment by muraliv** [comment]
Any updated on the next release? Thanks!
