### ISSUE TITLE
Is Sinatra still being actively developed?

### ISSUE THREAD

**Issue by RepublicOfAppsLLC** [sinatra/sinatra#981]
First off, I love Sinatra, it's awesome.  This is not a complaint.

However I notice that the last release was v1.4.5 on April 8, 2014.  Most of the recent commits look like changes to README or tests and I don't see a lot of security patches or new features.

Is Sinatra still being actively developed (i.e. new features added, security updates created)?  It's possible that it's just so awesome that it hasn't needed an update since April.  :-)

I just wanted to check before I go ahead and commit to writing some new APIs in Sinatra.  This is not meant to be a complaint of any form.  :-)

I don't see the need for major new features, but I just want to know that security patches are made when needed.

Best, and thanks for all of your hard work!

**Comment by kytrinyx** [comment]
Sinatra is being actively maintained, yes. We're planning a new release, we just have a small blocker before putting it out.

**Comment by zzak** [comment]
I also want to add that Sinatra is stable. Use master and if you find any bugs, please report them.

**Comment by RepublicOfAppsLLC** [comment]
Excellent, thanks for the reply!
