### ISSUE TITLE
undefined method `join' for #<String...>

### ISSUE THREAD

**Issue by audy** [sinatra/sinatra#986]
I'm having an issue displaying classy errors in Sinatra 1.4.5.

(ran with `bundle exec rackup`)

Instead of a traceback to the actual error, I get `undefined method 'join' for #<String...>`.

I made a simple example that recreates the error: https://gist.github.com/audy/5377cdc60827b2cddceb

![screenshot 2015-03-23 21 59 45](https://cloud.githubusercontent.com/assets/115904/6794428/f325f852-d1a7-11e4-8810-ee4d62e0f2bd.png)

**Comment by kytrinyx** [comment]
Hi @audy This is fixed in master and we're about to cut a release (and by _about to_ I mean we're in the process of updating the changelog and we'll probably cut the release today).

If you need to work around it, you can point to the master branch in your Gemfile temporarily.

**Comment by audy** [comment]
Will do. Thanks!

**Comment by lgustafson** [comment]
My take is that pointing to master in a Gemfile is a good way to 
introduce non-determinism and unexpected behavior in the dependent 
projects.  Please keep in mind, many of us believe this is an 
unacceptable solution in comparison to upstream releasing a point 
release to fix bugs like this... and would have reduced the amount of 
noise on the issue list as a result.  That said, thanks for releasing a 
new version soonish...

**Comment by kytrinyx** [comment]
You can also point to a specific commit. This is, in any case, very temporary.

**Comment by kytrinyx** [comment]
Version 1.4.6 has been released: https://rubygems.org/gems/sinatra/versions/1.4.6
