### ISSUE TITLE
Release tag?

### ISSUE THREAD

**Issue by namusyaka** [sinatra/sinatra#989]
I couldn't find 1.4.6 release tag from [this page](https://github.com/sinatra/sinatra/releases).
Could you attach the release tag of 1.4.6 ver?

**Comment by kytrinyx** [comment]
Hi, sorry -- we forgot to push the tag up. It's there now: https://github.com/sinatra/sinatra/releases/tag/v1.4.6

**Comment by namusyaka** [comment]
Thank you so much!

**Comment by zzak** [comment]
<3 <3 <3 <3
