### ISSUE TITLE
Configuring different instances of the same app

### ISSUE THREAD

**Issue by mperham** [sinatra/sinatra#990]
Howdy, I'm trying to mount three copies of the same app, each with different settings:

```ruby
POOL1 = ConnectionPool.new { Redis.new(:url => "redis://localhost:6379/1") }
POOL2 = ConnectionPool.new { Redis.new(:url => "redis://localhost:6379/2") }

Myapp::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  web1 = Sidekiq::Web.new
  web1.settings.set(:redis_pool, POOL1)
  mount web1 => '/sidekiq1'

  web2 = Sidekiq::Web.new
  web2.settings.set(:redis_pool, POOL2)
  mount web2 => '/sidekiq2'
end
```

No matter which URL I hit (/sidekiq, /sidekiq1 or /sidekiq2) I always see the info for web2's Redis connection.  Is this because settings are stored at the class level?  Is there a way to mount multiple of the same webapp configured differently in the same process?

**Comment by kytrinyx** [comment]
> Is this because settings are stored at the class level?

I believe so.

I don't know of any way to mount multiple of the same webapp configured differently, but... could you use inheritance without adding behavior, to give the settings a place to live?

**Comment by rkh** [comment]
Yes, creating separate subclasses for different settings should work.
Everything inside Sinatra is built with inheritance in mind.

**Comment by mperham** [comment]
Cool beans, you both are right and awesome.  I got it working, thanks!

**Comment by kgrz** [comment]
This looks like a good candidate for docs. Should we add it?

**Comment by zzak** [comment]
@kashyap :+1: Let's do something under classic vs. modular maybe
